elastic/connectors

requirements.txt
Update elasticsearch package to 8.5.0
=> Update elasticsearch version to 8.5.0

connectors/byoc.py, connectors/conftest.py, connectors/runner.py, connectors/sources/tests/test_aws.py, connectors/sources/tests/test_mysql.py, connectors/tests/test_byoc.py, connectors/tests/test_runner.py, connectors/utils.py
=> [8.5] Fix status check (#128)

config.yml, connectors/byoc.py, connectors/byoei.py, connectors/runner.py, connectors/sources/mysql.py, connectors/sources/tests/fixtures/mysql/loadsample.py, connectors/sources/tests/support.py, connectors/sources/tests/test_mysql.py, connectors/tests/ftest.sh, connectors/tests/test_byoei.py, connectors/tests/test_runner.py, connectors/utils.py, docs/CONFIG.md
- Fix memory bloat issue on large text and dbs (#100)
=> [8.5] Fix memory bloat issue on large text and dbs (#100)

connectors/byoc.py
Apply the BE status change proposed [here](https://github.com/elastic/enterprise-search-team/issues/3153#issuecomment-1291782149)
=> Update job status

.buildkite/run_dockerized_test.sh, config.yml, connectors/byoei.py, connectors/runner.py, connectors/tests/config_mem.yml, connectors/tests/test_runner.py, connectors/utils.py, requirements.txt
=> [8.5] memory info utility (#126)

connectors/byoei.py, connectors/sources/mysql.py, connectors/sources/tests/test_mysql.py, connectors/tests/config.yml, connectors/tests/test_byoei.py, connectors/tests/test_runner.py
- do not add a new ts if the backend provides it (#150)
=> [8.5] do not add a new ts if the backend provides it (#150)

connectors/byoei.py
=> Missed a merge

.buildkite/pull-requests.json
Added a `pr-bot` definition to make sure we trigger GH checks and BK correctly
=> added a pr-bot definition

config.yml, connectors/byoc.py, connectors/tests/config.yml, connectors/tests/test_byoc.py, docs/CONFIG.md
Populate `analysis_icu` and `language_code` in config.yml to further use them in framework.
=> Surface `analysis_icu` and `language_code` in config

MANIFEST.in
make sure requirements files are part of the release
=> fix MANIFEST

connectors/byoc.py, connectors/sources/mysql.py, connectors/sources/s3.py, connectors/sources/tests/test_s3.py
=> warning cleanups

connectors/tests/ftest.sh
tweak to not use `--pyspy` on darwin
=> dont run pyspy on darwin

connectors/sources/tests/test_gcs.py
=> more cleanups

.isort.cfg, connectors/byoei.py, connectors/es/__init__.py, connectors/es/client.py, connectors/es/index.py, connectors/tests/test_es_client.py, connectors/tests/test_utils.py, connectors/utils.py
More refactoring to isolate all ES-related code
=> moved ESCLient to connectors.es

docs/DEVELOPING.md
Fixes a typo in `docs/DEVELOPER.md`
Fix a typo in `docs/DEVELOPER.md`
=> docs: fix typo

connectors/sources/gcs.py, connectors/sources/tests/fixtures/gcs/.env, connectors/sources/tests/fixtures/gcs/fixture.py
=> Fixes the GCS e2e nightly test

connectors/byoc.py, connectors/runner.py, connectors/source.py, connectors/sources/directory.py, connectors/sources/mysql.py, connectors/tests/test_byoc.py, connectors/tests/test_source.py
- Fix configuration values sent to Kibana (#287)
=> [8.6] Fix configuration values sent to Kibana (#287)

connectors/es/client.py
Removes a login log logging the first three characters of the Elasticsearch user's password.
=> Remove password log line

.github/PULL_REQUEST_TEMPLATE.md
see https://elastic.slack.com/archives/C01795T48LQ/p1673535527143469?thread_ts=1673525897.348189&cid=C01795T48LQ
=> add pull request checklist items

connectors/es/client.py
=> Fix log message

connectors/utils.py
This will backport the following commits from `main` to `8.5`:
- [Fix log message (#301)](https://github.com/elastic/connectors-python/pull/301)
=> [8.5] Fix log message (#301)

connectors/utils.py
This will backport the following commits from `main` to `8.6`:
- [Fix log message (#301)](https://github.com/elastic/connectors-python/pull/301)
=> [8.6] Fix log message (#301)

requirements/aarch64.txt, requirements/framework.txt, requirements/x86_64.txt
=> pin all deps

connectors/cli.py, connectors/config.py, connectors/services/base.py, connectors/services/sync.py, connectors/tests/test_config.py, connectors/tests/test_sync.py
This PR adds a Config class, which should load YAML config once, and accessible across the project.
=> Add Config module

connectors/source.py, connectors/sources/mysql.py, connectors/tests/test_source.py
Found a small conversion bug when I was playing with Azure+MySQL
Also clarified the label of that flag, it was unclear
=> the conversion for bool=false is broken

config.yml, connectors/services/sync.py, connectors/tests/test_sync.py, connectors/utils.py, requirements/framework.txt
we don't need `tracemem` anymore as we have `perf8` now
=> removed guppy and tracemem

connectors/utils.py
remove flake (missed in https://github.com/elastic/connectors-python/pull/328)
=> forgot to remove _snapshot

connectors/tests/test_config.py
Follow-up PR on https://github.com/elastic/connectors-python/pull/327
=> Fix test_config.py

.github/issue-up.yml
this is a test related to https://elastic.slack.com/archives/C01795T48LQ/p1673449818920819
=> testing a github issue copying app

connectors/preflight_check.py
trivial fix (warn is deprecated)
=> fix deprecation

connectors/byoc.py, connectors/byoei.py
=> [Typos] Fix some typos

docs/DEVELOPING.md
=>  Certificate verify error is thrown when syncing S3

docs/DEVELOPING.md
=> Add guidance on what permissions are necessary for the S3 connector in an IAM policy

connectors/es/client.py
=> tweak the user-agent - fixes #377

connectors/filtering/basic_rule.py, connectors/tests/test_basic_rule.py
Change the ordering to adhere to the specification.
=> [Filtering] Order basic rules in ascending order with respect to the "order" field

connectors/sources/generic_database.py, connectors/sources/mysql.py
Just some small naming improvements and removal of unnecessary comments.
=> [Refactoring] Naming improvements in MySQL and GenericDatabase connectors

connectors/sources/tests/test_generic_database.py
Camel case some class names.
~- [ ] Tested the changes locally~
~- [ ] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)~
=> [Refactoring] PascalCase class names in test

connectors/cli.py, connectors/source.py, connectors/sources/abs.py, connectors/sources/directory.py, connectors/sources/gcs.py, connectors/sources/mongo.py, connectors/sources/mysql.py, connectors/sources/network_drive.py, connectors/sources/oracle.py, connectors/sources/postgresql.py, connectors/sources/s3.py, connectors/tests/fake_sources.py, connectors/tests/test_byoc.py
This PR adds clasa variables `name` and `service_type` to each data source class.
=> Add name and service_type method to data source classes

.buildkite/nightly.yml, .buildkite/publish_docker.sh, Dockerfile, Makefile, config.yml, docs/docker.md
=> Adds docker

connectors/tests/test_utils.py
run it 3 times and get the min
=> improved the speed comparison to reduce noise

connectors/kibana.py
I had a file named `data` in my GH root, and that broke the test. I looked at the fixture and fixed the corresponding code 
For relative vs absolute path, it's a bit unclear what you wanted to do there. part of the code says it's absolute path of the file, and part of the code was making the expectation it was just the base name
=> fix filtering loading

.buildkite/nightly.yml
deactivate the e2e test for Oracle until https://github.com/elastic/connectors-python/issues/400  lands
=> remove oracle from the nighlty

.buildkite/nightly.yml, config.yml, connectors/kibana.py, connectors/sources/directory.py, connectors/sources/tests/fixtures/dir/.env, connectors/sources/tests/fixtures/dir/docker-compose.yml, connectors/sources/tests/fixtures/dir/fixture.py, connectors/sources/tests/test_directory.py, connectors/tests/ftest.sh, scripts/verify.py
=> Make the directory connector a full connector

connectors/cli.py, connectors/services/base.py, connectors/services/sync.py, connectors/tests/test_job_cleanup.py, connectors/tests/test_sync.py
- [Fix service stop code (#433)](https://github.com/elastic/connectors-python/pull/433)
=> [8.7] Fix service stop code (#433)

requirements/framework.txt
=> bump elasticsearch client

.github/ISSUE_TEMPLATE/qa_connector_package.md
Add meta data, so it is added as option for creating a new issue
=> Add meta data as name and description

connectors/byoc.py, connectors/filtering/validation.py, connectors/services/sync.py, connectors/tests/test_byoc.py, connectors/tests/test_sync.py, connectors/tests/test_utils.py, connectors/utils.py
Get rid of those functions and use string-based Enums
=> remove e2str and str2e

Makefile, connectors/byoei.py, connectors/source.py, connectors/sources/tests/fixtures/dir/fixture.py, connectors/sources/tests/fixtures/fixture.py, connectors/sources/tests/fixtures/mongodb/fixture.py, connectors/sources/tests/fixtures/s3/fixture.py, connectors/tests/test_byoc.py, connectors/tests/test_sync.py, connectors/tests/test_utils.py, connectors/tests/test_validation.py, requirements/tests.txt, setup.cfg
Backports the following commits to 8.7:
- added flake8-bugbear (#481)
=> [8.7] added flake8-bugbear (#481)

.buildkite/run_dockerized_test.sh, .buildkite/run_nigthly.sh, .github/PULL_REQUEST_TEMPLATE.md, connectors/sources/tests/fixtures/dir/fixture.py, connectors/sources/tests/fixtures/fixture.py, connectors/tests/ftest.sh
=> added a small e2e test (runs for each PR)

connectors/tests/test_validation.py
Leftover of PR #503. Remove the mock as it's not used.
=> Remove unused mock

.buildkite/run_dockerized_test.sh, .buildkite/run_nigthly.sh, connectors/byoei.py, connectors/kibana.py, connectors/services/sync.py, connectors/sources/mongo.py, connectors/sources/tests/fixtures/fixture.py, connectors/tests/test_es_client.py
We've agreed on using "TODO" instead of "XXX" throughout the codebase to document todos.
=> Use TODOs consistently throughout the codebase

connectors/tests/test_byoc.py
Remove an unused patch from tests
=> Remove unused patch

connectors/source.py
=> use a dict comprehension

connectors/cli.py
=> Documented  the `cli` module

connectors/byoei.py, connectors/tests/test_byoei.py
- added docstrings for `byoei.py`
- cleanup dead code
=> Document the `byoei` module

Makefile, connectors/byoc.py, connectors/es/client.py, connectors/logger.py, connectors/services/job_cleanup.py, connectors/sources/azure_blob_storage.py, connectors/sources/generic_database.py, connectors/sources/google_cloud_storage.py, connectors/sources/mongo.py, connectors/sources/mysql.py, connectors/sources/s3.py, connectors/utils.py, pyrightconfig.json, requirements/tests.txt
`pyright` is Microsoft's static type checker (MIT)
It detected two major bugs in our codebase (yay):
- a serializing error in the Mongo connector
- a coroutine that was never awaited in `byoc.py`
This patch fixes them and ignore a few warnings. It's now plugged into `make lint`
=> added pyright and fixed a few issues

README.md
Update the documentation to beta
=> Change tech preview with beta

connectors/sources/generic_database.py, connectors/sources/oracle.py, connectors/sources/postgresql.py, connectors/sources/tests/test_generic_database.py, connectors/sources/tests/test_oracle.py, connectors/sources/tests/test_postgresql.py
* Add Queries class
* change user to username
=> [Generic Database Connector] Create an abstract queries class (#565)

docs/DEVELOPING.md
- Add the Oracle connectors in the [developing.md](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md).
=> [Generic Database Connector] Added documentation for Oracle Database in developing.md

docs/DEVELOPING.md
- Add the Microsoft SQL connectors in the [developing.md](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md).
=> [Generic Database Connector] Added documentation for Microsoft SQL in developing.md

connectors/sources/tests/test_mysql.py
It was not obvious what the test actually tested. Using a more explicit name now.
=> [MySQL] Rename a test

connectors/sources/google_cloud_storage.py, connectors/sources/tests/test_google_cloud_storage.py, connectors/tests/test_utils.py, connectors/utils.py
- [[GCS]-Parse configurations from Kibana UI (#493)](https://github.com/elastic/connectors-python/pull/493)
=> [8.7] [GCS]-Parse configurations from Kibana UI (#493)

connectors/services/base.py
=> document the services/base.py module

connectors/sources/tests/test_google_cloud_storage.py
=> fix leak -- fixes #599

connectors/sources/tests/test_mysql.py
Small PR to improve some test names
=> [MySQL] Improve test names

connectors/sources/confluence.py, connectors/sources/tests/test_confluence.py
Rename config fields as per the comments added by @danajuratoni 
- https://github.com/elastic/connectors-python/pull/647#discussion_r1151816779
- https://github.com/elastic/connectors-python/pull/647#discussion_r1151824555
=> Rename config fields in confluence

connectors/sources/confluence.py
This PR contains changes for confluence similar to those added in Jira connector: https://github.com/elastic/connectors-python/pull/648 by @navarone-feekery 
Updates Confluence configurable fields to have the extra field properties required for 8.8 Kibana UI.
Remove `enable_content_extraction` which is now handled by pipeline flags (https://github.com/elastic/connectors-python/pull/645)
Change `is_cloud` of bool type to `data_source` of str type
The UI will display this as a dropdown
Add misc new field properties.
=> Update Confluence configurable fields to new standard

connectors/source.py, connectors/tests/test_source.py
This is a followup PR to address changes that were requested in https://github.com/elastic/connectors-python/pull/710 before automerge dismissed them.
=>  Add configurable field validations to connector framework 2/2

connectors/es/index.py, connectors/tests/test_es_index.py
This PR adds a `update_by_script` method to `ESIndex` class.
=> Add update_by_script method

connectors/source.py, connectors/sources/tests/test_google_cloud_storage.py, connectors/sources/tests/test_jira.py
Some misc changes based on previous PR comments to avoid creating tech debt.
- Replace ` with ' for error logging
- Move `is_value_empty` to Field
- Move `validate_field` to Field (now named `validate`)
=> Refactor validations

config.yml, connectors/sources/generic_database.py, connectors/sources/mssql.py, connectors/sources/tests/fixtures/mssql/fixture.py, connectors/sources/tests/fixtures/mssql/requirements.txt, connectors/sources/tests/test_generic_database.py, connectors/sources/tests/test_mssql.py, requirements/framework.txt
Backport Pytds Changes of MS-SQL Connector into 8.7
=> [8.7] Backport latest changes of MS-SQL connector to 8.7

connectors/sources/generic_database.py, connectors/sources/mssql.py, connectors/sources/tests/test_generic_database.py, connectors/sources/tests/test_mssql.py
Backport NamedTemporaryFile Changes of MS-SQL Connector into 8.7
PR: https://github.com/elastic/connectors-python/pull/772
=> [8.7] Backport NamedTemporaryFile change

connectors/sync_job_runner.py, connectors/tests/test_sync_job_runner.py
This PR adds concurrency control to job execution:
1. Only one sync job can be claimed and executed per connector.
2. A sync job can only be claimed and executed by one connector instance.
=> Add concurrency control to job execution

connectors/byoc.py, connectors/tests/test_byoc.py
This PR adds concurrency control to the `validate_filtering` method of `Connector` class
=> Add concurrency control to connector validate_filtering method

connectors/sync_job_runner.py, connectors/tests/test_utils.py, connectors/utils.py
Small improvement for the logic that truncates the ids.
The message can get big if ids are really long, which makes it harder to read and logs bloat.
Example message before change for document with long id (had it in CI):
```
[FMWK][15:41:00][DEBUG] Document with id 'customers_0_JVJMRHNL714FFJ9NW8VRPN289ZW8AZO56BOSQ21ROB9F7GO9ZTA0JKKUCW0XSXTI1I3AN5KJAW5WUYRBN3MGF5V73XLGRTWILHOL78VYWFC7NRDEVLAN9FCL9RCUQSHYU7RLM152ZNT1AWYJ617Y45HPAKRSEVHSM47Z1FQ8GLBUWJ7D06K4E5OVVAULP6TP0CV0LNH3UIRIUU3SG3158TC2699M6HK50I8S9W6O0M95IHG8X4KLYAMO0IQ54PGEN7EKK8KRXLQU1ZPR6W5PR57QE9MZDJNO5A4IS78XI45FVHP47RYTWTFAOJ6WCBAXLFE4ALSXQ4EMNQSA8Z0S13WRKAM5DDNUS7Y6AAX6PLHVZHZ9S1E59QRRTLGXI27XK36UKA4PKR478DNIXPVDM7VGQFMXI7KYMU3SCHSNS6KQKPWAKBLWP5P9G4TWB2PCD9FXJBYL9WM03L0TC34JJJT0AGNT78YVZ3OHDXMIB3W1U083ZLWNB8JW8IK55ML59KDY4W4V …
```
=> Truncate document id when logging it; reduce the message size too

connectors/sources/confluence.py, connectors/sources/generic_database.py, connectors/sources/google_cloud_storage.py, connectors/sources/jira.py, connectors/sources/mongo.py, connectors/sources/mssql.py, connectors/sources/mysql.py, connectors/sources/network_drive.py, connectors/sources/oracle.py, connectors/sources/s3.py, connectors/sources/sharepoint.py, connectors/sources/tests/test_jira.py
- Update labels for all configurable fields
=> Update labels for configurable fields

config.yml, connectors/sources/servicenow.py, connectors/sources/tests/test_servicenow.py
=> [New Connector] ServiceNow: Ping feature

connectors/sources/mysql.py, docs/DOCKER.md
Add new connectors to `DOCKER.md` sample config
=> [Docs] Update DOCKER.md with new connectors

docs/CONNECTOR_PROTOCOL.md
Update the connector protocol to reflect changes to the configuration
=> Add rich configurable fields to connector protocol

docs/CONTRIBUTING.md
=> Tips on logging levels

connectors/sources/tests/fixtures/sharepoint/fixture.py, connectors/sources/tests/fixtures/sharepoint/requirements.txt
This adds HTTP request throttling capabilities we need to test Sharepoint Online
Related links:
* https://github.com/elastic/enterprise-search-team/issues/4332
=> [Sharepoint] Support HTTP requests throttling

connectors/sources/generic_database.py
We have a few warnings on pyright
=> fix pyright on latest 3.10

connectors/es/sink.py, connectors/kibana.py, connectors/sync_job_runner.py, tests/test_kibana.py, tests/test_sink.py, tests/test_sync_job_runner.py
- `byoei.Fetcher` -> `connectors.es.sink.Extractor`
- `byoei.Bulker` -> `connectors.es.sink.Sink`
- `byoei.ElasticServer` -> `connectors.es.sink.SyncOrchestrator`
=> renamed byoei.* to connectors.es.*

README.md, docs/CONTRIBUTING.md, docs/DEVELOPING.md, docs/REFERENCE.md, docs/reference/confluence.md, docs/reference/jira.md, docs/reference/sharepoint.md
For GA, we want to add some more explicit developer documentation. Before I start on that content, I wanted to clean up some of what we had, so it was clear where "developer documentation" would live.
This PR separates our docs into 3 categories:
- Connector reference documentation (for example, how to configure the JIRA connector)
- Contribution guidelines (what we expect from anyone submitting a PR, regardless of if they're adding a new connector, a new feature, or fixing a small typo)
- Developer guide (how to make sense of the code in this repo. Class architecture, how to run tests, common patterns, etc)
=> Reorganized docs for contributing, development, and reference

connectors/protocol/connectors.py, connectors/sources/mysql.py, tests/protocol/test_connectors.py
This PR adds a new accessor for the permissions schedule.
=> [DLS] Add permissions scheduling accessor

README.md, docs/CONTRIBUTING.md, docs/DEVELOPING.md, docs/UPGRADING.md
- expands the DEVELOPING.md to include common considerations that should be made when developing connectors
- expands the CONTRIBUTING.md to include a mental checklist, and guidance on different types of contributions to the project
- adds an UPGRADING.md to provide guidance on how to upgrade successfully
* https://github.com/elastic/connectors-python/pull/928
=> developer docs for GA

connectors/sources/confluence.py, tests/sources/test_confluence.py
This PR introduces advanced sync rules for Confluence by using CQL (Confluence Query Language) queries to filter out confluence data. The connector utilises `atlassian.py` file for validating the query.
=> Add Confluence advanced sync rules

README.md, docs/CONTRIBUTING.md, docs/DEVELOPING.md, docs/UPGRADING.md
manual backport of https://github.com/elastic/connectors-python/pull/935
=> [8.8] backport developer docs 8.8

.ruff.toml, Makefile, connectors/es/client.py, connectors/es/index.py, connectors/protocol/connectors.py, connectors/sources/generic_database.py, connectors/sources/google_cloud_storage.py, connectors/sources/jira.py, connectors/sources/mysql.py, requirements/tests.txt, setup.cfg, tests/sources/test_mysql.py
Ruff is way faster than flake8 and also catches more issues.
This patch move the project to use ruff -- it's a drop in replacement.
=> switch to ruff

connectors/services/base.py, connectors/utils.py, docs/CONFIG.md, docs/CONNECTOR_PROTOCOL.md, docs/CONTRIBUTING.md, docs/DEVELOPING.md
This PR fixes spelling mistakes in the repository. These errors were caught while playing around with a python package `codespell`
=> Rectify spelling mistakes

connectors/protocol/connectors.py, docs/CONNECTOR_PROTOCOL.md, tests/protocol/test_connectors.py
This PR adds the `incremental_sync` feature flag to class `Connector`
=> Add incremental_sync feature flag

connectors/es/sink.py, connectors/logger.py, tests/test_logger.py
Adding some timers to track where we spend time
=> @tracer.start_as_current_span

requirements/aarch64.txt, requirements/arm64.txt
Running MongoDB connector is problematic on ARM architecture - both Linux ARM and Macos M1. If connector is used with `mongodb+srv` protocol (modern load-balanced connection to a replica set of MongoDB), an error appears:
```
[FMWK][15:58:11][CRITICAL] The "dnspython" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv extra:
/Users/seanstory/Desktop/Dev/connectors-python/bin/python -m pip install "pymongo[srv]"
File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/services/job_scheduling.py", line 152, in _run
await self._sync(connector)
File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/services/job_scheduling.py", line 99, in _sync
validator=source_klass(connector.configuration) …
```
=> Install pymongo[srv] on M1 and ARM linux

connectors/es/sink.py, connectors/logger.py, tests/test_logger.py
Follow up from https://github.com/elastic/connectors-python/pull/971 
I implemented the unified API and did not notice the PR was already merged 
@vidok this is the change to have a single API that works on async generators as well (fun to implement)
=> unify the metrics API

docs/DEVELOPING.md
=> [ServiceNow] Documentation for ServiceNow connector

README.md, docs/reference/confluence.md, docs/reference/jira.md, docs/sync-rules/CONFLUENCE.md, docs/sync-rules/JIRA.md
This PR includes examples for JIra and Confluence Advanced Sync Rules using JQL and CQL queries respectively.
=> Document sync rules for Jira and Confluence

connectors/kibana.py, connectors/protocol/connectors.py, docs/CONNECTOR_PROTOCOL.md, tests/fixtures/connector.json, tests/protocol/test_connectors.py, tests/sources/fixtures/mongodb/connector.json, tests/sources/fixtures/mysql/connector.json
This PR:
1. replaces property `scheduling` with `full_sync_scheduling` in class `Connector`
2. adds property `incremental_sync_scheduling` to class `Connector`
3. updates connector protocol
4. updates `connector.json` in ftest
=> Modify scheduling structure in connector index

connectors/services/job_execution.py, tests/services/test_job_execution.py
This PR makes sure there's only one full/incremental sync to be executed per connector.
=> Support incremental sync in JobExecutionService

.buildkite/nightly.py, .buildkite/nightly_steps.yml
=>  Backport the nightly CI structure 

.buildkite/nightly_steps.yml, .buildkite/run_nigthly.sh
skips a couple of e2e tests on aarch64
=> skipping on aarch64

.buildkite/run_nigthly.sh
Fix the variable lookup and condition
=> Tweak the aarch64 flag

catalog-info.yaml
that pipeline is just for main for now
=> only main for aarch64 for now

connectors/sources/dropbox.py, tests/sources/test_dropbox.py
Added Document Sync Functionality for Dropbox connector.
Note: The current implementation for document sync is slow in terms of performance. So, we're trying to use low level APIs instead of SDK. However, the approach will still remain the same.
=> [Dropbox] Implement Indexing Feature

connectors/sources/servicenow.py, connectors/sources/tests/fixtures/servicenow/fixture.py, connectors/sources/tests/test_servicenow.py
This PR add support for batching to improve performance. Previously connector was taking 60 mins to index 50k documents (10GB of data) with present implementation connector takes around 7 mins for the same amount of data 🚀 🚀
=> [ServiceNow] Add batching in APIs

connectors/sources/sharepoint_online.py, tests/sources/test_sharepoint_online.py
1. Don't run any permissions query if DLS is disabled.
2. Make `_site_access_control` and `_list_item_access_control` consistent with other access control method
3. Move `_dls_enabled` check into `_with_{item}_access_control` method.
=> Don't run permissions query if DLS is disabled

connectors/services/job_cleanup.py, connectors/services/job_execution.py, connectors/services/job_scheduling.py
When `native_service_types` is configured like this
```
native_service_types:
```
It's evaluated to be `None` not `[]`. This PR fixes the bug.
=> Assign empty list if native_service_types is configured to None

connectors/sources/sharepoint_online.py
This PR enables incremental sync for Sharepoint Online connector
=> Enable incremental sync for SPO

docs/DEVELOPING.md
Update documentation to guide developers on how to implement incremental sync
=> Update developer guide for incremental sync

connectors/services/job_cleanup.py, connectors/services/job_execution.py, connectors/services/job_scheduling.py
This PR tries to improve logging by 1) changing log level to `debug` for some logs 2) making logs distinguishable.
=> Improve logging

.github/ISSUE_TEMPLATE/qa_connector_package.md, connectors/sources/generic_database.py, connectors/sources/mssql.py, tests/sources/test_mssql.py
This PR includes:
- Add multiple certificates in `get_pem_format`
- Add condition to avoid unnecessary logger while connector founds tables in database.
=> [MS-SQL] Add Support for multiple SSL Certificates

connectors/sources/sharepoint_online.py, tests/conftest.py, tests/sources/test_sharepoint_online.py
- [[SPO] Update DLS implementation  (#1156)](https://github.com/elastic/connectors-python/pull/1156)
=> [8.9] [SPO] Update DLS implementation  (#1156)

connectors/sources/sharepoint_online.py
Make sure that temporary files are deleted.
=> [SPO] Make sure that temporary files are deleted

connectors/sources/sharepoint_online.py
Based on feedback from https://github.com/elastic/kibana/pull/161546, just changing the copy for this RCF.
=> Change RCF label and tooltip based on feedback

docs/DEVELOPING.md, docs/reference/google_drive.md
Add documentation to configure google drive connector.
=> [Google Drive] Add connector documentation

connectors/utils.py
=> Extend Tika supported file types list

docs/CONFIG.md
Add a description for all local extraction service config
=> Add extraction service to CONFIG.md

connectors/sources/sharepoint_online.py, tests/sources/fixtures/sharepoint_online/connector.json, tests/sources/test_sharepoint_online.py
- [Performance improvements to the ACL sync (#1255)](https://github.com/elastic/connectors-python/pull/1255)
=> [8.9] Performance improvements to the ACL sync (#1255)

connectors/sources/mysql.py, connectors/sources/sharepoint_online.py, tests/sources/test_sharepoint_online.py
Follow-up for https://github.com/elastic/connectors-python/pull/1264#discussion_r1265772314 and https://github.com/elastic/connectors-python/pull/1264#discussion_r1266598896
=> [SPO] Put dynamic group check into correct context

connectors/sources/google_drive.py, tests/sources/fixtures/google_drive/connector.json, tests/sources/test_google_drive.py
Adds DLS to Google Drive connector. 
- Connector configuration change, add DLS toggle, add `admin email` field to specify a Google Workspace admin email to impersonate as a service account (to read workspace users and their group membership)
- Doc: #1274 
- `get_docs` function will also fetch files permissions (call a func) if dls is enabled. The permissions are fetched per-file, meaning we guarantee the same read access as google drive. Since we need to fetch permissions for each file (at least 1 extra API call) it slows down indexing rate a bit. I addressed it with asyncio, see below: `Changes requiring attention`.
- Manual test (Shared drive with 85k docs ingested in 3.5 hrs)
- `get_access_control` function lists all the users in the Google Workspace taking into consideration their …
=> [Google Drive] DLS implementation

docs/reference/google_drive.md
Add documentation about Document-level security for Google Drive connector.
This PR complements the code changes from: #1257
=> [Google Drive] Add docs for Google Drive DLS

config.yml, connectors/sources/onedrive.py, tests/sources/test_onedrive.py
Added a Ping Functionality for OneDrive connector.
=> [OneDrive] Add ping functionality

tests/sources/fixtures/github/fixture.py
This PR contains changes of E2E as per GraphQL Implementation
=> [GitHub] Update E2E as per GraphQL Implementation

connectors/sources/dropbox.py, tests/sources/test_dropbox.py
This PR is having the implementation of Advanced Sync rules for Dropbox connector.
=> [Dropbox] Advanced Sync Rules

docs/reference/dropbox.md, docs/sync-rules/DROPBOX.md
This PR contains the documentation of Dropbox connector advanced sync rules.
=> [Dropbox] Documentation for Advanced sync rules

connectors/sources/sharepoint_online.py
Follow up to #1352  - I forgot to add the logic to incremental sync as well
=> [SPO] Include fix to drive item permissions to incremental sync as well

connectors/sources/postgresql.py, tests/sources/test_postgresql.py
This PR adds PostgreSQLClient abstraction, which will handle the connection to PostgreSQL server.
=> Add PostgreSQLClient abstraction

connectors/sources/salesforce.py, tests/sources/test_salesforce.py
General improvements to the API request/response logic
- Add exception handling
- Add token refresh (not really a refresh)
- Add pagination handling
=> [Salesforce] Improve request handling

connectors/sources/mysql.py, connectors/sources/sharepoint_online.py
=> [SPO] Fix small typo

connectors/sources/onedrive.py, tests/sources/test_onedrive.py
The PR adds indexing implementation in OneDrive Connector.
=> [OneDrive] Add Indexing Implementation 

.buildkite/nightly_steps.yml, .buildkite/pipeline.yml, tests/sources/fixtures/onedrive/.env, tests/sources/fixtures/onedrive/Dockerfile, tests/sources/fixtures/onedrive/config.yml, tests/sources/fixtures/onedrive/connector.json, tests/sources/fixtures/onedrive/docker-compose.yml, tests/sources/fixtures/onedrive/fixture.py, tests/sources/fixtures/onedrive/requirements.txt, tests/sources/test_onedrive.py
This PR adds feature for end to end tests in OneDrive connector.
=> [OneDrive] Add e2e feature

connectors/sources/salesforce.py, tests/sources/test_salesforce.py
Ingest the final sobjects and all related fields:
- Campaign
- Case
- CaseComments
- EmailMessages
- CaseFeeds
- FeedComments
=> Ingest Campaign, Case and related sobjects

README.md, docs/document-level-security/CONFLUENCE.md, docs/document-level-security/JIRA.md
This PR contains the DLS documentations for Jira and Confluence connectors.
=> Add DLS docs for Jira and Confluence

tests/sources/test_mysql.py
This PR includes:
1.Test case warning error for mysql
=> Fix warning error for mysql

connectors/config.py, connectors/sources/salesforce.py, tests/sources/test_salesforce.py
Adds Salesforce as a new connector.
This connector is in beta for 8.10.
- Ingests the SObjects Accounts, Contacts, Leads, Campaigns, Opportunities, Cases
- Ingest ContentDocuments and extracts binary data from their associated files
=> [Salesforce] Add Salesforce connector

connectors/sources/salesforce.py
The configuration is in the wrong order and the sensitive fields are marked incorrectly.
=> [Salesforce] Fix configuration

tests/protocol/test_connectors.py, tests/test_utils.py
Our test coverage is around 92%, and caused the CI of some PRs to fail. E.g. 
1. https://github.com/elastic/connectors-python/pull/1428
2. https://github.com/elastic/connectors-python/pull/1505
which does not change much logic.
This PR tries to add tests for untested functions, missing lines line below are not covered:
https://github.com/elastic/connectors-python/blob/0d57e8b709aaea106b7e4153537c36943a334227/connectors/services/job_scheduling.py#L193-L196
=> Add more tests to improve test coverage

docs/DOCKER.md
Also verified that https://github.com/elastic/enterprise-search-team/issues/5025 is fixed. Couldn't reproduce it so marking it as fixed.
Update Docker instructions.
=> Update DOCKER docs for 8.10 release

connectors/sources/mysql.py, tests/fake_sources.py, tests/test_cli.py
I think the name of the `LargeFakeSource` could be offensive and therefore should be changed.
=> [FakeSource] Adjust name

connectors/sources/mysql.py, setup.py
This PR adapts the `author_email` in `setup.py` to use the team email.
=> [Setup] Use team email as author email

README.md
- [[DOCS] Update README.md (#1537)](https://github.com/elastic/connectors-python/pull/1537)
=> [8.9] [DOCS] Update README.md (#1537)

connectors/sources/mysql.py, docs/CONNECTOR_PROTOCOL.md
This PR adds a separate sequence diagram for access control syncs.
=> [Docs] Add access control sequence diagram

connectors/sources/zoom.py, docs/reference/zoom.md, tests/sources/fixtures/zoom/connector.json, tests/sources/test_zoom.py
=> [Zoom] Add recording age as config param

connectors/cli/connector.py, connectors/connectors_cli.py, requirements/framework.txt
- CLI base tool
- Add a cli folder
=> Introduce connector list command

connectors/sources/onedrive.py, docs/document-level-security/ONEDRIVE.md, tests/sources/fixtures/onedrive/connector.json, tests/sources/test_onedrive.py
=> [OneDrive] Document level security 

connectors/cli/job.py, connectors/connectors_cli.py
=> [ConnectorsCLI] Introduce jobs

connectors/cli/connector.py, connectors/connectors_cli.py, connectors/es/client.py, setup.py
- Rename old cli
- Introduce connector create
=> Introduce connector create command

.buildkite/pipeline.yml, connectors/sources/microsoft_teams.py, tests/sources/fixtures/microsoft_teams/.env, tests/sources/fixtures/microsoft_teams/config.yml, tests/sources/fixtures/microsoft_teams/connector.json, tests/sources/fixtures/microsoft_teams/docker-compose.yml, tests/sources/fixtures/microsoft_teams/fixture.py, tests/sources/test_microsoft_teams.py
This PR includes:
- e2e implementation
- update function name in test case `time_to_sleep_between_retries`(changed in utils)
- Add test case to increase coverage
=> [Microsoft Teams] Add ftests

connectors/sources/zoom.py
Add recording age validation for checking negative input value
=> [Zoom] Recording age validation

connectors/sources/network_drive.py, requirements/framework.txt, tests/sources/fixtures/network_drive/connector.json, tests/sources/test_network_drive.py
=> Add DLS in Network Drive

connectors/sources/sharepoint_online.py, tests/sources/test_sharepoint_online.py
- [[SPO] Handle aiohttp.ClientPayloadError (#1660)](https://github.com/elastic/connectors-python/pull/1660)
=> [8.10] [SPO] Handle aiohttp.ClientPayloadError (#1660)

connectors/sources/google_cloud_storage.py, tests/sources/test_google_cloud_storage.py
Fix google cloud storage issue to fetch files inside the folders
=> [GCS] Fix issue related url-encoded

.buildkite/pull-requests.json
Update `pull-requests.json` to reflect pipeline name change.
=> [CI] Update pull-requests.json

docs/DOCKER.md, tests/sources/test_sharepoint_online.py
Add link to elastic docker registry with available connector images.
Bonus fix: removed hardcoded datetime in spo tests which was a ticking time bomb that started failing our tests just now
=> Update DOCKER.md with link to elastic docker registry

docs/DOCKER.md, tests/sources/test_sharepoint_online.py
- [Update DOCKER.md with link to elastic docker registry (#1866)](https://github.com/elastic/connectors/pull/1866)
=> [8.10] Update DOCKER.md with link to elastic docker registry (#1866)

docs/DOCKER.md, tests/sources/test_sharepoint_online.py
This will backport the following commits from `main` to `8.11`:
- [Update DOCKER.md with link to elastic docker registry (#1866)](https://github.com/elastic/connectors/pull/1866)
=> [8.11] Update DOCKER.md with link to elastic docker registry (#1866)

connectors/sources/network_drive.py
If a non-standard (_ie_ not 445) port is configured for the SMB server, we must specify the port explicitly when calling various smbclient methods. Otherwise, some of the smbclient `os` methods will wrongly assume port 445, even though we have earlier specified the port when calling `smbclient.register_session`.
It's possible that with this changeset, we are working around a bug in smbclient, and one that isn't frequently encountered, since it seems likely that people would usually stick to the standard port.
Either way, this change should be safe, and should ensure that the network drive connector will work in the rare cases where port 445 is not being used.
=> Specify port when calling all smbclient methods in network drive connector

connectors/sources/oracle.py, tests/sources/fixtures/oracle/connector.json
Updated Labels of `oracle_home` and `wallet_configuration_path`.
=> [Oracle] Update Labels

docs/document-level-security/DROPBOX.md
Add Documentation for DLS in Dropbox
=> Add Documentation for DLS in Dropbox

config.yml, connectors/config.py
Reverts elastic/connectors#1894
We are going to move telemetry data collection to Kibana, so this change is no longger needed.
=> Revert "Add config for telemetry"

.github/PULL_REQUEST_TEMPLATE.md
Hopefully this will help us remember to make Kibana PRs when we or partners change Rich Configurable Fields
=> add RCF+kibana PR checklist item

connectors/connectors_cli.py
This PR fixes a type and makes `--update-config` help more clear.
=> [CLI] Fix typo in connector create command

connectors/sources/github.py
This will backport the following commits from `main` to `8.11`:
- [Add some logging to github connector for debugging (#1953)](https://github.com/elastic/connectors/pull/1953)
=> [8.11] Add some logging to github connector for debugging (#1953)

connectors/cli/auth.py, connectors/cli/connector.py, connectors/cli/index.py, connectors/cli/job.py, connectors/es/client.py, connectors/es/index.py, connectors/preflight_check.py, connectors/protocol/connectors.py, connectors/services/job_cleanup.py, tests/es/test_client.py, tests/protocol/test_connectors.py, tests/services/test_job_cleanup.py, tests/sources/fixtures/fixture.py, tests/test_connectors_cli.py, tests/test_preflight_check.py
Current structure of our classes that call Elasticsearch is neat, but there are some minor problems here and there as I see them. This PR attempts to refactor out these problems.
It contains several connected changes, might make it a bit harder to review, but they all follow the same logic.
Changes are:
A lot of classes inherit from ESClient, for example ConnectorIndex class. ConnectorIndex class is used to do certain operations on connectors - get all connectors, read one connector, get supported connectors, etc.
ESClient, however, had methods that are touching things that logically should not be available for _specialized_ classes that inherit from it, for example this method:
```
async def delete_indices(self, indices):
```
It seems illogical that `ConnectorIndex` class that's a rich …
=> Refactor ES Client methods

connectors/sources/servicenow.py, tests/sources/fixtures/servicenow/connector.json, tests/sources/test_servicenow.py
Add support of Document Level Security in ServiceNow.
=> [ServiceNow] Add DLS for ServiceNow

docs/document-level-security/SERVICENOW.md
Add Documentation of ServiceNow DLS
=> [ServiceNow] DLS documentation

scripts/testing/README.md, scripts/testing/cli.py, scripts/testing/docker-compose.yml, scripts/testing/pull-connectors.sh, scripts/testing/scenarios/clients/spo_automated_testing_site.json, scripts/testing/scenarios/clients/spo_full_and_incremental_syncs.yml, scripts/testing/scenarios/clients/spo_sean_site.json, scripts/testing/startup_scipt.sh, setup.py
This PR will add a new way of running functional tests. 
To give it a try follow the [installation guide](https://github.com/elastic/connectors/blob/dmitrii/5881-automated-testing/scripts/testing/README.md#L41) and run a sample test.
=> Introduce automated testing CLI

connectors/sources/mongo.py, tests/sources/test_mongo.py
Add validation to check consistency of SSL and raise `ConfigurableFieldValueError` if conflicting values found
=> [MongoDB] Validate & Ensure consistency of enabling SSL 

connectors/es/sink.py, connectors/sources/box.py, connectors/sources/confluence.py, connectors/sources/dropbox.py, connectors/sources/google_cloud_storage.py, connectors/sources/google_drive.py, connectors/sources/jira.py, connectors/sources/mysql.py, connectors/sources/network_drive.py, connectors/sources/onedrive.py, connectors/sources/servicenow.py, connectors/sources/sharepoint_server.py, connectors/sources/zoom.py, connectors/sync_job_runner.py, tests/test_sync_job_runner.py
This PR will bring back the timestamp-based optimization we dropped in https://github.com/elastic/connectors/pull/1907. 
Timestamp-based optimization is available only during incremental sync job execution so a connector should enable it by defining "incremental_sync_enabled = True". 
If a connector has its own `get_docs_incrementally` method then that method will be used when an incremental sync is triggered. Timestamp-based optimization will be skipped. 
The following list of connectors will support the optimization: 
- Google Cloud storage
- Google Drive
- Box
- Confluence
- Dropbox
- Jira
- Network Drive
- One Drive
- ServiceNow
- Sharepoint Server
- Zoom
* https://github.com/elastic/connectors/pull/1907
We added incremental sync jobs support for the following connectors: Google Cloud …
=> Support timestamp-based optimization

.buildkite/publish_docker.sh, catalog-info.yaml
backports https://github.com/elastic/connectors/pull/2097
=> [8.12] Update 'connectors-nightly-dockers' to stop trying to install Docker

.buildkite/publish_docker.sh, catalog-info.yaml
backports https://github.com/elastic/connectors/pull/2097
=>  [8.10] Update 'connectors-nightly-dockers' to stop trying to install Docker

.buildkite/publish_docker.sh, catalog-info.yaml
backports https://github.com/elastic/connectors/pull/2097
=> [8.9] Update 'connectors-nightly-dockers' to stop trying to install Docker

.buildkite/publish_docker.sh, catalog-info.yaml
backports https://github.com/elastic/connectors/pull/2097
=> [8.11] Update 'connectors-nightly-dockers' to stop trying to install Docker

connectors/sources/github.py, tests/sources/fixtures/github/fixture.py, tests/sources/test_github.py
=> [8.12] [GitHub] Fix scopes related issue (#1997)

connectors/config.py, connectors/sources/notion.py, requirements/framework.txt, tests/sources/test_notion.py
This PR adds Indexing functionality to notion connector.
=> Add Notion configurations and indexing Implementation

connectors/sources/salesforce.py, tests/sources/fixtures/salesforce/fixture.py
This PR includes changes in the Salesforce fixture to ingest large amount of data depending on `DATA_SIZE` argument.
Perf8 Report: https://drive.google.com/file/d/1L0TUpjiDyvYc3X1TFKzXC0j6NL1rv8ql/view?usp=drive_link
=> Add volumes to Salesforce Fixture

.buildkite/publish/build-docker.sh, .buildkite/publish/build-multiarch-docker.sh, .buildkite/publish/push-docker.sh, .buildkite/publish/test-docker.sh, .buildkite/release-pipeline.yml
Fixes issues found during testing of https://github.com/elastic/connectors/pull/2152
* Fixes the pipeline to use the correct agents and syntax
* Ensures we pull the images before creating the multi-arch image
* Sets the proper tags for the images
=> [CI] Fix Issues in Docker Publishing Pipeline

connectors/sources/notion.py, tests/sources/test_notion.py
Following change has been added:
- Since `fetch_by_query` returns a dictionary, `extend` is replaced with `append`
=> [Notion]Fix error on fetching search queries

connectors/sources/outlook.py, tests/sources/test_outlook.py
Adding more logs to Outlook connectors.
=> Add more logs in Outlook connector

connectors/sources/network_drive.py
This PR aims to wrap synchronous calls inside run_in_executor to prevent connector from hanging the framework.
=> [Network Drive] Fix connector hanging the framework

connectors/sources/outlook.py, tests/sources/test_outlook.py
=> Reduce lag in Outlook connector

connectors/cli/connector.py, connectors/connectors_cli.py, tests/test_connectors_cli.py
This PR adds a "Connector name" argument to the CLI to align with the Kibana changes.
=> [CLI] Add connector name support

connectors/sources/postgresql.py
After some analysis we found that  even using the cursor, it fetches whole table data at once and because of that memory will increase. To fix this issue we added custom pagination on query using limit-offset.
Now for given test data (1M rows with a single JSON field) connectors requires `152.5` MB.
=> [PostgreSQL] Add custom pagination to reduce memory consumption

connectors/es/client.py, connectors/preflight_check.py, connectors/sources/mongo.py, tests/es/test_client.py
Noticed some misleading or typoed logging
=> change some logging

connectors/sources/notion.py, docs/sync-rules/NOTION.md, tests/sources/test_notion.py
This PR adds Advanced Sync Rules for Notion connector.
Support added for advanced sync rules in Notion Connector.
=> Add Advanced Sync Rules for Notion connector

connectors/es/sink.py
- "does not exist" instead of "does not exists"
- "analyzers" instead of "analizers"
=> [Sink] Fix typos

connectors/sources/azure_blob_storage.py
=> [ABS] Fix typos

connectors/sources/box.py, tests/sources/test_box.py
Just improving some small things for the box connector:
- Add some more debug log lines to know what's happening
- Improve test names
- Adhere to python best practices, when it comes to variable names (no uppercase variables inside a method for example)
~- [ ] this PR links to all relevant github issues that it fixes or partially addresses~
~- [ ] if there is no GH issue, please create it. Each PR should have a link to an issue~
(trying to do small improvements everyday, so no explicit issue)
=> [Box] Improve logging, test naming and variable naming

connectors/sources/jira.py
This PR adds extra logs in Jira to track the connector execution on each stage.
=> [Jira] Add more logs

connectors/sources/github.py
A follow-up PR on #2328, to apply this function to more places.
=> Apply function nested_get_from_dict to more places

requirements/framework.txt
Update the elasticsearch package to the latest.
=> Bump elasticsearch package from 8.12.0 to 8.13.0

connectors/sources/confluence.py, tests/sources/test_confluence.py
This PR adding approach for confluence datacenter pagination for sync rules
=> Fix pagination for confluence datacenter sync rules

connectors/sources/jira.py, tests/sources/test_jira.py
Some small improvements:
- Add more logging
- Add more tests around `_get_session`
- Catch, if the data source type in `_get_session` is invalid
- Add constants for repeated strings
~- [ ] this PR links to all relevant github issues that it fixes or partially addresses~
~- [ ] if there is no GH issue, please create it. Each PR should have a link to an issue~
=> [Jira] Add more logging, tests and constants

connectors/sources/graphql.py, tests/sources/fixtures/graphql/connector.json, tests/sources/test_graphql.py
Added new RCF for identification of unique field for IDs.
version: 8.14.0
=> [GraphQL] Update GraphQL Object List RCF for identifying unique fields

tests/sources/fixtures/github/connector.json
Duplicate of PR https://github.com/elastic/connectors/pull/2374, because the change was accidentally reverted by PR https://github.com/elastic/connectors/pull/2372
=> Update connector.json for GitHub ftest

connectors/sources/jira.py, tests/sources/test_atlassian.py, tests/sources/test_jira.py
Backports the following commits to 8.13:
- Fix NotFound when the path is present in host URL #2377
=> [8.13] [Jira] Fix NotFound when the path is present in host URL #2377

connectors/es/sink.py, connectors/sync_job_runner.py, connectors/utils.py, tests/test_sink.py, tests/test_sync_job_runner.py, tests/test_utils.py
manual Backport of https://github.com/elastic/connectors/pull/2364
=> [8.14] Attempt to handle errors from Sink (#2364)

tests/ftest.sh
just a version bump. But blocked by ES producing the first artifact.
=> Bump es version for ftests to 8.15

connectors/sources/github.py, tests/sources/test_github.py
This PR updates the GitHub connector to be able to sync contents when `GitHub App` is selected as the Authentication method.
Enhanced the GitHub connector to support an additional authentication method GitHub App.
=> Update GitHub connector to sync content for GitHub App authentication

connectors/sources/confluence.py
As mentioned in the issue, the aiohttp session was not getting closed, therefore we've now used close_session method that unsets the session variable.
=> [Confluence] Use close_session to unset session variable 

connectors/sources/sharepoint_server.py, tests/ftest.sh, tests/sources/test_sharepoint_server.py
This PR contains implementation of SharePoint Server DLS
=> Add SharePoint Server DLS

connectors/sources/network_drive.py, tests/sources/test_network_drive.py
This PR includes fix for getting SMBResponseException: Received unexpected status from the server: Unknown error. ([3221225584](tel:3221225584)) UNKNOWN_ENUM: 0xc0000070.
=> [Network Drive] Fix unknown enum error: 0xc0000070

connectors/sources/outlook.py, tests/sources/test_outlook.py
This PR contains implementation of Outlook DLS
=> Add DLS in outlook

connectors/sources/network_drive.py, tests/sources/test_network_drive.py
Backports the following changes to 8.13:
- Fix unknown enum error: 0xc0000070 (#2458 )
=> [8.13] [Network Drive] Fix unknown enum error: 0xc0000070 (#2458)

connectors/sources/sharepoint_server.py, tests/sources/fixtures/sharepoint_server/fixture.py, tests/sources/test_sharepoint_server.py
This PR includes adding author and editor name instead of author/editor id for list items
=> Add author and editor name instead of author/editor id

.buildkite/pipeline.yml
- [Run all functional tests if any requirements change (#2516)](https://github.com/elastic/connectors/pull/2516)
=> [8.13] Run all functional tests if any requirements change (#2516)

connectors/sources/postgresql.py
Updated PostgreSQL `table_data` query to support column name with uppercase letters. Also updated other queries to support table name and schema name with upper case letters.
Updated the queries in PostgreSQL connector to support primary key column name with uppercase letters. Earlier UndefinedColumnError occurred while running the connector.
=> [PostgreSQL] Updated queries to support primary key column name with uppercase letters

connectors/sources/github.py, tests/sources/test_github.py
Backports the following PR to 8.13:
- [GitHub] Raising 403 exception #2507
=> [8.13] [GitHub] Raising 403 exception (#2507)

connectors/sources/notion.py
As Notion was a new connector, it was not included in https://github.com/elastic/connectors/pull/2142, therefore this PR enables incremental sync in Notion connector. 
Enable incremental sync jobs for Notion Connector
=> Enabled incremental syncs for Notion Connector

.github/ISSUE_TEMPLATE/config.yml
old workplace search category is dead
=> Use newer discuss category

tests/sources/test_sharepoint_server.py
=> [SharePoint Server]Fix flaky test

connectors/sources/confluence.py, tests/sources/fixtures/confluence/connector.json, tests/sources/fixtures/confluence/fixture.py, tests/sources/test_confluence.py
Added label code for each confluence pages.
=> [Confluence] Add labels in confluence

tests/sources/test_confluence.py
Similar to https://github.com/elastic/connectors/pull/2540
Flaky test failures had following error: async generator raised StopIteration. To fix it, this PR makes sure that aexit is defined for the mock to simulate the full async context manager protocol.
=> [Confluence] Fix flaky test_get_with_429_status

connectors/sources/azure_blob_storage.py, requirements/framework.txt, tests/sources/test_azure_blob_storage.py
Improve memory consumption in ABS connector. Added perf8 reports for the comparision:
Before: https://drive.google.com/file/d/12fcQWT8NKUr9CMgdEZsqVscXLEiFNJw-/view?usp=drive_link
After: https://drive.google.com/file/d/1IOKhm2s8hk0abjGarFy75d64AmKeANYE/view?usp=drive_link
The previous version of the connector instantiated a BlobClient for each blob it downloaded. Where, the new approach utilizes a single ContainerClient to download data for all blobs within that container. 
For instance, if a container contains 100 blobs, the old code was creating 100 separate BlobClient instances to download those blobs, but now the new code leverages just one ContainerClient for all blobs in the container. This optimization was inspired by a suggestion from[ this GitHub …
=> [Azure Blob Storage] Optimize memory consumption

connectors/sources/confluence.py, tests/sources/test_confluence.py
Following changes have been made in this PR:
- Ingest full body of documents while using advanced sync rules.
=> [Confluence] Ingest full body of documents in sync rules

connectors/sources/confluence.py
Changed LIMIT value to 50 as the original LIMIT value of 100 was causing the loop to break prematurely in the `paginated_api_call_for_datacenter_syncrule` method as the results limit is updated to 50.
Fixing data loss in Confluence connector when advanced sync rule is enabled.
=> [Confluence] Fix data loss for Data Center during Advance-Sync

connectors/sources/confluence.py
Backport PR https://github.com/elastic/connectors/pull/2651
=> [8.14] [Confluence] Fix data loss for Data Center during Advance-Sync

connectors/sources/atlassian.py, connectors/sources/confluence.py, tests/sources/fixtures/confluence/fixture.py, tests/sources/test_confluence.py
This PR fixes the issue in the Confluence connector where the body content includes HTML tags.
Fixes Access Control Sync, `getting TypeError: 'async for' requires an object with __aiter__ method, got coroutine in connectors/sources/atlassian.py", line 122, in fetch_all_users async for users in self.client.api_call(url=url_)`
=> [Confluence] Fix HTML Tags from Body Content

connectors/service_cli.py, tests/test_service_cli.py
I'm out of patience for this spec. It times out frequently, we can't get it to log easily to debug why, and none of the things we've tried have been successful. I think it's time to just trash it.
=> replace flakey spec

connectors/source.py, tests/sources/fixtures/mssql/fixture.py
We have checked all datatypes mentioned in the issue and its working as expected. For time data type we have updated the `_serialize` method.
time data type is now supported in MSSQL connector.
=> [MSSQL] Fix serialization to parse time object

connectors/sources/onedrive.py, tests/sources/test_onedrive.py
This PR adds a new field `mime-type` to be indexed in onedrive connector.
Following PR includes support for a new field `mime-type` in OneDrive connector.
=> [OneDrive] Add support for field mime-type

connectors/sources/github.py, tests/sources/fixtures/github/fixture.py, tests/sources/test_github.py
This will backport the following commits from main to 8.15:
- https://github.com/elastic/connectors/pull/2711
=> [8.15][Github] Fix Rate limit error #2711

Makefile, pytest.ini
Reverts elastic/connectors#2763
=> Revert "Replace python setup.py develop with pip install --editable ."

.buildkite/publish/dra/publish-daily-release-artifact.sh
Stop-gap to fix main build until https://github.com/elastic/crawler/pull/103 is ready
=> Comment out release-manager

Makefile
Try to fix the build after some non-conflict merge effects. :)
=> Use .venv/bin for sdist and pip-licenses

tests/agent/test_cli.py
Minor follow up to the PR adding agent component:
1. Remove empty README.md (can return later with some info)
2. Update the test in `test_cli.py` to have a better name + a comment why test does not assert
=> Delete README + add comment to test_cli

connectors/sources/__init__.py
Potentially removal of this file broke our DRA:
```
#12 81.08 [FMWK][18:22:09][INFO] Running connector service version 8.16.0
--
  | #12 81.08 [FMWK][18:22:09][INFO] Loading config from /usr/share/enterprise-search/python-connectors.yml
  | #12 81.09 Registered connectors:
  | #12 81.09 Traceback (most recent call last):
  | #12 81.09   File "/usr/share/enterprise-search/bin/elastic-ingest", line 8, in <module>
  | #12 81.09     sys.exit(main())
  | #12 81.09   File "/usr/share/enterprise-search/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
  | #12 81.09     return self.main(*args, **kwargs)
  | #12 81.09   File "/usr/share/enterprise-search/lib/python3.10/site-packages/click/core.py", line 1078, in main
  | #12 81.09     rv = self.invoke(ctx)
  | #12 81.09   File …
```
=> Return back connectors/sources/__init__.py

Dockerfile.agent, Makefile, resources/agent/python-elastic-agent-client, resources/agent/python-elastic-agent-client.spec.yml
This change provides a way to run docker image of agent with connectors component installed.
It's used purely for dev/testing purposes, should not be used for anything else.
When we finish the work with Agent, this docker image might change significantly or will be deleted.
=> Add everything needed to have a dockerfile for agent testing

docs/CONFIG.md
Fix broken link to example config file.
=> Fix broken link in CONFIG.md

connectors/sources/oracle.py
- [[Oracle] Add logs (#2528)](https://github.com/elastic/connectors/pull/2528)
=> [8.x] [Oracle] Add logs (#2528)

connectors/cli/README.md
* fix a broken link to the CLI docs
=> Fix cli docs link

.backportrc.json, catalog-info.yaml
Part of the 8.16 release (see https://github.com/elastic/search-team/issues/8045)
=> Add 8.16 build jobs

.buildkite/pipeline.yml
part of https://github.com/elastic/search-team/issues/8045
We need to make the new maintenance branch produce packaging artifacts
=> Update pipeline.yml to do packaging on 8.16

config.yml.example
=> Update example config yml with connectors api feature flag

NOTICE.txt
just noticed it was out of date.
=> updating the notice file

NOTICE.txt, pytest.ini, requirements/framework.txt
Part of the 8.16.0 release tasks. See https://github.com/elastic/search-team/issues/8045
=> update elasticsearch python client to 8.16

catalog-info.yaml
added now that we have an 8.17 branch
=> Add nightly 8.17 CI

requirements/framework.txt
Bumping pyOpenSSL as a part of maintenance.
=> Update pyOpenSSL to 24.3.0

catalog-info.yaml, docs/RELEASING.md
Now that 8.17.0 has been released, we no longer need to maintain 8.15.x
=> Remove 8.15 maintenance

.buildkite/run_notice_check.sh, .buildkite/shared.sh, NOTICE.txt
I see CI failures like https://buildkite.com/elastic/connectors/builds/15616:
```
.buildkite/shared.sh: line 31: [: missing `]'
.buildkite/shared.sh: line 39: [: missing `]'
```
The PR fixes 2 things:
1. Syntax problems (spaces when closing square braces)
2. Env variable in `if` did not have `$` in front of variable name 🤦
=> Fix CI considering every change a fork

.buildkite/pipeline.yml
Enables this branch to build DRA (backporting a piece of https://github.com/elastic/connectors/pull/3165)
=> Enable 9.0 DRA builds

.backportrc.json, .buildkite/pipeline.yml, catalog-info.yaml
Part of 8.18 Release Activities for DRA / Backport
=> 8.18 Release Activities for DRA / Backport

connectors/sources/postgresql.py, tests/sources/test_postgresql.py
This PR improves the PostgreSQL connector's primary key detection by enhancing the SQL query used to retrieve primary key information. The current implementation uses `i.indisprimary` to identify primary keys, but this approach can be unreliable in certain PostgreSQL configurations.
The improved query:
1. Adds explicit joins to `pg_class` and `pg_constraint` tables for more accurate filtering
2. Uses `c.contype = 'p'` to specifically target primary key constraints rather than any unique index
3. Orders results by column position in composite primary keys using `array_position(i.indkey, a.attnum)`
4. Maintains backward compatibility with existing code by keeping the same return format
These changes make primary key detection more reliable, especially for tables with composite primary keys …
=> Improve PostgreSQL primary key detection with enhanced SQL query

Makefile
For right now, the build is breaking after setuptools upgraded to version 80. Pinned for at least right now to 79.0.1.
=> Pin Setuptools to 79.0.1

NOTICE.txt, catalog-info.yaml
See the email: `[PSA] Slack Workspace Integration for Buildkite`
after this merges, I'll check to make sure this is working as expected. I'm mildly worried that it'll send notifications for _every_ success, not just the first. We'll see. 🤞
=> Leverage slack integration

.buildkite/nightly_steps.yml, .buildkite/pipeline.yml, .buildkite/release-pipeline.yml
following up on https://github.com/elastic/connectors/pull/3426
=> try adding message

connectors/sources/salesforce.py
Use Salesforce custom object type
=> Use type for access control list

.buildkite/pipeline.yml, NOTICE.txt, catalog-info.yaml
Update buildkite pipeline and catalog-info files for 9.1 branch
=> [9.1] Update CI files for 9.1 branch

NOTICE.txt, requirements/framework.txt
=> Bump aiohttp to 3.12.14

.backportrc.json
=> Update .backportrc.json - remove 8.17

.buildkite/pipeline.yml
Small PR to make sure connectors source paths are correct in our Buildkite pipeline
=> Update bk pipeline step with correct paths
