elastic/connectors

connectors/protocol/connectors.py
connectors/sources/sharepoint_online.py
tests/protocol/test_connectors.py
tests/sources/fixtures/sharepoint_online/connector.json
tests/sources/test_sharepoint_online.py

Sites are currently looked up by name, out of the paginated results of enumerating all sites. This is efficient when large numbers of sites should be synced relative to the total number of sites. However, if a tenant has many sites, but only a small number are configured for syncing, it may be more efficient to look up just the individually configured sites.
This PR adds an RCF to allow the user to pick which strategy to use, and implements looking up sites based on their path.
Additionally, this PR modifies the `validate_config` logic to check sites not by their `"name"` but by the path they use in their URL. This is more reliable and easier for customers to reason about. 
* original POC: https://github.com/elastic/connectors-python/pull/1639/commits
Adds the ability for the Sharepoint …

[SPO] individual site lookup RCF

---

connectors/protocol/connectors.py
connectors/sources/sharepoint_online.py
tests/protocol/test_connectors.py
tests/sources/fixtures/sharepoint_online/connector.json
tests/sources/test_sharepoint_online.py

- [[SPO] individual site lookup RCF (#1653)](https://github.com/elastic/connectors-python/pull/1653)

[pre-8.10-stable] [SPO] individual site lookup RCF (#1653)

---

connectors/protocol/connectors.py
connectors/sources/sharepoint_online.py
tests/protocol/test_connectors.py
tests/sources/fixtures/sharepoint_online/connector.json
tests/sources/test_sharepoint_online.py

- [[SPO] individual site lookup RCF (#1653)](https://github.com/elastic/connectors-python/pull/1653)

[8.10] [SPO] individual site lookup RCF (#1653)

---

NOTICE.txt

Connector service uses a transitive library [certifi](https://pypi.org/project/certifi/), which is under Mozilla Public License 2.0 (MPL 2.0). MPL 2.0 is in yellow list:
>Incorporation of **unmodified** source or binaries into Elastic products is permitted, provided that the product's NOTICE file links to a URL providing the MPL-covered source code
This PR adds the link to certifi source in NOTICE.txt

Update NOTICE.txt to include link to certifi source

---

connectors/source.py
connectors/sources/azure_blob_storage.py
connectors/sources/confluence.py

This PR moves the logic for downloading files to temp files, and their extraction/conversion to b64 to BaseDataSource.
The new tool is very generic, so it can be easily added to other connectors in future PRs.
If this is approved, I will also generalise/abstract the file size and file extension check.
This PR uses two connectors as examples for how this tool would be used:
1. Confluence
This is a "standard" download and extraction case. The download func uses `response.content.iter_chunked`, which is the same pattern that most connectors use. This download func is now abstracted onto the `BaseDataSource` class as `generic_chunked_download_func`.
1. Azure Blob Storage
ABS has an irregular download method (it uses a library and has its own chunking method). As a result, its download func …

Abstract download file extraction and conversion

---

connectors/source.py
connectors/sources/azure_blob_storage.py
connectors/sources/confluence.py
connectors/sources/dropbox.py
connectors/sources/google_cloud_storage.py
connectors/sources/google_drive.py
connectors/sources/jira.py
connectors/sources/onedrive.py
connectors/sources/s3.py
connectors/sources/salesforce.py
connectors/sources/servicenow.py
tests/sources/fixtures/google_cloud_storage/connector.json
tests/sources/fixtures/google_drive/connector.json
tests/sources/fixtures/onedrive/connector.json
tests/sources/fixtures/salesforce/connector.json
tests/sources/fixtures/servicenow/connector.json
tests/sources/test_google_cloud_storage.py
tests/sources/test_google_drive.py
tests/sources/test_onedrive.py
tests/sources/test_salesforce.py
tests/sources/test_servicenow.py

- Expand extraction service to more connectors:
- Google Cloud Storage
- Google Drive
- Onedrive
- Salesforce
- Servicenow
- https://github.com/elastic/connectors-python/pull/1685
- https://github.com/elastic/connectors-python/pull/1693

Expand extraction service to more connectors #3

---

connectors/es/sink.py
tests/test_sink.py

This PR makes the changes so that
1. when the connector cancels the sync job, it will wait for (hardcoded) 5 seconds for cancelation to be done
2. If the sync job is not canceled successfully after 5 seconds, it will try to forcibly cancel the sync job, by removing the queue object, so the whole flow from the remote source to Elasticsearch is cut off.
3. The connector then continue to mark the sync job as `canceled`

Forcibly cancel a sync job after waiting for 5 seconds

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

`retry-after` header can change if the request is throttled more than once. Therefore, the waiting time can be very long
```
[FMWK][10:41:34][WARNING] [Connector id: M9XHqYoBDc5CccrnbkG-, index name: search-test, Sync job id: 8CBW4YoBQesD0dyuubIq] Rate Limited by Sharepoint: a new attempt will be performed in 540 seconds (retry-after header: 54, retry_count: 2, backoff: 5)
```
This PR will change the waiting time computing logic to `retry-after + retry-count * backoff`

[SPO] Do not use retry-after as multiplier

---

connectors/sources/azure_blob_storage.py
connectors/sources/confluence.py
connectors/sources/dropbox.py
connectors/sources/github.py
connectors/sources/google_cloud_storage.py
connectors/sources/google_drive.py
connectors/sources/jira.py
connectors/sources/onedrive.py
connectors/sources/outlook.py
connectors/sources/s3.py
connectors/sources/salesforce.py
connectors/sources/servicenow.py
connectors/sources/sharepoint_online.py
connectors/sources/sharepoint_server.py
connectors/sources/zoom.py

Add missing UI restrictions for all connectors with `use_text_extraction_service` RCF.

Add ui restrictions for all extraction RCFs

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

- [Replace User Information List usage with role assignments for SPO sites (#1688)](https://github.com/elastic/connectors-python/pull/1688)

[pre-8.10-stable] Replace User Information List usage with role assignments for SPO sites (#1688)

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

- [[SPO] Add logic to handle sitegroups in ACL for drive_items and sites (#1659)](https://github.com/elastic/connectors-python/pull/1659)

[8.10] [SPO] Add logic to handle sitegroups in ACL for drive_items and sites (#1659)

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

- [Replace User Information List usage with role assignments for SPO sites (#1688)](https://github.com/elastic/connectors-python/pull/1688)

[8.10] Replace User Information List usage with role assignments for SPO sites (#1688)

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

Ensures that group logins prefixed with `c:0t.c|tenant|` will get picked up
Fixes a bug where the Sharepoint Online connector did not add ACL entries for Azure Security Groups

Add support for security group prefixes

---

connectors/source.py
connectors/sources/sharepoint_online.py
connectors/utils.py
tests/sources/test_sharepoint_online.py

- [Truncate branches and leafs in incremental sync (#1731)](https://github.com/elastic/connectors-python/pull/1731)

[pre-8.10-stable] Truncate branches and leafs in incremental sync (#1731)

---

connectors/source.py
connectors/sources/sharepoint_online.py
connectors/utils.py
tests/sources/test_sharepoint_online.py

- [Truncate branches and leafs in incremental sync (#1731)](https://github.com/elastic/connectors-python/pull/1731)

[8.10] Truncate branches and leafs in incremental sync (#1731)

---

catalog-info.yaml

Minor change - we still run nightly tests for 8.7 and 8.8 branches, but we don't push anything into them. 
Removing nightlies for them - does not make sense to keep running them.

Stop nightlies for 8.7 and 8.8

---

tests/test_utils.py

Since test_next_run is now deterministic, then `test_next_run` can be deterministic too - therefore instead of freezing time and calling `datetime.utcnow` we create datetime statically and pass it into `next_run` method.

Make test_next_run deterministic

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

This fetches site collection admins with a `GET /_api/web/SiteUsers?$filter=isSiteAdmin eq true`, and appends the results to the ACLS fetched from role assignments that had `isSiteAdmin: true`. This ensures that _all_ the site admins, not just the ones in the site's "Owners" group, get stored and granted access through DLS.
Additionally, this PR ensures that `_o`-suffixed group IDS get expanded into the _owners_ of the group. This happens when a site's "members" includes a group, that group's owners automatically get added to the site's "owners" group.
- needs confirmation from stakeholders that it does or does not need backporting.
Ensures that all Site Collection Administrators are present in Site, Site Page, Site List, Site List Item, and Drive Item access control lists for Document …

fetch site admins separate from role assignments

---

tests/test_utils.py

Several things:
1. Initial timeout is a little too small as sometimes event loop hicks up and takes more than 0.1 second to remove something from the queue (which is weird). I increase timeout to 2 seconds after we've made queue full
2. Last assert is flaky by design - there are no good guarantees about it since we don't run both add_data and remove_data immediately - they're ran on event loop, so if something slows down, then one function can start later than the other (add_data will start with a lag of 0.05 second and will fail the test, for example). I've changed this assert to just check, that the data is added into the queue within refresh_timeout
All in all this test is hard to make non-flaky and might make sense to break it into individual tests.

Make test_mem_queue less flaky

---

tests/sources/fixtures/network_drive/fixture.py

Make Network Drive ftest use shared fixture

---

tests/commons.py
tests/sources/fixtures/mysql/fixture.py

Make MySQL ftest use shared fixture

---

tests/commons.py
tests/sources/fixtures/onedrive/fixture.py

Make OneDrive ftest use shared fixture

---

tests/commons.py
tests/sources/fixtures/oracle/fixture.py

Make Oracle ftest use shared fixture

---

tests/commons.py
tests/sources/fixtures/postgresql/fixture.py

Make PostgreSQL ftest use shared fixture

---

tests/sources/fixtures/s3/fixture.py

Make S3 ftest use shared fixture

---

tests/commons.py
tests/sources/fixtures/salesforce/fixture.py

Make Salesforce ftest use shared fixture

---

tests/commons.py
tests/sources/fixtures/sharepoint_online/fixture.py

Make Sharepoint Online ftest use shared fixture

---

connectors/sources/outlook.py
docs/reference/outlook.md

This PR is adding a new RCF called `Maximum concurrent tasks` to update the fetchers value. The default value for the field is 2000.

[Outlook] Add a new field for `max concurrent tasks`

---

connectors/sources/network_drive.py
docs/document-level-security/NETWORK_DRIVE.md
tests/sources/fixtures/network_drive/connector.json
tests/sources/test_network_drive.py

DLS for Linux Network Drive depends on a local csv file that contains the details of user. DLS for Linux Network Drive would be available via self-managed connector clients.
The format of csv would be as follows:
`username;user-id;groups-sids`

Add support for DLS in Linux Network Drive

---

.buildkite/pipeline.yml
tests/commons.py
tests/sources/fixtures/sharepoint_server/fixture.py

Make Sharepoint Server ftest use shared fixture

---

tests/commons.py
tests/sources/fixtures/zoom/fixture.py

Make Zoom ftest use shared fixture

---

connectors/sources/github.py
tests/sources/test_github.py

This fixes an issue, where a non-401 error leads to an implicit `return None` leading to this error: `TypeError: cannot unpack non-iterable NoneType object`.
The code inside `post` returns an implicit `None`, if a `ClientResponseError` is raised with a `status != 401`:
```
except ClientResponseError as exception:
if exception.status == 401:
raise UnauthorizedException(
"Your Github token is either expired or revoked. Please check again."
) from exception
except Exception:
raise
```
This leads to the error described above, when trying to unpack it in `_remote_validation`:
```
_, headers = await self.github_client.post(  # pyright: ignore
query_data=query_data, need_headers=True
)
```
Fixed by re-raising the original exception, which contains useful information.

[GitHub] Add missing re-raise on ClientResponseError

---

connectors/sources/salesforce.py
tests/sources/test_salesforce.py

In Salesforce, when a file is uploaded, a [ContentDocument](https://developer.salesforce.com/docs/atlas.en-us.244.0.object_reference.meta/object_reference/sforce_api_objects_contentdocument.htm) object is created, and it links to multiple [ContentVersion](https://developer.salesforce.com/docs/atlas.en-us.244.0.object_reference.meta/object_reference/sforce_api_objects_contentversion.htm) objects, which keeps all the history of the file.
The `ContentDocument` has a `LatestPublishedVersionId` field linking to the current version of the file, and we used `VersionDataURL` of the `ContentVersion` to download the file:
>The URL used to fetch a file from the binary data endpoint. This field is only populated on direct queries to ContentVersion, and not when queried through a related entity’s …

Use VersionData endpoint to download content

---

.ruff.toml
connectors/sources/directory.py
requirements/framework.txt
tests/test_logger.py

I skimmed through the `ruff` docs and saw that there are `ASYNC` rules:
- No blocking http calls
- No blocking sleep, open or subprocess calls
- No blocking os method calls
I think these can be pretty useful to avoid blocking the event loop. We already had examples in the past, where we used blocking `os` calls.
Also fixed the issues the linter found. Added `aiofiles` as requirement to enable local async file operations.

[Linter] Add ASYNC rules and fix issues

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

This fixed the issue with changed content of a file (driveItem) not being picked up by an incremental sync. 
The simple solution is to disable timestamp checks for site_drives and then rely on efficient delta api to get all changes for drive items. 
I verified that the  drive_item <-> drive_site is the only scenario when change to an object doesn't update its "parent" `lastModifiedDateTime` field.  Interestingly, drive item updates would result in timestamp updates for its parent "list" and "site", so we are safe at keeping timestamp checks for sites.
For other object types in SPO there were no "unexpected" behaviour when it comes to updating timestamps after edits.
I realized that with `fetch_drive_item_permissions` enabled, the incremental sync will fail at handling `DELETE` operations …

[SPO] Fix bugs when handling drive_items in incremental sync

---

.ruff.toml
connectors/filtering/basic_rule.py
connectors/source.py
connectors/sources/generic_database.py
connectors/sources/github.py
connectors/sources/mssql.py
connectors/sources/mysql.py
connectors/sources/outlook.py
connectors/sources/postgresql.py
connectors/sources/servicenow.py
tests/filtering/test_validation.py
tests/protocol/test_connectors.py
tests/sources/test_google_drive.py
tests/sources/test_mysql.py
tests/sources/test_sharepoint_online.py

Adding new linter rule: https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
This rule helps with simplifying the code working with comprehentions. All the changes in the code are done with `make autoformat` and remove redundant usage of `list`, `set` and such.

Add flake8-comprehentions(C4) ruff rule

---

connectors/sources/postgresql.py
tests/sources/fixtures/postgresql/connector.json
tests/sources/fixtures/postgresql/fixture.py

According to the [postgres wiki](https://wiki.postgresql.org/wiki/Retrieve_primary_key_columns), this is the optimal query to use for getting a table's primary key.
The previous query we were using had a limitation insofar as: a user with restricted permissions (_eg_ only the `pg_read_all_data` role) can't see data in `information_schema.table_constraints`, and thus cannot determine the primary key for a table.
The new query being used here does not appear to have that limitation.
-----
Related to the above: we are also updating the Postgres functional tests to configure the connector with a user that has reduced (read-only) permissions. Thanks @artem-shelkovnikov for the suggestion.

Improve PostgreSQL query for identifying primary keys

---

tests/services/test_base.py
tests/services/test_job_cleanup.py
tests/services/test_job_execution.py
tests/services/test_job_scheduling.py

There are some repeated codes in `tests/services/*`. This PR moves those functions to `tests/services/test_base.py`

Move common functions to test_base.py

---

connectors/protocol/connectors.py
connectors/services/job_execution.py
tests/protocol/test_connectors.py

Make the `pending_jobs` method of `SyncJobIndex` to be able to fetch pending jobs by job type. This is to prepare for the PR [Break JobExecutionSerivce to ContentSyncJobExecutionService and AccessControlSyncJobExecutionService](https://github.com/elastic/connectors/pull/1840).

Make pending_jobs fetch jobs by job types

---

connectors/services/base.py
connectors/services/job_execution.py
tests/services/test_base.py
tests/services/test_job_execution.py

Move the `_override_es_config` method to `BaseService`, because this can be used by other services besides `JobExecutionSerivce`, and `JobExecutionService` will be broken into two service classes by PR https://github.com/elastic/connectors/pull/1840

Move _override_es_config to BaseService

---

connectors/sources/postgresql.py
tests/sources/fixtures/postgresql/connector.json
tests/sources/fixtures/postgresql/fixture.py

Manually backporting https://github.com/elastic/connectors/pull/1823 to 8.11 since I missed adding the appropriate labels in the original PR.
```
git cherry-pick 8bbc3f11a6c96bae226e9351c29162899d1d3434
```
cc @artem-shelkovnikov

[8.11] Improve PostgreSQL query for identifying primary keys (#1823)

---

connectors/sources/network_drive.py
tests/sources/fixtures/network_drive/connector.json
tests/sources/test_network_drive.py

This PR addresses following issue:
- Added a configurable field for `Drive type` as discussed in weekly sync with @danajuratoni. This field will be visible when the DLS is enabled and it allows two values `Linux` and `Windows` as the connector supports DLS for Linux and Windows Network Drives only. Further it is kept advanced field as the native connector flows only supports DLS in Windows Network Drive. The support for Linux Network Drive is added via csv path that can only be used via self-managed connector client flow (https://github.com/elastic/connectors/pull/1773 )

[Network Drive] Add Dropdown for Drive type

---

connectors/es/client.py

Following up on a renaming of the repo from `connectors-python` to `connectors`. 
In this change I rename user agent string used by ES client.

Update user agent string for the ES client

---

connectors/utils.py
tests/test_utils.py

This PR uses `asyncio.BoundedSemaphore` instead of `asyncio.Event` to control the max concurrency of `ConcurrentTasks`
1. `BoundedSemaphore` is a better fit for this use case.
2. There's a [bug](https://github.com/elastic/connectors-python/pull/1477#issuecomment-1690159544) in the original implementation, and you can verify it by adding and running this test in [test_utils.py](https://github.com/elastic/connectors-python/blob/main/tests/test_utils.py):
```python
@pytest.mark.asyncio
async def test_concurrent_runner():
async def coroutine(i, sleep_time):
await asyncio.sleep(sleep_time)
print(f"Complete task {i}")
runner = ConcurrentTasks(max_concurrency=1)
await runner.put(functools.partial(coroutine, "a", 0.1))
print()
print(f"task a was pushed into pool at {datetime.now()}")
await …
```

Use BoundedSemaphore instead of asyncio.Event to control the max concurrency

---

connectors/sources/sharepoint_server.py

Minor cleanup: method `convert_file_to_b64`:
- Does not convert anything
- Is not used at all
Removing the method

Remove convert_file_to_b64 in SP Server (unused)

---

docs/CONTRIBUTING.md
docs/DEVELOPING.md

- [[DOCS] Update CONTRIBUTING.md, DEVELOPING.md (#1875)](https://github.com/elastic/connectors/pull/1875)

[8.10] [DOCS] Update CONTRIBUTING.md, DEVELOPING.md (#1875)

---

connectors/sources/sharepoint_online.py

This PR adds the `OData__UIVersionString` to the documents. This field is useful to filter out drafts using sync rules.
When this option enabled:
Files can have versions. 
0.1 means unpublished draft
After published becomes 1.0
Then I save a new draft and becomes 1.1
Sync rule to exclude drafts (everything that doesn't end with 0): `^(?!.*\.0$).*$`

[SPO] Adding OData__UIVersionString document version field

---

connectors/es/sink.py
tests/test_sink.py

When connectors were first being built, there was an assumption that a distinction between "full" and "incremental" syncs would not be needed. We hoped to only have one sync type, and to have it be capable of doing full table scans on its first run, but only partial scans thereafter.
In reality, this has not worked, and we've begun to introduce new sync types, specifically the Incremental sync. At the same time, we've received more and more reports that this optimization is actually a hiderance to customers working to move into production. While it was intended to save time, it in fact takes more, as every code, pipeline, or configuration change requires data to be deleted, modified, or a new index to be started from scratch. This friction was not intended or anticipated, and is …

Remove timestamp optimization for full syncs

---

connectors/sources/gmail.py
connectors/sources/google_cloud_storage.py

This PR make `service_account_credentials` RCF sensitive

Make service_account_credentials RCF sensitive

---

Dockerfile
Dockerfile.ftest

Bump Dockerfile to use `python:3.11.6-slim` for its base image to reduce the number of vulnerable libraries/packages installed with the image.
I've left 3.10 as the minimum version for the project.
Note: This relates to an internal developer productivity issue; I will link from there to this issue.

Bump Dockerfile base image to python:3.11.6-slim

---

connectors/utils.py
tests/test_utils.py

This PR introduces a new class `NonBlockingBoundedSemaphore`, which extends `asyncio.BoundedSemaphore`. The new class has a `try_acquire` method, which allows users to acquire the semaphore in non-blocking way, ie. the method will return `False` immediately if it can't acquire a semaphore.
The new method will be used by `ConcurrentTasks`, in PR #1479, where we introduced a non-blocking `try_put` method, which allows users to put task without being blocked. It's a bit tricky to implement it with the existing `asyncio.BoundedSemaphore` class and it doesn't work as expected under certain edge cases (see discussion in https://github.com/elastic/connectors/pull/1479#discussion_r1383112200). And we found that the most easy and clean way to achieve this was to extend the …

Extend a non-blocking Semaphore implementation

---

connectors/utils.py
tests/test_utils.py

This PR adds a `try_put` method to `ConcurrentTasks`. Compared to the `put` method, `try_put` will return a `None` task immediately if the `ConcurrentTasks` are not ready to accept a new task.
The new method will be used in #1865, by both `AccessControlSyncJobExecutionService` and `ContentSyncJobExecutionService`. 
The existing `put` method is blocking, which will prevent the loop of both services from going to the next iteration.
While `try_put` will return immediately if there's no space available, allowing the service to try in the next iteration instead of blocking.

Add non-blocking try_put method to ConcurrentTasks

---

connectors/sources/github.py
tests/sources/test_github.py

This will backport the following commits from `main` to `8.11`:
- [[GitHub] Add missing re-raise on ClientResponseError (#1806)](https://github.com/elastic/connectors/pull/1806)

[8.11] [GitHub] Add missing re-raise on ClientResponseError (#1806)

---

connectors/protocol/connectors.py
tests/protocol/test_connectors.py

Sometimes, an Exception is raised that has no `message` property. This is common for errors like `NoneTypeError`, `NotFound` or any internal exception we use like:
```
class SomeError(Exception)
pass
...
raise SomeError() 
```
Our Extractor sets the `fetch_error` to be the instance of the caught exception, and we log it, but the connector sync job was getting updated with `str(e)`, which ends up being the empty string for these types of exceptions.
This PR adds some conditionals to attempt to generate a good error message based on what is passed to the `fail` function.
Fixes a bug where some sync jobs might fail with an empty error message

Ensure that Exceptions with empty error messages at least state the exception

---

resources/connectors_api/Connectors API.postman_collection.json
resources/connectors_api/README.md

This PR adds the postman collection for the Connectors API, which can be used for manual testing during development. It contains all happy paths requests and also edge cases to verify validation, parsing etc.

[Connectors API] Add postman collection

---

connectors/services/job_cleanup.py
tests/services/test_job_cleanup.py

Recent refactoring changed signature of method `SyncJob.fail` by renaming "message" argument to "error". This caused errors in console - job cleanup failed because of unexpected argument.

Fix job cleanup calling fail with wrong argument

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

- [[SPO] Fix bugs when handling drive_items in incremental sync (#1827)](https://github.com/elastic/connectors/pull/1827)

[8.10] [SPO] Fix bugs when handling drive_items in incremental sync (#1827)

---

connectors/cli/job.py
connectors/connectors_cli.py
connectors/protocol/connectors.py
tests/test_connectors_cli.py

Very often it's required to get information about a specific job. This PR adds a new command `job view {JOB_ID}` that shows information. 
Also, I added `--format` option to display the output in different formats like text or JSON. 
We have added a new command `connector job view {JOB_ID} --format {text|json}`.

[CLI] Add a command to show specific job informaton

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

during 8.12 QA it was noticed that the SPO connector was making permissions-related API calls to Sharepoint, even if Document Level Security was disabled. Turns out one of our functions just wasn't gating its logic sufficiently. 
After this change, I was able to quickly sync our entire test sharepoint instance without seeing any evidence of `/permissions`, `/users` or `/groups` API calls being made when DLS was disabled.
fixes a bug where the Sharepoint Online connector was making unnecessary API requests when DLS was disabled. This should improve performance if DLS is not enabled for the Sharepoint Online connector.

check if DLS is enabled before fetching drive item permissions

---

connectors/es/sink.py
tests/test_sink.py

1. Changed the log level to `warning` when a sync job is forcibly canceled
2. Ignore any error thrown in `Sink` or `Extractor` class if the `Sink` or `Extractor` object is forcibly canceled
In the last release, we [Forcibly cancel a sync job after waiting for 5 seconds](https://github.com/elastic/connectors/pull/1683). This should not be treated as `ERROR`, therefore we want to log it at `warning` level.
When we forcibly cancel the `Sink` or `Extractor` task, it will throw a `ForceCanceledError`. But sometimes there can be other errors thrown due to task cancellation, and be caught first. Before we log those errors as `critical`, we want to check if the task is forcibly canceled. If so, we will ignore those errors, and instead log a `warning` message that the task is forcibly canceled.

Ignore errors when Sink or Extractor is forcibly canceled

---

tests/sources/fixtures/fixture.py

This PR changes functional tests fixture to handle 429 errors from Elasticsearch. This change for now is isolated to fixture.py. In subsequent PRs I'm planning to do the following:
1. Make retry a part of ESClient class and retry transparently
2. Get rid of places calling `ESClient.client` and make `ESClient` a rich client.

Make test fixture retry 429 errors

---

connectors/connectors_cli.py

This PR removes `blink=True` that we accidentally added during the first phase of deployment.

[CLI] Remove blink=True

---

connectors/sources/mysql.py

Removes the duplicate primary keys check in advanced sync rules for the MySQL connector to enable JOINs, also when the primary keys of different tables are the same.

[MySQL] Remove duplicate PK check in advanced sync rules

---

connectors/sources/mysql.py

This will backport the following commits from `main` to `8.11`:
- [[MySQL] Remove duplicate PK check in advanced sync rules (#2005)](https://github.com/elastic/connectors/pull/2005)

[8.11] [MySQL] Remove duplicate PK check in advanced sync rules (#2005)

---

.buildkite/pipeline.yml

Minor convenience improvement:
We want to run all functional tests on PR if the file `"tests/sources/fixtures/fixture.py"` was changed - any changes in this file can potentially break fixtures.
This is exactly what happened for PostgreSQL fixture that caused [this PR](https://github.com/elastic/connectors/pull/2009) to be created.

Include fixture.py into diff for all pipeline tests

---

tests/sources/fixtures/azure_blob_storage/fixture.py
tests/sources/fixtures/dir/fixture.py
tests/sources/fixtures/fixture.py
tests/sources/fixtures/google_cloud_storage/fixture.py
tests/sources/fixtures/mongodb/fixture.py
tests/sources/fixtures/mongodb_serverless/fixture.py
tests/sources/fixtures/mssql/fixture.py
tests/sources/fixtures/mysql/fixture.py
tests/sources/fixtures/network_drive/fixture.py
tests/sources/fixtures/oracle/fixture.py
tests/sources/fixtures/postgresql/fixture.py
tests/sources/fixtures/s3/fixture.py

Current builds are failing because PostgreSQL fixture is using event loop to run async postgresql client. With recent change I've made `tests/sources/fixture.py` class async (to reuse code) and it caused this one fixture to fail, because it's running `run_until_complete` on current event loop that is already doing this.
So far the situation is:
1. Postgresql fixture uses async code
2. MongoDB/MySQL connectors use async code, their fixtures do not use async code (should be fixed)
3. PostgreSQL, MSSQL and OracleDB connectors and their fixtures do not use async code (there are manual wrappers), this should be fixed
So for now this async change just makes it work for PostgreSQL's fixture, but it also opens up way for unification of fixtures with connectors for MongoDB/MySQL (they can use same …

Make fixtures async

---

connectors/sources/postgresql.py

Removes the duplicate primary keys check in advanced sync rules for the PostgreSQL connector to enable JOINs, also when the primary keys of different tables are the same.

[PostgreSQL] Remove duplicate PK check in advanced sync rules

---

requirements/framework.txt

This PR updates `elasticsearch` client to latest + updates `elastic-transport` to latest

Update Elasticsearch client to 8.11

---

requirements/framework.txt
requirements/tests.txt

Updating aiohttp to 3.9.0 + updating aioresponses to 0.7.6 - aioresponses is used for mocking aiohttp server responses and current version is not compatible with new aiohttp.

Update aiohttp to latest

---

connectors/cli/auth.py
connectors/cli/connector.py
connectors/cli/index.py
connectors/cli/job.py
connectors/es/client.py
connectors/es/management_client.py
connectors/es/settings.py
connectors/es/sink.py
connectors/kibana.py
connectors/preflight_check.py
connectors/services/job_cleanup.py
tests/es/test_client.py
tests/es/test_management_client.py
tests/services/test_job_cleanup.py
tests/sources/fixtures/fixture.py
tests/test_connectors_cli.py
tests/test_kibana.py
tests/test_preflight_check.py
tests/test_sink.py

This PR changes more places to use rich Elasticsearch clients instead of direct calls to python Elasticsearch client.
Example methods that were introduced or changed with this PR:
- `ESManagementClient.ensure_exists` method got "expand_wildcards" argument that's default to `open` - some places use "all", but most of the places use "open". "open" is also more conservative, thus the choice
- `ESManagementClient.create_content_index` - new method to create content index. Normally kibana does it, but in some cases (mostly CI or CLI) we wanna create the index ourselves. _This method is just extracted from the original place that was calling non-rich Elasticsearch client with no changes_
- `ESManagementClient.ensure_content_index_mappings` - new method to ensure that content index has our …

Replace more places accessing Elasticsearch client directly with proxied calls

---

connectors/connectors_cli.py

Minor fix:
Calling `bin/connectors index` outputs nothing for me:
```
artemshelkovnikov-m2@Work-M2 connectors-py % bin/connectors index
artemshelkovnikov-m2@Work-M2 connectors-py %
```
With this change, it will display help for `index` command exactly in same way it does it for job/connector:
```
artemshelkovnikov-m2@Work-M2 connectors-py % bin/connectors index
Usage: connectors index [OPTIONS] COMMAND [ARGS]...
Search indices management
Options:
--help  Show this message and exit.
Commands:
clean   Remove all documents from the index
delete  Delete an index
list    Show all indices
```

Make bin/connectors index without arguments output help

---

connectors/es/index.py

Minor improvement for `clean_index` - added `conflicts=proceed` to not fail the cleaning of the index if conflicts happened during clearing.
Normally conflicts can happen if document was updated while the delete_by_query is executed (this includes ingest pipelines updating a document after it was ingested)

Make clean_index method proceed on conflicts

---

connectors/sources/github.py
tests/sources/fixtures/github/fixture.py
tests/sources/test_github.py

Connector throws an error in the case of admin:org and write:org scopes. Now add admin:org and write:org to valid scopes and add a warning if the connector finds higher privileges than required.

[GitHub] Fix scopes related issue

---

README.md
docs/CLI.md

This adds a Connectors CLI documentation page.

[CLI] Add documentation

---

connectors/sources/mongo.py
tests/sources/test_mongo.py

This PR makes it possible to use MongoDB connector with user that has _only_ privilege to read from a collection.
Before this PR, privileges to list databases/collections was also needed.
Validation logic got more complex and I feel that it can be simplified.
What we do now in steps:
1. Check if collection is accessible by current user
2. If it is, validation is successful
3. If not, try to read list of databases and collections and show the user available dbs/collections in UI
4. If any of operations in 3. fail, we display a message that user has no access to the collection/database and they manually need to ensure that these collection, database exist and user has access to them
Is it getting too complex?
We can safely drop steps 3/4 and always show validation error without availables …

Make mongodb work without admin privelege

---

LICENSE
connectors/services/job_cleanup.py
tests/services/test_job_cleanup.py

relates to: https://github.com/elastic/enterprise-search-team/issues/6075
This removes deleting indices for orphaned jobs, as we may be inadvertently deleting indices that should be kept in some edge cases.
On some edge cases where Elasticsearch is facing issues we may be inadvertently deleting content indices, because we incorrectly think the index has been deleted. This change removes the step where we delete indices.

Remove automatically deleting indices for orphaned jobs

---

connectors/es/index.py
tests/es/test_index.py

We have a theory that we've been hitting some bugs when ES is unhealthy and returns non-200 responses for `_search` requests. This PR changes our client behavior to raise the ApiError if we hit one, instead of implicitly returning an empty result set for the executed search.
- see also: https://github.com/elastic/connectors/pull/2038
Fixes a bug where Elasticsearch health issues might be passed over. Previously, if Elasticsearch returned a 500 error when connectors executed a `_search`, this error was not propagated correctly.

Raise an error if our ES client fails to execute a _search

---

connectors/connectors_cli.py
scripts/stack/README.md
scripts/stack/configure-connectors.sh
scripts/stack/copy-config.sh
scripts/stack/run-stack.sh

Reverts the changes to the `connectors_cli.py` configuration loading in favour of the original method. Updates the scripts to use a separate configuration for the CLI used in the Connectors configuration script to connect to the Elasticsearch instance.

Revert Changes to Connectors CLI Config Loading and Use Separate Configuration for Stack Scripts

---

connectors/sources/network_drive.py
tests/sources/fixtures/network_drive/connector.json
tests/sources/test_network_drive.py

The Deny permissions takes precedence over Allow permissions in Windows Network Drive. So the following two cases have been addressed:
1. If a user has Explicit Deny permissions along with another Explicit allow permission, then the user is denied the access. #1966 
2. If a Group has Deny permission but a user of the group has Explicit allow permission, then the user is denied the access. #1963

[Network Drive] [DLS] Fix precedence for Deny permissions

---

connectors/preflight_check.py

See: https://elastic.slack.com/archives/C01795T48LQ/p1704910889935649?thread_ts=1704851023.342089&cid=C01795T48LQ
The connectors process exits if no connectors are configured, but it doesn't really tell you where to get the necessary information for configuration. This could help.

give CTA if no connectors are configured

---

connectors/services/job_cleanup.py
tests/services/test_job_cleanup.py

- [Remove automatically deleting indices for orphaned jobs (#2038)](https://github.com/elastic/connectors/pull/2038)

[8.10] Remove automatically deleting indices for orphaned jobs (#2038)

---

.buildkite/pipeline.yml

(ad hoc change)
* adds some generous timeouts to the make/lint/ftest steps
* unfortunately it does not appear we can add timeouts to steps that are generated via the monorepo-diff plugin; if this becomes a problem in the future, we can fork that plugin and add timeout support ourselves
* unrelated: removes some extraneous whitespace

Add timeouts to Buildkite steps

---

catalog-info.yaml

In order to be compliant with Search Developer Productivity charter and be able to work with Search CI pipelines, it's required to grant @elastic/search-productivity-team permissions to connectors Buildkite pipelines.
This PR is dedicated to granting Search Developer Productivity team permissions to all connectors Buildkite pipelines

Add search-productivity-team to connectors Buildkite pipelines

---

connectors/sources/salesforce.py

This problem is faced while the API name (which is used in SOQL query to fetch data) is different in the Salesforce edition. I also noticed that the `/sobjects` endpoint provides the custom objects with the suffix `__c`, `__e` and might be some others, so we filter out the custom objects having just `__c` as a suffix in object API name.

[Salesforce] Add custom object support with different API Names

---

connectors/protocol/connectors.py
connectors/services/job_cleanup.py
tests/protocol/test_connectors.py
tests/services/test_job_cleanup.py

Instead of deleting orphaned jobs, this PR tries to mark those orphaned (i.e. sync jobs with deleted connectors) idle (sync jobs seeing no update for more than 1 min) sync jobs as `error`.
When a customer deletes a connector in Kibana, it will not delete all the associated sync jobs. Those orphaned sync jobs are kept for audit purporse. If the orphaned sync jobs are idle, we will mark them as `error`

Mark orphaned idle sync jobs as error

---

setup.py

We set the architecture to `x86_64`, if we cannot determine the machine architecture. I think it's useful to log it, if this happens.
~- [ ] this PR links to all relevant github issues that it fixes or partially addresses~ (there is no issue, just stumbled across this)
~- [ ] if there is no GH issue, please create it. Each PR should have a link to an issue~

[Setup] Add logging, when default architecture is set

---

connectors/utils.py
setup.py
tests/test_utils.py

Fix connectors packaging in Enterprise Search. 
```
python3 -m pip install .
```
```
Processing ~/projects/connectors-python
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "~/projects/connectors-python/setup.py", line 12, in <module>
from connectors.logger import logger
File "~/projects/connectors-python/connectors/logger.py", line 17, in <module>
import ecs_logging
ModuleNotFoundError: No module named 'ecs_logging'
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: …
```

Fix packaging

---

requirements/tests.txt

Minor tweak: with certain setup the tests will error out because `faker` is not imported. It happens because `faker` dependency was declared only in functional tests requirements file.
This PR explicitly declares `faker` dependency for tests.

Add faker dependency to tests.txt requirements file

---

connectors/sources/network_drive.py
tests/sources/test_network_drive.py

This PR introduces following changes:
- Add retry mechanism in case of SMB timeouts.
- Ensure fetch_groups_info is only called when dls is enabled to prevent unnecessary network calls
The Connection to Network Drive would be re-established and request would be retried in case SMBConnectionClosed error is raised due to timeout while fetching files.

[Network Drive] Handle smb connection timeout

---

connectors/services/job_scheduling.py
tests/services/test_job_scheduling.py

Adding logic to run validation for content source configuration with every loop of scheduler service.
Before, configurable fields would be validated only when a sync job is ran, but now we're gonna run validation every time `job_scheduling_service` runs (every 30 seconds). That will actually expose errors in configurations to the customer eariler.
Now configurations of connectors are validated periodically, exposing validation errors without need to run a sync.

Validate configurable fields every loop of job scheduling service

---

.buildkite/publish_docker.sh
catalog-info.yaml

(ad hoc change)
The `connectors-nightly-docker` build recently started failing when trying to install Docker: https://buildkite.com/elastic/connectors-nightly-dockers/builds/1033
This is likely related to a recent change in the base VM image we're inheriting from. That image already has Docker and Docker Compose installed (and the Docker daemon is already running by default), so I think it should be safe to remove the steps where we install those packages at build time and then start the systemd unit.

[CI] Update 'connectors-nightly-dockers' to stop trying to install Docker

---

connectors/es/management_client.py

Instead of crashing/breaking if we try to add mappings to an index and fail, we log an error and continue. This is particularly important for stateless where in the current state adding mappings will always fail because we don't have the corresponding settings.
Partially addresses: https://github.com/elastic/connectors/issues/2095

Treat inability to create mappings as warning instead of breaking error

---

connectors/cli/auth.py
connectors/cli/connector.py
connectors/cli/index.py
connectors/connectors_cli.py
docs/CLI.md
tests/test_connectors_cli.py

These changes add Elasticsearch API keys authentication method. Also, this PR addresses the issue when CLI created API keys for native connectors. 
The new version of `./bin/connector login`
```
Usage: connectors login [OPTIONS]
Authenticate Connectors CLI with an Elasticsearch instance
Options:
--host TEXT
--method [basic|apikey]  Authentication method
--help                   Show this message and exit.
```
* https://github.com/elastic/connectors/pull/2091
Connectors CLI can authorize with Elasticsearch API keys by running `./bin/connectors login --method apikey`.

[CLI] API keys authentication

---

catalog-info.yaml

* we no longer need to build pre-`8.12`
* we should be building the same branches across all nightly pipelines

[CI] Update nightly CI pipelines to use the right branches

---

connectors/services/job_scheduling.py

Minor improvement: 
Log message that says when next sync happens was missing the sync type.
Before:
```
[FMWK][17:03:59][DEBUG] [Connector id: network_drive, index name: search-network_drive] Next sync is at 2024-02-02 16:04:01.648207
```
After:
```
[FMWK][17:03:59][DEBUG] [Connector id: network_drive, index name: search-network_drive] Next 'full' sync is at 2024-02-02 16:04:01.648207
```

Improve debug log for next sync message

---

connectors/access_control.py
tests/sources/test_confluence.py
tests/sources/test_github.py
tests/sources/test_google_drive.py
tests/sources/test_jira.py
tests/sources/test_salesforce.py
tests/sources/test_servicenow.py
tests/test_access_control.py

In a review of the [DLS + Internal Knowledge Search blog](https://www.elastic.co/search-labs/blog/articles/dls-internal-knowledge-search), @xeraa [had commented](https://github.com/elastic/search-labs-elastic-co/pull/292#discussion_r1467288194) that our DLS query looked overly complex. This sent me down a rabbit hole, first figuring out that our example DLS app _was_ using an overly-complex query, then wondering why we were having to create an explicit query at all, then finally realizing I'd had these thoughts before and filed https://github.com/elastic/connectors/issues/1696 to eventually address the issue.
The time has come. 
This PR removes the outer `bool: { filter: {` clause that's no longer necessary (since Workplace Search) as we do not have a `_deny_access_control` pattern for …

fix acl query template

---

tests/sources/fixtures/oracle/connector.json
tests/sources/fixtures/oracle/docker-compose.yml
tests/sources/fixtures/oracle/fixture.py

This updates the Oracle connector's functional tests to use an officlal container image from Oracle, instead of the community/third-party Oracle Express Edition image we have been using. According to [this post](https://medium.com/version-1/oracle-database-express-edition-now-database-free-ed5aa444152), Oracle Free appears to supersede Express Edition, so it probably makes sense to switch to testing against it.
Note however that with this change we are still can't enable the Oracle functional tests [on arm64](https://github.com/elastic/connectors/blob/main/.buildkite/nightly_steps.yml#L41), since getting an arm64 Oracle container image is [a bit more complicated](https://github.com/elastic/connectors/issues/1579#issuecomment-1924745013).

Switch to an official Oracle container image in functional tests

---

connectors/sources/sharepoint_online.py

See https://elastic.slack.com/archives/C7LLL50CA/p1706800182262059?thread_ts=1705426484.605769&cid=C7LLL50CA
Users can get an error that tells them that the tenant name is wrong, but it's difficult to track down _what_ is causing this issue. Adding the URL will let us go track down which item is associated with a different tennant.

Add problem URL to error message

---

config.yml
connectors/config.py
connectors/es/sink.py

We see that some use-cases of connectors cause heavy load on Elasticsearch. Because of that, ingestion mechanisms do not pick up items from the MemQueue and the job fails. Settings for MemQueue are hardcoded and this PR makes them configurable.
Made Memory Queue configurable - it's possible to avoid `QueueFull` errors in overloaded environments with this setting.

Make MemQueue used in sync configurable via config options

---

connectors/sources/network_drive.py

This reverts commit 463689bfed5572302b876bc5ab48d93de35c19ef.
As reported by some customers, this change makes connector not usable against certain versions of SMB protocol, specifically ones running on Windows Server.
Fix Network Drive connector unable to connect to certain versions of SMB server running on Windows

Revert "Specify port when calling all smbclient methods in network drive connector (#1898)"

---

connectors/es/management_client.py
connectors/es/sink.py
connectors/protocol/connectors.py
connectors/source.py
connectors/sync_job_runner.py
docs/CONNECTOR_PROTOCOL.md
tests/es/test_management_client.py
tests/protocol/test_connectors.py
tests/test_sink.py
tests/test_sync_job_runner.py

In 8.13 we will be using API keys for native connector content ingestion. This is applicable to both content and ACL syncs.
API keys are generated for native connectors upon creation ([Kibana changes here](https://github.com/elastic/kibana/pull/176046)). The API keys are stored in secrets storage, with a reference in the connector document under `api_key_secret_id`.
When performing a sync, a native connector will now fetch its API key from secrets storage and use that as the authorization header for requests. This is only for the duration of that sync. The connector will fetch the API key each time it syncs. This is so that if the user changes the API key, they don't need to restart everything to have it applied.
These changes do not impact connector clients, which will continue to use …

Use API keys for native connector syncs

---

connectors/services/job_scheduling.py
tests/services/test_job_scheduling.py

Additionally to running RCF validation (see https://github.com/elastic/connectors/pull/2093) every time we check connector for whether the job should be scheduled, now we send a ping to the backend of this connector as well to verify, that it's available.
Before this logic would happen only before sync, which is too late.
- https://github.com/elastic/connectors/pull/2093
Now configurations checks health of 3rd-party system periodically and reports errors to Kibana. Previously it was only done before the sync is started.

Add logic to send a ping to connector's backend every loop

---

connectors/sources/gmail.py

In the Gmail connector's config, the 'Subject' config field's label didn't match how that field is referred to in the [docs](https://www.elastic.co/guide/en/enterprise-search/8.12/connectors-gmail.html). It should be labeled 'Google Workspace admin email' instead.

Make Gmail connector's 'subject' field label match docs

---

connectors/sources/azure_blob_storage.py
connectors/sources/github.py
connectors/sources/gmail.py
connectors/sources/microsoft_teams.py
connectors/sources/outlook.py
connectors/sources/salesforce.py

This enables incremental syncs for the connectors which can present `_timestamp` field. Therefore, they can use the optimization introduced in this [PR](https://github.com/elastic/connectors/pull/2057).
* https://github.com/elastic/connectors/pull/2057
Enable incremental sync jobs for Github, Outlook, Gmail, Azure blog storage, and Microsoft Teams connectors.

Enabled incremental syncs for more connectors

---

connectors/protocol/connectors.py

We've figured out that idle timeout of 1 minute is too small. This PR bumps it to 5 minutes.
Since this change is not connector-specific (Kibana has pieces of this logic too), it's not possible to make it a configuration option.
Increased idle job timeout from 1 minute to 5 minutes. Jobs that haven't made any progress for 5 minutes will be marked as "idle" and failed.

Bump idle job threshold to 5 minutes

---

connectors/services/job_scheduling.py
tests/services/test_job_scheduling.py

This reverts commit 038e4724d9c1471c8df893a4f595c0da6e07fc4c.
This change is a valuable one, but seems to have broken our nightly CI. We can re-introduce it in a follow-up, along with targeted fixes to the Box and Network Drive ftests that were failing. In the mean time, this will unblock some other work.
- unblocks https://github.com/elastic/connectors/pull/2146

Revert "Add logic to send a ping to connector's backend every loop (#2105)"

---

Dockerfile
Dockerfile.ftest

This reverts commit 7baa53991844f3cf43464e0e3f5908277a859b48.
Related to: https://github.com/elastic/connectors/issues/2144
Python 3.11 is incompatible with a MongoDB dependency Motor, so revert to 3.10 until that dependency issue can be resolved.

Revert "Bump Dockerfile base image to python:3.11.6-slim (#1911)"

---

connectors/es/index.py
tests/es/test_index.py

This PR adds same retry mechanism to ESIndex class - it got overlooked

Add retry to ESIndex class methods

---

connectors/sources/servicenow.py
tests/sources/test_servicenow.py

Remove the unsafe dict call from ServiceNow.
There are circumstances where tables fetched from `sys_db_object` may be missing `name` or `label` fields. Even if the user is not trying to query those tables, they are checked during the filtering operation. If `name` or `label` is missing, the connector shouldn't crash with the unsafe dict call. It should log the issue as debug and continue syncing.

Remove unsafe dict call from ServiceNow

---

connectors/sources/atlassian.py

This PR contain the changes in atlassian.py file for Jira Data Center DLS

Add atlassian.py for Jira Data Center DLS

---

connectors/es/sink.py
connectors/sync_job_runner.py
tests/test_sink.py
tests/test_sync_job_runner.py

API key authentication for native connectors is currently broken, because the `ESManagementClient.client.options` update func doesn't change requests to use API key authentication.
This PR changes how the `ESManagementClient` is initialised:
1. Fetch API key from connector secrets
2. Attach API key to es_config
3. Initialise ESManagementClient (using API key from the start)
To do this, it's necessary to create a second ESManagementClient that authenticates with username and password. This is because the connector secrets API is only accessible by the Enterprise Search system role.

Fix native API key authentication

---

connectors/es/management_client.py
connectors/services/job_execution.py
connectors/source.py
connectors/utils.py
tests/es/test_management_client.py
tests/services/test_job_execution.py
tests/test_utils.py

- [Generate API keys when running native connector syncs (#2188)](https://github.com/elastic/connectors/pull/2188)

[8.13] Generate API keys when running native connector syncs (#2188)

---

connectors/sources/network_drive.py
tests/sources/test_network_drive.py

This PR aims adds following changes to network drive connector
- Use of `end_of_file` for calculating file size
- Use of more Debug logs.

[Network Drive] Fix Download of documents in Windows and debug logs

---

connectors/services/job_execution.py
connectors/sync_job_runner.py

Add more debug-level logging when executing sync jobs. 
Example output from job execution service and the sync job runner:
```
[FMWK][12:17:01][DEBUG] Polling every 30 seconds for access control sync job execution
[FMWK][12:17:01][DEBUG] Polling every 30 seconds for content sync job execution
[FMWK][12:17:02][DEBUG] Polling every 30 seconds for Job Scheduling
[FMWK][12:17:02][DEBUG] [Connector id: 97VO0I0Bam-j8dNh-4C4, index name: search-g, Sync job id: BrWI0I0Bam-j8dNhIIGV] Detected pending JobType.FULL sync.
[FMWK][12:17:02][DEBUG] [Connector id: 97VO0I0Bam-j8dNh-4C4, index name: search-g, Sync job id: BrWI0I0Bam-j8dNhIIGV] Attempting to start JobType.FULL sync.
[FMWK][12:17:02][DEBUG] [Connector id: 97VO0I0Bam-j8dNh-4C4, index name: search-g, Sync job id: BrWI0I0Bam-j8dNhIIGV] Starting …
```

Add more debug logging in job execution

---

.buildkite/publish/build-docker.sh
.buildkite/publish/build-multiarch-docker.sh
.buildkite/publish/publish-common.sh
.buildkite/publish/push-docker.sh
.buildkite/publish/test-docker.sh
.buildkite/release-pipeline.yml
catalog-info.yaml

This will backport the following commits from `main` to `8.12`:
- [Pipeline Creation for Building and Pushing Connectors Docker Images (#2152)](https://github.com/elastic/connectors/pull/2152)

[8.12] Pipeline Creation for Building and Pushing Connectors Docker Images (#2152)

---

.buildkite/publish/build-docker.sh
.buildkite/publish/build-multiarch-docker.sh
.buildkite/publish/push-docker.sh
.buildkite/publish/test-docker.sh
.buildkite/release-pipeline.yml

This will backport the following commits from `main` to `8.12`:
- [[CI] Fix Issues in Docker Publishing Pipeline (#2180)](https://github.com/elastic/connectors/pull/2180)

[8.12] [CI] Fix Issues in Docker Publishing Pipeline (#2180)

---

connectors/cli/job.py
tests/test_connectors_cli.py

This PR fixes a problem that CLI uses already closed client during "cancel job" action.
This problem started happening because new transient retrier relies on proper usage of `close` method and stops executing actions if it's closed. Other clients do not (yet) follow this pattern, so the problem did not manifest itself before.

Fix problem with cancel jobs action using closed client

---

connectors/sources/network_drive.py

The PR adds following change:
- Pass configured port in the params while calling smbclient methods.
The Network Drive connector would now support non-default ports.

[Network Drive] Allow connector to work with non-default ports

---

connectors/es/management_client.py
connectors/protocol/connectors.py
connectors/services/job_execution.py
connectors/source.py
connectors/utils.py
tests/es/test_management_client.py
tests/services/test_job_execution.py
tests/test_utils.py

Revert #2188
It was discovered through QA that API keys generated by Enterprise Search on cloud cannot provide access to indices created by the user in Kibana, so this feature doesn't work.
Instead, I will make follow-up PRs providing verbose errors + instructions on how to fix native connectors that fail API key auth.

Revert "Generate API keys when running native connector syncs  #2188"

---

connectors/sources/mysql.py
tests/sources/test_mysql.py

It's possible to create DB and TABLE names in MySQL that will break current connector, for example:
```
mysql> create database `really@strange*database$name`;
mysql> use `really@strange*database$name`;
mysql> create table `really@strange*table$name` (id MEDIUMINT NOT NULL AUTO_INCREMENT, name CHAR(30) NOT NULL, PRIMARY KEY (id) );
mysql> INSERT INTO `really@strange*table$name`(name)  VALUES('dog');
```
If you try to select without escaping the table name, it will not work, the table name has to be escaped (see PR changes). This PR makes sure that all places that need to have table names escaped properly do so.
MySQL Connector: Fix an issue when special characters in database/table names make it impossible to sync data.

Fix table/db names not being escaped for MySQL connector

---

tests/ftest.sh

nightly CI was failing and the final logs were:
```
+ set +e
--
  | + echo 'Waiting for PERF8 to finish the report'
  | Waiting for PERF8 to finish the report
  | ++ ps aux
  | ++ grep bin/perf8
  | ++ grep -v grep
  | ++ awk '{print $2}'
  | + PERF8_PID=
  | + kill -0 ''
  | tests/ftest.sh: line 101: kill: `': not a pid or valid job spec
  | + set -e
  | + rm -f description.txt
  | + STATUS=1
  | + exit 1
  | make: *** [Makefile:62: ftest] Error 1
  | 🚨 Error: The command exited with status 2
```
So this attempts to just move on if we have an empty value for `PERF8_PID`

Avoid ftest perf8 race condition

---

connectors/cli/connector.py
connectors/connectors_cli.py
connectors/es/management_client.py
tests/es/test_management_client.py
tests/test_connectors_cli.py

We had to revert automated API key generation [here](https://github.com/elastic/connectors/pull/2233) because it didn't work in Cloud as we expected.
Previously, we would just allow native connectors to be created in CLI without an API key, and rely on it being generated before a sync. Now that we know this isn't possible, we need to explicitly generate and store API keys for native connectors when they are created in CLI.
- Allow API keys to be created for native connectors
- Store native connector API keys to secrets
- Update `api_key_secret_id` field on connector doc with secret id

[CLI] Create and store API keys for native connectors in CLI

---

connectors/es/management_client.py
connectors/es/sink.py
connectors/sync_job_runner.py
tests/es/test_management_client.py
tests/test_sink.py

This PR will improve the following scenarios:
1. A Customer creates a new connector and a new index using Elasticsearch API or Connectors API
2. The customer runs a full sync job
3. The connector service tries to apply mappings and fails with: 
```
[FMWK][16:54:58][WARNING] Client method 'put_mapping' retry 1: api error with status 400
[FMWK][16:54:58][WARNING] Could not create mappings for index test-mysql-custom-3, encountered error BadRequestError(400, 'mapper_parsing_exception', 'Failed to parse mapping: dynamic template [data] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"iq_text_base","fields":{"prefix":{"search_analyzer":"q_prefix","analyzer":"i_prefix","type":"text","index_options":"docs"},"delimiter":{"analyzer":"iq_text_delimiter","type":"text","index …
```

Automatically update content index settings and mappings

---

connectors/sources/redis.py
tests/sources/test_redis.py

This PR includes fix for:
1. Raising correct error incase of incorrect configuration values and correct database name

Fix logs for incorrect configuration values in Redis

---

connectors/sources/redis.py
tests/sources/test_redis.py

- [[Redis] Log correct message when cannot connect to Redis  (#2259)](https://github.com/elastic/connectors/pull/2259)

[8.13] [Redis] Log correct message when cannot connect to Redis  (#2259)

---

connectors/es/client.py

The `self.host` variable for the Elasticsearch client is set up before the AsyncElasticsearch client is created, and thus does not have various options set (such as `ca_certs` in this case) - or, better stated, the defaults for the NodeConfig are used. Once the AsyncElasticsearch client is created, a copy of the `self.host` NodeConfig is created and the additional options are merged.
This PR logs only the URL from the `self.host` at the INFO level. If DEBUG logging is turned on, an additional log line with the seed node configuration (`self.client.transport.node_pool._seed_nodes`) will be logged that has additional information including the `ca_certs` populated amongst others.
As an example, with `service.log_level: DEBUG`, the following is emitted: 
```
[FMWK][06:30:41][INFO] Waiting for …
```

Clarify Elasticsearch Client Log Message While Waiting for Connection

---

connectors/filtering/validation.py

We log the start of validation at INFO, but with this at DEBUG, it's unclear to the customer (by default) if validation succeeds or not.

log filtering validation result at info

---

connectors/services/job_execution.py
connectors/utils.py

The problem started happening due to recent fix to actually close ESClient instances properly.
The problem in short happened because the instances of ESClient were closed while SyncJobRunner was attempting to suspend the sync - to suspend the sync it needed to load the job record from ES, then update it, then do some more small calls to Elasticsearch. It failed because the client was already closed by the time these calls were made.
The change now ensures, that all tasks in ConcurrentTasks finish before actually closing ESClients.
Fixed connectors not properly suspending jobs on host being forcefully stopped.

Wait for sync jobs to finish before closing clients

---

.buildkite/pull-requests.json
catalog-info.yaml

A small CI related change to reduce the number of duplicated Buildkite jobs. This:
1) sets `"build_on_commit": false` in the `pull-requests.json` to allow the webhook settings to determine when to build
2) sets `skip_pull_request_builds_for_existing_commits: false` in the `catalog-info.yaml` file to ensure new builds are created only when there's a new commit (you can still run the comment commands to rebuild that will flow through the other webhook)

Eliminate Duplicate Buildkite Builds on Branches and PRs

---

connectors/es/sink.py

Small PR to improve consistency. We use constants for operations we're using at multiple places, so we should also use constants for `FETCH_ERROR` and `END_DOCS` IMO.
~- [ ] this PR links to all relevant github issues that it fixes or partially addresses~
~- [ ] if there is no GH issue, please create it. Each PR should have a link to an issue~
(didn't create an issue for a 20 seconds refactoring)

[Sink] Use constant for END_DOCS and FETCH_ERROR

---

connectors/es/sink.py

It should be "fill a queue with" and not "fill a queue of"

[Sink] Improve wording

---

config.yml
connectors/config.py
connectors/es/sink.py

This will backport the following commits from `main` to `8.12`:
- [Make MemQueue used in sync configurable via config options (#2079)](https://github.com/elastic/connectors/pull/2079)

[8.12] Make MemQueue used in sync configurable via config options (#2079)

---

connectors/sources/github.py
tests/sources/test_github.py

The configuration `use_document_level_security` of GitHub connector depends on field `repo_type = organization`, but function `_dls_enabled` doesn't check `repo_type`.

Check both repo_type and use_document_level_security for dls_enabled

---

scripts/testing/README.md
scripts/testing/cli.py
scripts/testing/scenarios/clients/spo_full_and_incremental_syncs.yml

We need to supply `--name` when generating the connector cli's `connector create` command in the automated test runner.

Add connector name param to automated test runner

---

connectors/sources/confluence.py

- Fixed a typo
- Split two comments, which were too long over two lines
- Added two log lines to know, which spaces are configured for a full sync without advanced rules

[Confluence] Fix typo, split long comments and add two log lines

---

connectors/es/sink.py

The method called `get_mb_size` states that it returns `MiB` (Mebibyte) so the name should also reflect it IMO instead of using `mb` (Megabyte).

[Sink] rename get_mb_size to get_mib_size

---

docs/DOCKER.md
docs/RELEASING.md

Updates for documentation: add steps to release docker images to RELEASING.MD.
The process has changed recently, and got much simpler and sweeter!

Update RELEASING.md with new docker release steps

---

connectors/sources/notion.py
tests/sources/test_notion.py

During performance testing, it was reported that the [notion sdk module](https://github.com/ramnes/notion-sdk-py/blob/d5e5f5c98ae5578ce4b0130b65ad6e8f9e92e02b/notion_client/helpers.py#L58) does not provision any retry mechanism for a paginated api call made via `async_iterate_paginated_api`. 
This PR attempts to implement `async_iterate_paginated_api` with an ability to retry a failed page. 
Simply decorating the module's helper method [async_iterate_paginated_api](https://github.com/ramnes/notion-sdk-py/blob/d5e5f5c98ae5578ce4b0130b65ad6e8f9e92e02b/notion_client/helpers.py#L58) with retryable decorator won't work as that would mean any error thrown by page k (k >1) would result in retrying from page 1 instead of retry on page k.

[Notion] Implement an ability to retry for failed paginated api call

---

connectors/protocol/connectors.py
connectors/sources/github.py
connectors/utils.py
tests/protocol/test_connectors.py
tests/sources/test_github.py
tests/test_utils.py

I found the method [get_data_by_keys](https://github.com/elastic/connectors/blob/01d30bbcbeb1c4151ceb44d46cc008e8df0dc2e6/connectors/sources/github.py#L779) in GitHub should exist in `utils`. And there's another similar implementation [_nested_feature_enabled](https://github.com/elastic/connectors/blob/01d30bbcbeb1c4151ceb44d46cc008e8df0dc2e6/connectors/protocol/connectors.py#L520) in `Features` class.
This PR move the function to `utils`.

Create a nested_get_from_dict function in utils

---

connectors/sync_job_runner.py
tests/test_sync_job_runner.py

Adds some logging on sync completion that prints out every metric that we have in the orchestrator's `ingestion_stats` dict. This means that going forward, all we have to do is add something to `ingestion_stats` in order to expose it from the logs.
The new output looks like:
```
[FMWK][10:30:03][INFO] [Connector id: eV5Fmo4BAQ4Y7gVESEBV, index name: slack, Sync job id: fF5Hmo4BAQ4Y7gVES0Dr] --- Counters ---
[FMWK][10:30:03][INFO] [Connector id: eV5Fmo4BAQ4Y7gVESEBV, index name: slack, Sync job id: fF5Hmo4BAQ4Y7gVES0Dr] 'attachment_extracted' : 0
[FMWK][10:30:03][INFO] [Connector id: eV5Fmo4BAQ4Y7gVESEBV, index name: slack, Sync job id: fF5Hmo4BAQ4Y7gVES0Dr] 'bulk_operations' : {'index': 21}
[FMWK][10:30:03][INFO] [Connector id: eV5Fmo4BAQ4Y7gVESEBV, index name: slack, Sync job id: …
```

Log all counters

---

connectors/service_cli.py
connectors/utils.py
tests/test_service_cli.py

This PR addresses the problem that if you `CTRL+C` out of the service while a long running sleep originating from `retryable` is running, the service won't exit until the sleep has finished. Therefore I've introduced one global object for all sleeps from `retryable` which can be cancelled, when `SIGINT` or `SIGTERM` are caught.

[Framework] Use Cancellable sleeps in retryable

---

docs/DEVELOPING.md

Updating older readme files to mention that we only work with python 3.10

Say that we only work with python 3.10

---

connectors/connectors_cli.py
docs/CLI.md
tests/test_connectors_cli.py

This PR adds `-h` as a flag to the connectors CLI as part of the CLI tech improvements.

[CLI] Show help page for "-h" argument

---

tests/test_connectors_cli.py

Small extension of `test_version` to also test that `--version` is a valid command to show the version

[CLI] Extend version test

---

connectors/connectors_cli.py

As part of the CLI tech improvements I've adapted the error message to not show a raw stack strace with the error message, but only show the error with a more actionable message.
Before change:
```
./bin/connectors job                                                                                                                                                                                      ─╯
File "/Users/timgrein/Repositories/connectors/./bin/connectors", line 33, in <module>
sys.exit(load_entry_point('elasticsearch-connectors', 'console_scripts', 'connectors')())
File "/Users/timgrein/Repositories/connectors/connectors/connectors_cli.py", line 627, in main
cli()
File "/Users/timgrein/Repositories/connectors/lib/python3.10/site-packages/click/core …
```

[CLI] Improve config missing error handling

---

connectors/service_cli.py

From the string it looks like we would've wanted to log the exception `[...] {e} [...]`, but we actually didn't, so adjusting it.

[Service CLI] Log exception, if uvloop couldn't be enabled

---

connectors/es/client.py

Learned today about a header that is used by Beats, Kibana, and Fleet, to help breakdown telemetry and identify product traffic vs customer traffic.

Add X-elastic-product-origin header

---

tests/sources/fixtures/github/connector.json

Follow-up PR of #2272
Extracted from PR #2372
This PR updates the configuration in connector.json for GitHub ftest.

Update connector.json for GitHub ftest

---

connectors/service_cli.py
tests/test_service_cli.py

This PR migrates the `service_cli.py` to use the `click` library without changing any messages or behavior. I've also closed some testing gaps. Follow-ups, which will be kept separate from this PR to keep reviews focused:
- Improve help messages
- Consolidate duplicate logic between `connectors_cli.py` and `services_cli.py`

[Service CLI] Migrate to click

---

connectors/cli/auth.py
connectors/cli/connector.py
connectors/cli/index.py
connectors/cli/job.py
connectors/es/cli_client.py
connectors/es/client.py
tests/es/test_cli_client.py
tests/es/test_client.py
tests/test_connectors_cli.py

This PR adds a new property `user_agent` to the `ESClient` class, which can be overridden, so we're able to track different origins. `CLIClient` overrides this property to `connectors-cli` so we're able to track CLI usage. Also added one missing test to `ESClient`.

[CLI] Track CLI usage through user agent header

---

connectors/sources/jira.py
tests/sources/test_atlassian.py
tests/sources/test_jira.py

This PR removes leading slashes from the endpoints used in the connector and adding an extra '/' in the host url to prevent the NotFound error.
Adds support for Jira Server and Jira Data Center where the root of the server is hosted behind a path, and not at a root of the host/domain.

[Jira] Fix NotFound when the path is present in host URL

---

LICENSE
connectors/sources/github.py
tests/sources/test_github.py

1. A GitHub app can be installed on multiple organizations/personal accounts, each called an installation.
2. To list all installations of a GitHub app, you need to call [List installations for the authenticated app](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installations-for-the-authenticated-app) API with a jwt token generated from the GitHub App ID and a private key
3. To access content from an installation (on either an org or a personal account), you have to [Create an installation access token for an app](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app), which is valid for one hour.
4. With the installation access token, you can access the repos/PRs/issues/content (based on the permissions …

Update GitHubClient to support GitHub App authentication

---

tests/sources/test_atlassian.py

Adds a test for a previously untested function, since `atlassian.py` was our weakest link in the coverage report.
```
connectors/sources/atlassian.py                               96     16    83%   94, 111-133, 136-137
```

Add unit test for atlassian fetch_all_users

---

connectors/sources/github.py
tests/sources/test_github.py

This PR updates the config validation and advanced rules validation to support GitHub App authentication:
1. The configured repositories must be repo name with the owner, i.e. `OWNER/REPO`
2. The owner of the configured repo must have the GitHub App installed
3. The GitHub App must have access to the configured repo

Update config validation to support GitHub App authentication

---

connectors/sources/notion.py
tests/sources/test_notion.py

Backports the following commits from main to 8.14:
- [Notion] [Bugfix] Handle error on fetching children of external objects (https://github.com/elastic/connectors/pull/2337)
- [Bugfix] [Notion] Objects not shared with Integration or not found should not fail the sync (https://github.com/elastic/connectors/pull/2312)

[8.14] [Notion] Handle error on fetching children of external objects and Objects not shared with Integration

---

connectors/sources/github.py
tests/sources/test_github.py

Allows for cases where the PR review author is `None` to not crash the sync.

Safely get author login for PR reviews

---

connectors/sources/graphql.py
docs/reference/graphql.md
tests/sources/fixtures/graphql/connector.json
tests/sources/test_graphql.py

Rename `graphql_object_list` to `graphql_object_to_id_map` for better understanding.

[GraphQL] Rename "graphql_object_list" to "graphql_object_to_id_map"

---

.github/workflows/label-community-issues.yml
.github/workflows/scripts/label_community_issues.py

Adds an action workflow to tag issues created by external contributors with the labels:
- `community-driven`
- `needs-triage`
I tested this on a personal repo https://github.com/navarone-feekery/crawler-test-static-site
Example external user issue: https://github.com/navarone-feekery/crawler-test-static-site/issues/26
Example collaborator issue: https://github.com/navarone-feekery/crawler-test-static-site/issues/24

Add action workflow for community issues

---

docs/reference/opentext_documentum.md

This will backport the following commits from `main` to `8.14`:
- [[Opentext Documentum] Connector client documentation (#2416)](https://github.com/elastic/connectors/pull/2416)

[8.14] [Opentext Documentum] Connector client documentation (#2416)

---

connectors/sources/jira.py
tests/sources/fixtures/jira/fixture.py
tests/sources/test_jira.py

Previously we're getting custom field ids in the API response, now we fetch all custom fields and mapping their names with the ids present in the response.
Maps custom fields' IDs of `issue` documents to the custom field names.

[Jira] Map custom field ids with their names

---

connectors/sources/jira.py

Adding a support for the configured project keys that belongs to the [reserved keywords](https://confluence.atlassian.com/gsgtest/advanced-searching-815566220.html#:~:text=summary%20~%20%22%5C%5C%5Bexample%5C%5C%5D%22-,Reserved%20words,-JQL%20also%20has) in `Jira project keys` configuration fields.
Handles reserved keywords (such as `IS`, `ACCESS`, etc.) present in `Jira Projects` configuration field.

[Jira] Add support for reserved keywords as a project key in `Jira project keys` RCF

---

connectors/sources/github.py
tests/sources/test_github.py

The author is missing from docs of types `issue` and `pull_request`. This change adds `{ "login": "<name>" }` to the `author` fields for these docs.
I considered directly adding `author.login` to the `author` field as a text-type, but I thought that might add unnecessary complexity if we want to add more `author.x` keys in the future.
Also doing this change exposed some tests that didn't work as expected for this source, so I also fixed those up.

[GitHub] Add author to issue and pull request docs

---

connectors/sources/network_drive.py
tests/sources/test_network_drive.py

- [[Network Drive] Change traversal strategy to ingest as you go instead of pre-fetching the whole tree for sync rule (#2355)](https://github.com/elastic/connectors/pull/2355)

[8.13] [Network Drive] Change traversal strategy to ingest as you go instead of pre-fetching the whole tree for sync rule (#2355)

---

connectors/sources/confluence.py
tests/sources/test_confluence.py

Handles the rate limit by retrying for 429 error code with respect to the `Retry-After` header.

[Confluence] Handle rate limit

---

connectors/services/job_scheduling.py

While fixing a bug with jobs not being scheduled, I've broken concurrent scheduling. This PR aims to fix it.
Current scheduling logic is to look back when scheduling a job:
Let's say that connector is set up to schedule syncs every 15 minutes, so syncs will happen at minutes XX:00, XX:15, XX:30, XX:45 of every hour.
Connector wakes up every 30 seconds and checks whether sync should be started.
Let's simulate what happens from when service was started.
Service wakes up at 12:14:45. It sees that it just started, so it does not schedule anything.
Next time it wakes up at 12:15:16 (1 second is just arbitrary loop lag here). It checks when the sync should have been started by taking first wake up time (12:14:45) and running it against a cron definition - it will be 12:15:00. Service looks back …

Fix concurrent scheduling

---

connectors/es/sink.py
tests/test_sink.py

This PR makes 2 changes:
1. When there's field `_id` missing in a document, skip the document and log an error message
2. When one or more operations fail in a bulk request, don't fail the whole sync job, log the error message instead.

Don't fail the sync if there are failed operations in the bulk api request

---

requirements/aarch64.txt
requirements/arm64.txt
requirements/x86_64.txt

Previous version bump in [Bump pymongo from 3.13.0 to 4.6.3 in /requirements #2474](https://github.com/elastic/connectors/pull/2474) broke installation as dependent packages were not upgraded. Weirdly, tests did not catch this.
This PR upgrades relevant mongodb libraries to latest

Upgrade motor and pymongo[srv]

---

scripts/stack/copy-config.sh
scripts/stack/run-stack.sh

This PR makes 2 changes:
1. Copy `config.yml` from `config.yml.example` instead of `config.yml` due to change introduced in #2280 
2. Run `copy-config.sh` before starting Elastic connectors

Copy config.yml from config.yml.example

---

tests/sources/fixtures/mysql/docker-compose.yml

Functional tests for MySQL started failing due to new image of mysql released. New image seems to have plugin changes and some of our settings that we use (namely, auth) are done differently.
For now let's just pin MySQL version we use for testing (does not affect connector, affects only functional tests).

Use 8.3 mysql docker image for ftest

---

connectors/sources/oracle.py
tests/sources/fixtures/oracle/connector.json
tests/sources/test_oracle.py

Added the new RCF for connecting to Oracle with Service name.

Update Oracle connector to support service name

---

catalog-info.yaml

We should be building the same branches across all nightly pipelines: at the moment, we need to build 8.13 and 8.14 branches.

Update `connectors-nightly-dockers` pipeline to use the right branches

---

connectors/cli/index.py
connectors/connectors_cli.py
connectors/es/management_client.py
tests/test_connectors_cli.py

`GET _stats` API isn't available in Elasticsearch serverless so this PR will introduce a workaround for `./bin/connectors index list` command.

Support serverless in index list command

---

connectors/sources/jira.py
tests/sources/test_jira.py

Raise EmptyResponseError if the response body is empty when the status code is 200.

[Jira] Handle empty response when status code is 200

---

connectors/sources/github.py
tests/sources/test_github.py

Raising 403 exception same as unauthorized exception in Github
Raises 403 as ForbiddenException in GitHub connector. Previously, the connector skipped the 403 status code.

[GitHub] Raising 403 exception

---

connectors/sources/jira.py
tests/sources/test_jira.py

This PR has the following changes:
- converting `get_jira_fields` method from coroutine to generator
- adding a new field in ingestion document for showing custom fields
Adds a new field for custom field. The elasticsearch issue document will look like as follows:
```python
{
"id": <id>,
"key": <key>,
"Issues": <issues>,
"Custom_Fields": <customFields>,
...
}
```

[Jira] show custom fields seperately

---

Makefile

Part of security hardening: we need to upgrade `setuptools` on installation. We don't directly install `setuptools`, we get it as a part of `venv` distribution.

Update setuptools package on installation

---

connectors/sources/jira.py
tests/sources/test_jira.py

Backports the following commits to 8.14:
- [Jira] Handle empty response when status code is 200 #2506

[8.14][Jira] Handle empty response when status code is 200 (#2506)

---

connectors/sources/confluence.py
tests/sources/test_confluence.py

Flaky test failures had following error:  `async generator raised StopIteration`.  To fix it, this PR makes sure that __aexit__ is defined for the mock to simulate the full async context manager protocol.

[Confluence] Fix flaky test case

---

config.yml.example
connectors/config.py
connectors/es/index.py
connectors/protocol/connectors.py
connectors/utils.py
tests/test_utils.py

This PR attempt to do the following things:
- Add `elasticsearch.feature_use_connectors_api` config option that turns of usage of connectors API if on. Turned off by default
- Use this feature flag to call Connectors API for connector health check function as a demonstration of implementation.
Some notes:
I went for the path of least resistance here keeping in mind that current design of classes and code is more ORM-style with `ESIndex` abstraction actually encapsulating calls to specific indices. With Connectors API it changes - instead of indices it _might_ work in future on the route basis, E.G. one class for calls to Connector endpoints, one class for calls to Connector Sync job endpoints and so on.
Decisions for the above can be done later, especially when Connectors API will be …

Implement feature flag for Elasticsearch API + use for connector heartbeat

---

connectors/sources/box.py
tests/sources/test_box.py

Following changes are included in this PR:
- Ensure end-signals are put to queue even if error is encountered, in all relevant places.

[Box] Fix end signal not enqueued

---

requirements/framework.txt

"Not allowed to access Non IPM folder" this error is fixed in the new version of Exchangelib, hence upgrading to the latest.
Due to issue in exchangelib, outlook connector was facing `Not allowed to access Non IPM folder` error. After upgrading to latest version of exchangelib, outlook connector is working fine.

[Outlook] Upgrade Exchangelib

---

connectors/sources/servicenow.py
tests/sources/test_servicenow.py

Following changes are included in this PR:
1. Ensure end-signals are put to queue even if error is encountered, in all relevant places. 
2. Set advanced_rules_enabled to True

[Servicenow] Fix end signal not enqueued

---

requirements/aarch64.txt
requirements/framework.txt
requirements/x86_64.txt

This resolves a `PyMySQL` CVE which was shipped only with the version installed on aarch64.

Use same aiomysql version on different platforms

---

connectors/protocol/connectors.py
connectors/services/job_scheduling.py
connectors/utils.py
tests/services/test_job_scheduling.py
tests/test_utils.py

- This PR ensures are timestamps of `last_access_control_sync_scheduled_at`, `last_incremental_sync_scheduled_at` and  `last_sync_scheduled_at` are written to ES index with explicit UTC timezone  `+00:00`
- Job scheduling service is adapted, all references to deprecated `utcnow()` are replaced with `now(timezone.utc)`, this forces the scheduling service to operate on timezoned datetime objects instead of naive system defaults
- See good explanation by Miguel: https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated 
- Added unit tests
- Manually tested, scheduled full, incremental and ac syncs, they were triggering correctly with 8.15 snapshot of the stack

[Job scheduling] Use UTC timezone with timestamps

---

connectors/protocol/connectors.py
tests/protocol/test_connectors.py

Followup to #2067. I realised that migrating from naive to offset aware timestamps for job scheduling might break existing connectors that had scheduling enabled and were using naive datatime (no tz info) representation. 
I tried this scenario, as expected after migrating to new offset aware logic the scheduling was broken ... I got a following error from a scheduler
```
File "/Users/jedr/connectors-python/connectors/services/job_scheduling.py", line 207, in _should_schedule
and last_sync_scheduled_at > last_wake_up_time
TypeError: can't compare offset-naive and offset-aware datetimes
```
The fix is to try to cast naive datetimes, to offset aware datetimes when reading `last_access_control_sync_scheduled_at`, `last_incremental_sync_scheduled_at` and  `last_sync_scheduled_at` from ES …

Migration for timezone aware timestamps

---

connectors/sources/mssql.py

Adding more logs in MSSQL connector.
Log File: https://drive.google.com/file/d/1Rnm-tMY-ECYv1JZpj3oP9SvMljZZRxjZ/view?usp=drive_link

[MSSQL] Add logs

---

connectors/sources/salesforce.py
tests/sources/test_salesforce.py

Capture `error_description` on token error from Salesforce.
The Salesforce connector does not handle the error_description field when a ClientResponseError is raised. This field can provide helpful information when debugging the connector.  This change captures this field, if available, and appends it to the exception message.

Saleforce client token generation error logging

---

connectors/sources/confluence.py
tests/sources/test_confluence.py

This will backport the following commits from main to 8.14:
- https://github.com/elastic/connectors/pull/2602

[8.14] [Confluence] Ingest full body of documents in sync rules (#2602)

---

.buildkite/release-pipeline.yml

This PR fixes the release pipeline we will use soon to release a new version: env variables are not replaced in `artifact_paths` values.
* https://github.com/elastic/connectors/pull/2399

Fix glob in artifact_paths steps for release

---

connectors/protocol/connectors.py
connectors/sync_job_runner.py
tests/protocol/test_connectors.py
tests/test_sync_job_runner.py

If a connector thinks a job is running for it, we'd better ensure that a job either starts or fails. Before this PR, if `sync_job.claim()` failed, the connector would not be informed that there was nothing running the job, and the job it expected to start running would never transition out of the pending state. This PR does a few things:
1. Ensures that after the connector record has been informed that the sync is starting, that everything past that is in a `try/except` block to handle any errors and fail the job.
2. wraps all SyncJob methods individually in `try/except` to ensure that any surfaced error messages are as actionable as possible
3. Adds tests
This PR does not yet address the root issue of the linked ticket, which is _why_ we're getting to a place where `claim()` is resulting …

Catch job claim failures, and result in job termination

---

connectors/protocol/connectors.py
connectors/sync_job_runner.py
tests/protocol/test_connectors.py
tests/test_sync_job_runner.py

- [Catch job claim failures, and result in job termination (#2606)](https://github.com/elastic/connectors/pull/2606)

[8.13] Catch job claim failures, and result in job termination (#2606)

---

.buildkite/release-pipeline.yml

`buildah` is failing to build a multi-arch image when the image is Wolfi-based:
> ERRO[0010] While applying layer: ApplyLayer stdout:  stderr: operation not permitted exit status 1
It's possible that a newer version of `buildah`, which we'll get via the newer `drivah` image, may fix the problem.
If this doesn't work, we can go back to the approach over here: https://github.com/elastic/connectors/pull/2622

Use latest drivah image for building multiarch images

---

connectors/es/index.py
connectors/protocol/connectors.py
tests/protocol/test_connectors.py

Next step after #2561
If the feature flag `feature_use_connectors_api` we call Connector APIs to update the filtering validation info and activate the filtering if valid.
- `PUT _connector/{connector_id}/_filtering/_validation` updates the draft validation info
- `PUT _connector/{connector_id}/_filtering/_activate` activates the draft

[Connector API] Validate and activate filtering with API call

---

requirements/framework.txt

This PR bumps the `elasticsearch` version to `8.14.0`, and `elastic-transport` version to `8.13.1` (There's no plan to release `8.14.0`)

Bump elasticsearch and elastic-transport versions

---

connectors/sources/confluence.py
tests/sources/fixtures/confluence/fixture.py
tests/sources/test_confluence.py

- Added missing fields for Creator/attribution, and Created date. 
- Last modified date is already available via the timestamp field. 
Note: There's a limitation for data center space objects, Author and Created date are not available in the API response.

[Confluence] Add Fields Author and Created Date

---

connectors/es/index.py
connectors/protocol/connectors.py
tests/protocol/test_connectors.py

Use [create sync job API ](https://www.elastic.co/guide/en/elasticsearch/reference/current/create-connector-sync-job-api.html) to create a scheduled sync job with a given type. 
This feature is behind a feature flag that is disabled by default.
- added unit tests
- tested e2e on all sync types

Create scheduled jobs with Connector APIs

---

connectors/es/index.py
connectors/protocol/connectors.py
tests/protocol/test_connectors.py

Use [claim sync job API](https://github.com/elastic/elasticsearch/pull/109480) to claim a sync job at the beginning of the sync.
This feature is behind a feature flag that is disabled by default.
- added unit tests
- tested e2e on all sync types

Claim sync jobs with Connector APIs

---

README.md

Currently the build is passing, but the badge is red. I think this is because it's showing a union of all jobs, including feature branches
This magic url comes from https://buildkite.com/elastic/connectors/settings/badges

use buildkite image for main

---

tests/protocol/test_connectors.py

Example failures:
```
FAILED tests/protocol/test_connectors.py::test_create_job_with_connector_api[JobTriggerMethod.SCHEDULED-JobType.INCREMENTAL] - ValueError: Strict mode enabled, variables $elasticsearch.password are not defined!
--
  | FAILED tests/protocol/test_connectors.py::test_create_job_with_connector_api[JobTriggerMethod.ON_DEMAND-JobType.FULL] - ValueError: Strict mode enabled, variables $elasticsearch.password are not defined!
```
It happens because the tests are not using `set_env` fixture - original configuration file that's used for these tests does not have actual elasticsearch configuration definitions, it uses variables. These variables are populated from ENV.
Sometimes these tests pass because previous tests already defined these environment variables. To avoid these …

Add set_env to tests that init elasticsearch client

---

scripts/stack/README.md

There's a regression in curl prior to 8.7.1 (https://www.github.com/curl/curl/issues/13170) that can make stack scripts fail to launch Kibana.
This just adds a version requirement and an explanation about the existence of the regression.

Update stack scripts README

---

connectors/sources/s3.py

There is a security concern with the AWS library `aiobotocore` which is being called via the logs in S3 connector. This PR aims to remove those logs.
~- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)~

[Amazon S3] Remove security concerned logs

---

connectors/es/index.py
connectors/protocol/connectors.py
tests/protocol/test_connectors.py

Use [update stats api](https://www.elastic.co/guide/en/elasticsearch/reference/master/set-connector-sync-job-stats-api.html) to update connector sync job ingestion stats.
Note we don't need to provide `last_seen` as server will update it automatically to current UTC timestamp. 
This feature is behind a feature flag that is disabled by default.
- added unit tests
- tested e2e on all sync types

Use Connector APIs to update sync job stats

---

connectors/connectors_cli.py
connectors/es/sink.py
connectors/sync_job_runner.py
tests/test_sink.py
tests/test_sync_job_runner.py

We've been having an issue with the GCS ftest taking > 10 minutes. Digging with @artem-shelkovnikov today, we found that there was a sync that received a SIGINT, and acted like it was stopping/cleaning up (printed job counters and everything) but the extractor clearly kept going. Digging further, we found a logical error, where the SyncOrchestrator's tasks were only being canceled if there was an "error" in the job.
This change instead makes sure that `orchestrator.close()` always cancels the tasks if they are still running. It also makes sure that the SyncJobRunner's `_sync_done()` function always calls `orchestrator.cancel()`. There is no risk in calling `cancel()` multiple times.
Fixes a bug where the framework might receive an interrupt, but not terminate all running sync job tasks …

Ensure orchestrator tasks are always canceled

---

requirements/aarch64.txt
requirements/framework.txt
requirements/ftest.txt
requirements/x86_64.txt
tests/sources/test_s3.py

Snyk flagged a race condition:
```
Introduced through aioboto3@10.3.0
Fixed in aiobotocore@2.9.1
```
This PR bumps our `aioboto3` dep to give us:
```
Name: aiobotocore
Version: 2.12.3
``` 
I also took the opportunity to move this dep into `requirements/framework.txt` since we don't support any architecture that doesn't include this, so having it separate files felt redundant.
The upgrade caused one test failure, where an `aioboto.exceptions.ClientError` was raised instead of an `aioboto.exceptions.HTTPClientError`. I think that's likely ok, as the S3 connector doesn't have any reliance on `HTTPClientError`, so this only broke the test, but not the connector itself.

Bump aioboto

---

.buildkite/nightly_docker.yml
.buildkite/publish/publish-common.sh
.buildkite/release-pipeline.yml

With 8.14 we published two image flavours:
* `docker.elastic.co/enterprise-search/elastic-connectors` (based on Debian)
* `docker.elastic.co/enterprise-search/elastic-connectors-wolfi` (based on Wolfi)
Only `docker.elastic.co/enterprise-search/elastic-connectors` (based on Wolfi) will be published from 8.15.

Build and publish Wolfi-based images only

---

connectors/cli/connector.py

We introduced `manage_connector` privilege in ES: https://github.com/elastic/elasticsearch/pull/110128
Let's use it for new generated API keys for connectors.
See Kibana PR for reference with similar change: https://github.com/elastic/kibana/pull/187361
This is not backward compatible, since the new privilege is introduced in 8.15. Hence CLI won't work with <8.15 ES versions

Include `manage_connector` privilege in generated api keys

---

connectors/es/sink.py
tests/test_sink.py

Fixes a bug where `task.name` is not a thing, but my previous usage of mocks in the spec covered up the AttributeError
* first fixed in https://github.com/elastic/connectors/pull/2671/files#diff-68c31d9379d91378705cf6d47c447185e8c6ad952876c7a5fb979e3c89646148R914, but that might be a minute before merged, so putting this up separately.

Replace task.name with task.get_name()

---

connectors/logger.py
tests/test_logger.py

I noticed log lines like:
```
[FMWK][14:25:44][DEBUG] [job_scheduling_service] Scheduler woke up at 2024-07-09 19:25:44.085357+00:00.
```
notice that the logging framework timestamp is `14:25:44` (my local time) but the connectors logic understands that the time should be reasoned about in UTC (`19:25:44`). 
This discrepancy makes it hard to get scheduling right. If I just look at the _majority_ of timestamps that I see in the logs, I'd assume that the scheduling logic should use my local time, and not UTC time.
This PR fixes the issue by overwriting `logging.Formatter.format_time()` for our Formatter class.
It also simplifies the logic for changing the style depending on log level so that function overwrites work. 
Connector logs now use UTC timestamps, instead of machine-local …

log in utc

---

scripts/stack/docker/docker-compose.yml
scripts/stack/run-stack.sh

The stack scripts `script/stack/run-stack.sh` was using a generated network called `connectors_stack_net` (which would finalize as `docker_connectors_stack_net`) whenever the script was run.
In [Elasticsearch](https://github.com/elastic/elasticsearch) and [Connectors](https://github.com/elastic/connectors/blob/34efbe579e65eba89f70b3e3f1228e6ade0cb26f/docs/DOCKER.md#5-run-the-docker-image) documentation, we always specify to use the docker network `elastic`. This change updates the stack scripts docker compose to use the `elastic` network.
Because users may be following manual steps from other documentation, we can't rely on creating the network in the docker-compose file. Instead, we must assume the network was already created (the flag `external: true`). Without this flag, the docker …

Change docker-compose network in stack scripts to `elastic`

---

tests/test_content_extraction.py

Improve test coverage so we can get the baseline a bit above 92%.
This should improve content_extraction.py coverage from 84% to 98%.

Improve test coverage for content_extraction.py

---

connectors/es/sink.py
tests/test_sink.py

The output log for a failed bulk operation item doesn't include the ID of the document, so there's no actions a user can take to remedy the problem.
This adds the `_id` to the error log when an item in the bulk indexing fails.

Add _id to failed bulk logs

---

requirements/framework.txt

This PR updates `msal` to latest version to fix potential security vulnarability.

Bump msal to 1.30.0

---

Makefile

Follow up for https://github.com/elastic/connectors/pull/2734#pullrequestreview-2238470095:
This was not a backwards-compatible change, and it did not work well for me when I was testing - `python` alias always led to system Python.
But it looks, like it just _should_. If CI is green, then I was wrong and we can safely keep the old `python3` command work - `python3` should be correctly handled by `pyenv`
Some context on `python` vs `python3`: https://stackoverflow.com/questions/67550189/i-dont-have-python-but-i-have-python3
> Recent Ubuntu versions do not install python 2 by default, as python 2 is now "dead". However, the command `python` is not (yet) linked to Python 3, to avoid some confusion; traditionally, `python` was for python 2 while `python3` was for python 3.

Revert default python to python3

---

requirements/framework.txt

Part of https://github.com/elastic/search-team/issues/7689
This PR bumps the elasticsearch version to 8.15.0, and elastic-transport version to 8.15.0

Bump elasticsearch and elastic-transport packages to 8.15

---

Makefile
pytest.ini

The far-reaching goal of current work is to be able to have libraries separate from executables - for simplicity and maintenance, but also to be able to distribute executables separately. Unlikely that running connectors natively would need CLIs, or running connectors on agent would need a native connectors service.
This PR just starts the process by removing deprecated call to `python setup.py develop` and replacing it with `pip install --editable .`. This breaks tests as they do not know where to get the actual package code, so a change to `pytest.ini` was done.

Replace python setup.py develop with pip install --editable .

---

Dockerfile.ftest
Dockerfile.ftest.wolfi
Makefile
tests/sources/fixtures/box/docker-compose.yml
tests/sources/fixtures/confluence/docker-compose.yml
tests/sources/fixtures/dropbox/docker-compose.yml
tests/sources/fixtures/github/docker-compose.yml
tests/sources/fixtures/google_cloud_storage/docker-compose.yml
tests/sources/fixtures/google_drive/docker-compose.yml
tests/sources/fixtures/graphql/docker-compose.yml
tests/sources/fixtures/jira/docker-compose.yml
tests/sources/fixtures/microsoft_teams/docker-compose.yml
tests/sources/fixtures/notion/docker-compose.yml
tests/sources/fixtures/onedrive/docker-compose.yml
tests/sources/fixtures/salesforce/docker-compose.yml
tests/sources/fixtures/servicenow/docker-compose.yml
tests/sources/fixtures/sharepoint_online/docker-compose.yml
tests/sources/fixtures/sharepoint_server/docker-compose.yml
tests/sources/fixtures/zoom/docker-compose.yml

Just a minor bug: with PR before I've changed default venv location, didn't update in ftest dockerfiles :(

pip is now in .venv/bin

---

requirements/framework.txt

This attempts to address some issues from: https://github.com/elastic/connectors/issues/2309
Bumping this lib was suggested in the thread of aiohttp issue:  https://github.com/aio-libs/aiohttp/issues/4581#issuecomment-2307177212
make test 
triggered a sync locally

Bump `aiohttp` version to 3.10.4

---

.buildkite/pipeline.yml
.buildkite/publish/dra/init_dra_publishing.sh
.buildkite/publish/test-docker.sh
catalog-info.yaml

https://github.com/elastic/connectors/pull/2765 merged but didn't pass on main, because the docker tests expected an older file structure that changed earlier this week.
This also adds the ability to add `ci:packaging` to run everything except for the DRA publishing from branches other than `main` and `x.y` maintenance branches

Fix docker test, and add label hack for running packaging from PRs

---

.buildkite/publish/dra/init_dra_publishing.sh

I noticed that our artifact CSV was just:
```
"Name","Version","License","URL"
```
Because this job doesn't run `make install` first. So this ensures that it does, and also adds `clean` in case we ever add anything else earlier in this job (we don't want to ship with test deps in the CSV)
Related PR: https://github.com/elastic/connectors/pull/2757/files

Ensure required python libs are installed before generating csv

---

.buildkite/publish/dra/init_dra_publishing.sh

related to https://github.com/elastic/infra/pull/41445
Alpar let me know that the convention for docker is `amd64` not `x86_64`. I'd copied from a project that needs to be updated. Better for us to just do things the right way to start with.

Change back to amd64 instead of x86_64

---

.buildkite/publish/dra/init_dra_publishing.sh

`clean` removes `dist/` which destroyed all the artifacts we'd staged 🤦

Clean was a mistake

---

connectors/services/job_cleanup.py

All other services do this.
Rationale:
If the service is interrupted it should stop doing whatever it's doing and quit.
It can happen due to asynchronous nature that the service is stopped right before the `await self._sleeps.sleep(self.idling)` is called. What happens is:
1. `self.running` is set to false
2. `self._sleeps.cancel` is called
But CancellableSleeps class allows adding new sleeps after cancellation happens, so service is not running but it will still sleep one last time before exiting. For job cleanup service this sleep will be 5 minutes by default, thus graceful cancellation will just hang for 5 minutes cause of it.
This change is just to "make it work" - we need to think about making CancellableSleeps not accept any more sleeps if cancelled.

Make job cleanup service not sleep if it's not running any more

---

Makefile
scripts/deps-csv.py

@alpar-t flagged that the current csv structure is causing downstream issues because it doesn't meet their format requirements. TIL!
This PR adds a post-processing script to parse the output of `pip-licenses` to reorder the columns to match requirements.
It also uses "minimal quoting" as apparently having quotes in the header row was causing issues too.
Old output:
```
"Name","Version","License","URL"
"PyJWT","2.9.0","MIT License","https://github.com/jpadilla/pyjwt"
...
```
New output:
```
name,url,version,revision,license,sourceURL
PyJWT,https://github.com/jpadilla/pyjwt,2.9.0,,MIT License,
...
```
This leaves `revision` and `sourceURL` empty, which Alpar says is ok.
CSV was added in: https://github.com/elastic/connectors/pull/2757

Post-process deps-csv to meet DRA needs

---

Makefile
connectors/agent/cli.py
connectors/agent/component.py
connectors/agent/config.py
connectors/agent/protocol.py
connectors/agent/service_manager.py
connectors/config.py
requirements/agent.txt
requirements/framework.txt
requirements/ftest.txt
setup.py
tests/agent/test_agent_config.py
tests/agent/test_cli.py
tests/agent/test_component.py
tests/agent/test_protocol.py
tests/agent/test_service_manager.py

This PR adds a way to run Connectors Service in Agent.
Entry point is `connectors/agent/cli.py` - if it's ran from an Agent component via the python in `.venv/bin/python` it will enable Connector Service running within an Agent (docker or not).
This PR adds bare bone logic: positive cases work, so expect tricky bugs to still be out there if we haven't accounted for anything.
I've tried to keep it very small, and I think there's no way to make it simpler/smaller :)
Additionally - I had to exclude tests for the component from `make test` because it would break `make test` for people who have no access to the python agent client repository - this one will be opened later so we can revert this part of the changeset. If you need to run tests there is a make target `make test-agent` - I kept …

Add code for running connectors in Agent

---

connectors/sources/postgresql.py

Removed sorting for primary keys that allowed the connector to start syncing.
Removes sorting for the primary keys

[Postgres] Removed sorting for primary keys

---

docs/DOCKER.md

I’ve been checking Discuss forums and noticed a recurring issue: the lack of documentation around running connectors with Docker against a local Elastic Stack (started with [docker-compose.yml](https://github.com/elastic/elasticsearch/blob/8.15/docs/reference/setup/install/docker/docker-compose.yml)). This starts ES with security enabled and uses a self-signed certificate stored in a docker volume. Getting the connector docker command and service config to work with this setup requires some effort. See discuss threads: [ES PostgreSQL connector](https://discuss.elastic.co/t/es-postgresql-connector/365853/3), [Azure Blob Storage connector](https://discuss.elastic.co/t/azure-blob-storage-connector/360400/3), [PostgreSQL Connector unable to connect to elasticsearch …

[Docs] Add tip about self-signed certificate

---

connectors/sync_job_runner.py
tests/test_sync_job_runner.py

For Elastic-managed connectors in agentless we need to disable connector secrets on a service-level. 
I added new "internal" option `_use_native_connector_api_keys` that **is not documented** in `config.py` , similar to how we handle the `_force_allow_native` flag in: https://github.com/elastic/connectors/blob/4e97330803087151952debbdfa35408ff240666d/connectors/preflight_check.py#L192
Let me know if this approach work for you!
I ran the setup e2e and verified that this allows native connectors to run without connector secrets. If flag is not provided to service config the logic defaults it to `True` which is backward compatible option.

Config option to disable connector secrets for native connectors

---

.coveragerc
connectors/agent/__init__.py
connectors/cli/__init__.py

```
make clean install-agent
.venv/bin/elastic-agent-connectors
```
would work from source, but not from the sdist, because `setup.py` was only packaging source code that it could "discover".
I hate python

Add missing __init__.py files

---

.coveragerc
Dockerfile.ftest.wolfi
Dockerfile.wolfi
connectors/agent/__init__.py
connectors/cli/__init__.py
connectors/es/management_client.py
connectors/es/sink.py
connectors/sources/__init__.py
connectors/sync_job_runner.py
tests/agent/test_cli.py
tests/es/test_management_client.py
tests/test_sink.py
tests/test_sync_job_runner.py

Main is still on 8.16, as https://github.com/elastic/connectors/pull/2800 has not yet been able to build. But DRAs for 8.16 are being built now from 8.x branches, not main branches. We need to backport everything. 
I'm going to mass-backport this, then set up main to auto-backport to 8.x until we can merge the 9.0 version bump PR.

Mass backport into 8.x branch

---

requirements/framework.txt

CI started failing overnight.
This happened because of release of `pyasn1` `0.6.1` version: https://github.com/pyasn1/pyasn1/pull/75/files. Runtime deprecation happened that affected other libraries that use this package - we only use `pyasn1` as a transitive dependency.
This PR enforces usage of previous version for now until the libraries that we use ever support new version.

Forcefully downgrade pyasn1 to 0.6.0

---

.buildkite/nightly_steps.yml
.buildkite/pipeline.yml

Adding retries to our buildkite pipelines:
- commit/main
- Nightly
For now we'll retry 2 times for signals -1, 255 and 2.
See https://buildkite.com/blog/retrying-ci-cd-steps-when-spot-instances-terminate for docs

Add retry for on-commit and nightly pipelines

---

.buildkite/publish/build-docker.sh
.buildkite/publish/build-multiarch-docker.sh
.buildkite/publish/git-setup.sh
.buildkite/publish/manual-release/restore-stack-version.sh
.buildkite/publish/manual-release/update-release-version.sh
.buildkite/publish/publish-common.sh
.buildkite/publish/push-docker.sh
.buildkite/publish/test-docker.sh
.buildkite/publish_docker.sh
.buildkite/release-pipeline.yml
.coveragerc
.gitignore
catalog-info.yaml
connectors/preflight_check.py
docs/RELEASING.md
tests/test_preflight_check.py

This PR does a few things.
1. Adds back the scripts that used to exist for triggering a manual release
2. Introduces a `MANUAL_RELEASE` env var (through the pipeline) that gates some special versioning logic
3. That logic (in `publish-common.sh`) will re-compute the VERSION by going to the most recent patch version, and adding a `+build<timestamp>` suffix (this matches the pattern that Agent is establishing)
4. The pipeline adds a setup and a cleanup group, which actually commit the VERSION file change and create a git tag on that commit. This ensures that the docker tag, git tag, and `bin/elastic-ingest --version` all are in agreement.
5. every part of this pipeline is gated, and can only be run off of `X.Y` branches (not `main`, not other dev branches)
* …

add back release pipeline

---

Makefile
connectors/agent/config.py
tests/agent/test_agent_config.py

Bundles two changes:
- Makes it possible to run the component with fleet. This is achieved by base64 encoding the api key if it's received in a format "a:b"
- Set `service._use_native_connector_api_keys` to `False` to make the service run without using native api keys and use agent/fleet api key instead

Minor fixes for agent component

---

connectors/sources/network_drive.py
tests/sources/test_network_drive.py

Network Drive connector is currently indexing the access control docs (user docs) with group ids and causes duplicate ids for documents within that group. So, this PR now assigning the user id instead of group id.
Fixing the overwriting issue for access control docs.

[Network Drive] fix duplicate ids in access control sync

---

connectors/sources/network_drive.py
tests/sources/test_network_drive.py

This will backport the following commits from main to 8.15:
- https://github.com/elastic/connectors/pull/2832

[8.15][Network Drive] fix duplicate ids in access control sync #2832

---

connectors/agent/protocol.py
tests/agent/test_protocol.py

Mostly improvements around handling output units, this PR explicitly assumes that:
- We are only dealing with `elasticsearch` output types, see supported output types, see docs https://www.elastic.co/guide/en/fleet/current/elastic-agent-output-configuration.html
- We are only sending data to the first output unit of elasticsearch type, if there are multiple ES outputs in the agent policy a warning is logged
- Works locally 🤌 
- Unit tests

[Agent] Improvements to agents protocol handler

---

connectors/sources/confluence.py
tests/sources/test_confluence.py

- [[Confluence] Update logs (#2526)](https://github.com/elastic/connectors/pull/2526)

[8.x] [Confluence] Update logs (#2526)

---

connectors/agent/component.py
connectors/agent/config.py
connectors/agent/connector_record_manager.py
connectors/agent/protocol.py
connectors/es/index.py
connectors/protocol/connectors.py
docs/CONFIG.md
tests/agent/test_agent_config.py
tests/agent/test_connector_record_manager.py
tests/agent/test_protocol.py

This change introduces the `ConnectorRecordManager`, which ensures that connectors associated with a given agent are created on startup using the `ensure_connector_records_exist` function.
The check-in handler has been updated to inspect both input and output units passed to the component from the agent protocol. The assumption is that each connector component will receive no more than one output of type ES and one input of type `connectors-py`. I've added logging and additional logic to detect and handle edge cases.
If more then one connector component is defined in the policy user will see a log: `Multiple connector inputs detected. The first connector input defined in the agent policy will be used.` 
> [!NOTE]  
> We could change this and allow adding multiple connector inputs to the …

Create connector record in agent component

---

connectors/utils.py

error messages like:
```
Exception found for task Extractor download #946:
```
Are not particularly helpful. When we log exceptions, we should include the full stack trace, if we're not re-raising the error.

include full stack trace in concurrent exception

---

Dockerfile
Dockerfile.ftest

More details in the issue, but TLDR because we were missing git in non-Wolfi Dockerfiles building the local docker image and running ftests was failing
This PR fixed both scenarios, verified manually:
- building local image with non-wolfi image
- running ftest with non-wolfi image

[Docker] Add git so that non-wolfi images are usable

---

Dockerfile
Dockerfile.wolfi
Makefile

This PR makes a symlink from `/app/.venv/bin` to `/app/bin` to preserve old logic of running the app from `/app/bin/elastic-ingest`. Otherwise they'd have to run it with `/app/.venv/bin/elastic-ingest` and it feels getting out of hand. Documentation still points to `/app/bin/elatic-ingest`, so let's just symlink it!

Docker: make a symlink to maintain backwards-compatibility after venv change, update makefile to build with --no-cache

---

.backportrc.json

We've got 8.16 branch, but tagging PR as `8.16.0` will still point to `8.x` branch - now `8.17.0` needs to point to `8.x`

Update backportrc to alias 8.17.0 -> 8.x and dealias 8.16.0

---

connectors/es/sink.py

I hit an error:
```
[FMWK][15:19:19][INFO] [Connector id: confluence, index name: search-confluence, Sync job id: LwAtoJIB52ZH8QDRudeD] Task is canceled, stop Extractor...
--
  | 2024-10-18 15:19:19 UTC | Exception in callback SyncOrchestrator.extractor_task_callback()(<Task cancell.../sink.py:486>>)
  | 2024-10-18 15:19:19 UTC | handle: <Handle SyncOrchestrator.extractor_task_callback()(<Task cancell.../sink.py:486>>)>
  | 2024-10-18 15:19:19 UTC | Traceback (most recent call last):
  | 2024-10-18 15:19:19 UTC | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1729263632898151260/elastic/connectors/connectors/es/sink.py", line 587, in get_docs
  | 2024-10-18 15:19:19 UTC | await lazy_downloads.put(
  | 2024-10-18 15:19:19 UTC | File …
```

Check for task cancelation before fetching exception

---

config.yml.example
connectors/config.py
connectors/es/client.py
docs/DOCKER.md

Updated the verification logic for server certificates to allow for configurable settings. The `verify_certs` option now defaults to `True` but can be set to `False` in the configuration. This change enhances flexibility, allowing users to opt out of certificate verification in environments with varying security requirements.

Allow Insecure HTTPS 

---

connectors/es/sink.py
connectors/protocol/connectors.py
connectors/services/job_cleanup.py
connectors/services/job_execution.py
connectors/services/job_scheduling.py

Related to https://github.com/elastic/connectors/pull/2916, which reminded me that this has been annoying for a while. We should only use CRITICAL when the process is imminently crashing. Sync errors are not "CRITICAL".

Removes gratuitous 'critical' logging

---

connectors/agent/connector_record_manager.py
connectors/es/index.py
connectors/protocol/connectors.py
connectors/utils.py
tests/agent/test_connector_record_manager.py
tests/protocol/test_connectors.py

Addressed items:
- added debug logs in connector record manager
- moved `connector_exists` to ConnectorIndex class
- moved `generate_random_id` to utils class
- adapted tests

Followup on #2861

---

Makefile
NOTICE.txt
requirements/framework.txt

Bump `pyOpenSSL` to latest version, this in turns updates `cryptography` (our transitive dependency) as Snyk was complaining about our `cryptography` version. 
+ regenerate `Notice.txt` file, seems like it was not updated in a while
Relates to [CVE-2024-6119](https://www.cve.org/CVERecord?id=CVE-2024-6119)

Bump pyOpenSSL lib version

---

catalog-info.yaml

I broke terrazo 🙈 see: https://github.com/elastic/connectors/pull/2951#issuecomment-2471635528

use quotes on 8.16 version in catalog-info.yml

---

Dockerfile
Dockerfile.ftest

Without the `-y` params, `docker build` can fail when confronted with an interactive `apt` prompt:
> Do you want to continue? [Y/n] Abort.
> ERROR: failed to solve: process "/bin/sh -c apt update && apt upgrade && apt install make git -y" did not complete successfully: exit code: 1

Fix `apt` invocations in `Dockerfile`s

---

.buildkite/release-pipeline.yml
docs/RELEASING.md

Related to https://elasticco.atlassian.net/browse/ENGPRD-829
Our "in between" release process has been broken since Elastic made org-wide changes to our github rulesets, requiring PRs for commits made to maintenance branches. 
This therefore adjusts the formal description of the process to explain how a dev branch can be used. It also removes the branch gating for the buildkite build.

Adjusting inbetween release process to use dev branches

---

scripts/stack/run-stack.sh
scripts/stack/update-kibana-user-password.sh

I noticed that `script/stack/start-stack.sh` wasn't working. It would wait for kibana indefinitely, and if you checked kibana logs, you'd see auth errors because kibana_system didn't have the right credentials.
Two problems:
- we were not setting the kibana_system password until _after_ kibana was supposed to have started up
- we were trying to source some `read-env.sh` script that doesn't exist.
IDK how this ever worked, or what broke it. But this makes things start up as expected, now.

Make local stack scripts work

---

connectors/sources/outlook.py
tests/sources/test_outlook.py

A failure in the outlook connector was reported with a stack trace like:
```
File "/workspaces/elastic_connectors/connectors/es/sink.py", line 487, in run
await self.get_docs(generator)
File "/workspaces/elastic_connectors/connectors/es/sink.py", line 539, in get_docs
async for count, doc in aenumerate(generator):
File "/workspaces/elastic_connectors/connectors/utils.py", line 856, in aenumerate
async for elem in asequence:
File "/workspaces/elastic_connectors/connectors/logger.py", line 247, in __anext__
return await self.gen.__anext__()
File "/workspaces/elastic_connectors/connectors/es/sink.py", line 521, in _decorate_with_metrics_span
async for doc in generator:
File "/workspaces/elastic_connectors/connectors/sync_job_runner.py", line 454, in …
```

[outlook] Filter users to only include active ones

---

tests/ftest.sh
tests/sources/fixtures/azure_blob_storage/docker-compose.yml
tests/sources/fixtures/box/docker-compose.yml
tests/sources/fixtures/confluence/docker-compose.yml
tests/sources/fixtures/dir/docker-compose.yml
tests/sources/fixtures/dropbox/docker-compose.yml
tests/sources/fixtures/fixture.py
tests/sources/fixtures/github/docker-compose.yml
tests/sources/fixtures/google_cloud_storage/docker-compose.yml
tests/sources/fixtures/google_drive/docker-compose.yml
tests/sources/fixtures/graphql/docker-compose.yml
tests/sources/fixtures/jira/docker-compose.yml
tests/sources/fixtures/microsoft_teams/docker-compose.yml
tests/sources/fixtures/mongodb/docker-compose.yml
tests/sources/fixtures/mongodb_serverless/docker-compose.yml
tests/sources/fixtures/mssql/docker-compose.yml
tests/sources/fixtures/mysql/docker-compose.yml
tests/sources/fixtures/network_drive/docker-compose.yml
tests/sources/fixtures/notion/docker-compose.yml
tests/sources/fixtures/onedrive/docker-compose.yml
tests/sources/fixtures/oracle/docker-compose.yml
tests/sources/fixtures/postgresql/docker-compose.yml
tests/sources/fixtures/redis/docker-compose.yml
tests/sources/fixtures/s3/docker-compose.yml
tests/sources/fixtures/salesforce/docker-compose.yml
tests/sources/fixtures/servicenow/docker-compose.yml
tests/sources/fixtures/sharepoint_online/docker-compose.yml
tests/sources/fixtures/sharepoint_server/docker-compose.yml
tests/sources/fixtures/zoom/docker-compose.yml

- [[Publishing] Load ES image for ftest from DRA artifact (#2979)](https://github.com/elastic/connectors/pull/2979)

[8.x] [Publishing] Load ES image for ftest from DRA artifact (#2979)

---

tests/ftest.sh

I noticed in buildkite some sporadic errors when downloading the image tarball, let's add retries to make our pipeline stable:
Exampel of error (buildkite retried and it passed)
```
+ TAR_FILE=elasticsearch-9.0.0-SNAPSHOT-docker-image.tar.gz
--
  | + echo 'Downloading Docker image tarball from https://artifacts-snapshot.elastic.co/elasticsearch/9.0.0-925206fd/downloads/elasticsearch/elasticsearch-9.0.0-SNAPSHOT-docker-image.tar.gz...'
  | Downloading Docker image tarball from https://artifacts-snapshot.elastic.co/elasticsearch/9.0.0-925206fd/downloads/elasticsearch/elasticsearch-9.0.0-SNAPSHOT-docker-image.tar.gz...
  | + curl -O https://artifacts-snapshot.elastic.co/elasticsearch/9.0.0-925206fd/downloads/elasticsearch/elasticsearch-9.0.0-SNAPSHOT-docker-image.tar.gz
  | % Total    % …
```

[CI] Add retries when fetching DRA artifacts

---

connectors/sources/confluence.py

Minor change to replace unsafe object field access with safe one - we've received reports with errors coming from these lines because some intermediate objects were None:
```
File "/app/connectors/sources/confluence.py", line 1154, in _page_blog_coro
async for document, attachment_count, space_key, permissions, restrictions in self.fetch_documents(
File "/app/connectors/sources/confluence.py", line 904, in fetch_documents
"author": document["history"]["createdBy"][self.authorkey],
KeyError: 'publicName'
[FMWK][18:00:15][ERROR] Exception found for task Task-132
File "/app/connectors/sources/confluence.py", line 1154, in _page_blog_coro
async for document, attachment_count, space_key, permissions, restrictions in …
```

Change dto for page blog documents to access fields in safe manner

---

.backportrc.json
.buildkite/pipeline.yml

- [Update for 8.17 FF (#2994)](https://github.com/elastic/connectors/pull/2994)

[8.17] Update for 8.17 FF (#2994)

---

requirements/framework.txt

Response to https://github.com/elastic/search-team/issues/8737:
Upgrading `aiohttp` to latest.

Upgrade aiohttp to 3.11.7

---

connectors/es/sink.py
tests/test_sink.py

Always stringify `doc["id"]` field. The default index mappings were removed in https://github.com/elastic/connectors/pull/3013. 
This limits the scenario of running into weird issues with ES mappings for numeric-like ID fields (overflows, etc). ID should be keyword never numeric ideally.

Stringify doc[id] field

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bed0cbf (#3006)](https://github.com/elastic/connectors/pull/3006)

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bed0cbf (#3006)

---

connectors/es/sink.py
connectors/utils.py
tests/test_sink.py

We were ensuring that the ingested `doc[id]` was a string, but at the time we computed:
```
if doc_id in existing_ids:
```
`doc_id` could be numeric, but `existing_ids` were guaranteed to be strings.
Fixes a bug where full syncs may delete documents they just ingested if the document ID when fetched from the 3rd party was numeric.

also cast doc_id to str

---

connectors/es/sink.py
connectors/utils.py
tests/test_sink.py

- [also cast doc_id to str (#3031)](https://github.com/elastic/connectors/pull/3031)

[8.16] also cast doc_id to str (#3031)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

Manual backport of https://github.com/elastic/connectors/pull/3024

Manually bump dockerfiles in 8.17

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

Manual backport of https://github.com/elastic/connectors/pull/3024

Manually bump dockerfiles in 8.x

---

requirements/framework.txt

- [Update aiohttp to latest (#3040)](https://github.com/elastic/connectors/pull/3040)

[8.17] Update aiohttp to latest (#3040)

---

connectors/sources/mysql.py

BUG: When configuring the advanced sync rule for the MySQL connector, the sync action throws an error: 'MySQLClient.yield_rows_for_query() missing 1 required positional argument: 'primary_key_columns''.
Root Cause: The yield_rows_for_query method is called without the required primary_key_columns parameter.
Fix: Add the missing primary_key_columns parameter when calling the yield_rows_for_query method.

Fix mysql advanced sync rule execute error

---

config.yml.example
connectors/config.py
connectors/es/client.py
docs/DOCKER.md

- [Allow Insecure HTTPS  (#2913)](https://github.com/elastic/connectors/pull/2913)

[8.x] Allow Insecure HTTPS  (#2913)

---

NOTICE.txt
requirements/framework.txt

- [Update elasticsearch client to 8.17 (#3033)](https://github.com/elastic/connectors/pull/3033)

[8.x] Update elasticsearch client to 8.17 (#3033)

---

connectors/protocol/connectors.py
connectors/services/job_scheduling.py
tests/commons.py
tests/services/test_job_scheduling.py

Currently connectors have no way to report they're connected.
This PR makes it so that if a data source succeeds in validation and ping, then its status is set to CONNECTED.
In practice it means, that a user who had problems with their setup will see an error in UI. If they fix the credentials, before the error would go away after a sync starts. After this change the error will disappear within the service poll interval from user's action.
Fix a UI issue with connector reporting problems with connection even if wrong configuration was fixed. Before the error would go away only when a sync is executed.

Set connector status to CONNECTED after successful validation and ping

---

Makefile

Minor improvement for local development: running `make` commands will not re-init your venv and dependencies any more unless it's really needed.
Before every time you ran a makefile command that has `config.yml` as a dependency, your whole venv gets reinitialised:
```
artemshelkovnikov-m2@Mac connectors-py % make lint
python3 -m venv .venv
.venv/bin/pip install --upgrade pip
... tons of stuff that reinstalls requirements.txt
```
This happened because of this dependency:
```
.venv/bin/python: config.yml
```
Running make in debug mode explains why:
```
Considering target file `lint'.
File `lint' does not exist.
Considering target file `.venv/bin/python'.
Considering target file `config.yml'.
Finished prerequisites of target file `config.yml'.
No need to remake target `config.yml'.
Finished …
```

Make config.yml an order dependency

---

requirements/agent.txt

Noticed a NOTICE.txt update in https://github.com/elastic/connectors/pull/3085 that should not have been there.
Happens because we use `python-elastic-agent-client` from `main` of the repo, not from PyPi, fixing this.

Use actual PyPi version of elastic-agent-client

---

.buildkite/run_linter.sh
.buildkite/run_notice_check.sh
.buildkite/shared.sh

See failure of CI in PR https://github.com/elastic/connectors/pull/3090: https://buildkite.com/elastic/connectors/builds/15589#01945040-19d0-4239-915a-173479f8aee8
```
++ git switch -
--
  | Warning: you are leaving 2 commits behind, not connected to
  | any of your branches:
  |  
  | 824f57b6 use rstrip for lists to remove whitespace
  | cf502ec0 remove '' as a space with trailing comma
  |  
  | If you want to keep them by creating a new branch, this may be a good time
  | to do so with:
  |  
  | git branch <new-branch-name> 824f57b6
  |  
  | Switched to branch 'main'
  | Your branch is up to date with 'origin/main'.
  | ++ git checkout meghanmurphy1:confluence-trailing-comma
  | error: pathspec 'meghanmurphy1:confluence-trailing-comma' did not match any file(s) known to git
  | 🚨 …
```

Avoid git commands when running against a fork

---

.buildkite/publish/dra/publish-daily-release-artifact.sh

It seems like we need to pass `--qualifier` to the release pipeline. Reading the cli implementation, I understand this is an optional arg ([source](https://github.com/elastic/infra/blob/19bde2ec72bb79075755ade7b5a14e6e85fd9267/cd/release/release-manager/docker-entrypoint.sh#L254)) so skipping checks for undefined.
If I understand correctly, we only ever populate this via manual trigger of release pipeline.

DRA release pipeline, pass qualifier to release cli

---

.backportrc.json
renovate.json

This PR enables auto-backport of Renovate PRs (when merged to `main`) to branches corresponding to currently open minor versions.

Auto-backport Renovate PRs

---

.buildkite/publish/dra/publish-daily-release-artifact.sh

Reverts elastic/connectors#3101
We've determined this doesn't resolve https://github.com/elastic/search-team/issues/9111, and it's breaking CI, so let's just take it out until we can revist.

Revert "DRA release pipeline, pass qualifier to release cli"

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 4ce83a8 (#3108)](https://github.com/elastic/connectors/pull/3108)

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 4ce83a8 (#3108)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 4ce83a8 (#3108)](https://github.com/elastic/connectors/pull/3108)

[8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 4ce83a8 (#3108)

---

.backportrc.json
docs/RELEASING.md

Updating release docs to include step for keeping `renovate.json` up to date as well.
* https://github.com/elastic/connectors/pull/3104

Add step to update Renovate config to release docs

---

connectors/source.py
connectors/sources/confluence.py
tests/test_source.py

A fix for when a trailing comma is used as part of 'Confluence space keys' when configuring a Confluence Connector.

Remove ' ' as a configured Confluence space when there's a trailing comma

---

.buildkite/pipeline.yml
.buildkite/publish/dra/init_dra_publishing.sh
.buildkite/publish/dra/publish-daily-release-artifact.sh
docs/RELEASING.md

This gives us the ability to specify a `VERSION_QUALIFIER` env var for a buildkite pipeline, and have that qualifier be picked up when producing staging artifacts. 
After this PR is merged, we will trigger a build on `main` with `VERSION_QUALIFIER=alpha1` to produce a 9.0.0-alpha1 pre-release for internal testing.

Enable basic DRA qualifiers

---

.buildkite/publish/dra/publish-daily-release-artifact.sh
docs/RELEASING.md

https://github.com/elastic/connectors/pull/3119 didn't add the qualifier to the artifacts, but still did pass the qualifier to the `release-manager` command. This lead to errors like:
```
2025-01-17 12:04:45 CST | FAILURE: Build failed with an exception.
-- | --
  | 2025-01-17 12:04:45 CST |  
  | 2025-01-17 12:04:45 CST | * What went wrong:
  | 2025-01-17 12:04:45 CST | Some problems were found with the configuration of task ':checksumConnectorsSnapshotSHA512' (type 'DefaultTask').
  | 2025-01-17 12:04:45 CST | - Property '$1' specifies file '/artifacts/dra-artifacts/connectors-9.0.0-alpha1-SNAPSHOT.zip' which doesn't exist.
  | 2025-01-17 12:04:45 CST |  
  | 2025-01-17 12:04:45 CST | Reason: An input file was expected to be present but it doesn't exist.
```
This change should prevent …

Fix SNAPSHOT workflow to not have VERSION_QUALIFIER

---

.buildkite/publish/dra/init_dra_publishing.sh
.buildkite/publish/dra/publish-daily-release-artifact.sh

Turns out that when you `source somescript.sh` instead of `./somescript.sh`, overrides of exported variables propagate up, instead of staying local to their assignment. So https://github.com/elastic/connectors/pull/3123/files ended up overwriting `VERSION_QUALIFIER` for both snapshot AND staging workflows. 🤦 
This instead swithces `publish-daily-release-artifact.sh` to use it's own local variable of `version_qualifier`, rather than overwriting the provided value of `VERSION_QUALIFIER`.

version qualifier fixes

---

renovate.json

Our correct backport labels contain patch versions.
Additionally adding v8.18.0 to backport to `8.x` branch too.

Update renovate labels

---

NOTICE.txt
requirements/agent.txt

Using latest version of elastic-agent-client with more strict library requirements.
Came from https://github.com/elastic/connectors/pull/3134: `grpcio` and `grpcio-tools` should be of version `1.68.x`, 1.69.0 doesn't work due to uninvestigated compatibility issues.

Update elastic-agent-client to 0.0.1dev2

---

NOTICE.txt
connectors/es/index.py
connectors/protocol/connectors.py
requirements/framework.txt
tests/es/test_index.py

- [Updating ESApi class methods to use ES client calls instead of temporary wrapper methods (#3110)](https://github.com/elastic/connectors/pull/3110)

[8.x] Updating ESApi class methods to use ES client calls instead of temporary wrapper methods (#3110)

---

.buildkite/publish/publish-common.sh

Add hard-coded qualifier `beta1` so nightly builds have a qualifier. This will be removed when we release 9.0.

Add hardcoded qualifier

---

connectors/es/index.py
tests/es/test_index.py

https://github.com/elastic/connectors/pull/3110

Fix to ESApi connector_sync_job_update_stats() to ensure undefined metadata passed as {} when undefined

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

This fixes an issue where `Unclosed client session` and `Unclosed connector` messages were appearing in logs.
RCA:
aiohttp does not close its sessions, so when we create an Azure CertificateCredential, we need to manually call `.close()` on it, otherwise the client sessions will remain open.
See [this](https://github.com/Azure/azure-sdk-for-python/issues/13242#issuecomment-677857681) Azure Python SDK thread for details.

SharePoint Online Connector: Added credentials.close() call to _fetch_token() method

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

- [SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)](https://github.com/elastic/connectors/pull/3177)

[8.x] SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

- [SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)](https://github.com/elastic/connectors/pull/3177)

[8.18] SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)

---

connectors/sources/sharepoint_online.py
tests/sources/test_sharepoint_online.py

- [SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)](https://github.com/elastic/connectors/pull/3177)

[8.16] SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)

---

connectors/protocol/connectors.py
tests/protocol/test_connectors.py

Since we introduced soft-deletes in 9.0, make sure framework respects deleted flag. 
Exclude any connectors with `deleted: true` when fetching supported connectors in a query (note, I added this to native connectors query for conssitency but this code should be deleted anyway https://github.com/elastic/connectors/issues/2991)
This is in line with how API handles soft-deleted connectors https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/ConnectorIndexService.java#L410C12-L410C119
Ran this locally with debug log enabled with ES 9.0. Soft-deleted connector, and that was resulting output of the framework:
```
[content_sync_job_execution_service] There's no supported connectors found with native service types …
```

[Framework] Correctly handle soft deleted connectors

---

Makefile

Fix Makefile `elastic-ingest` target to force reinstall when requirements change. The `requirements/$(ARCH).txt` references  inside`requirements/framework.txt` the `framework.txt` was not listed as dependency of makefile target. Hence we were not reinstalling when framework-level dependency was updated.
That was triggering me for a while. With every new python version update the global alias of python3 is bumped (on MacOS at least with homebrew python), e.g. now `python3` has version 3.13 for me. 
This caused running `make clean && make run` always fail as connectors are not compatible with python 3.12+. As requirements will fail to install.
In order to address this issue, I added logic to:
- use `PYTHON=python3` as before (backward compatible for CI setup)
- check CI step that we use …

[Makefile] Improvements to python selection and requirement changes

---

connectors/es/__init__.py

This PR adds a warning filter to suppress the following warning from output:
`
GeneralAvailabilityWarning: This API is in technical preview and may be changed or removed in a future release. Elastic will work to fix any issues, but features in technical preview are not subject to the support SLA of official GA features. result = await func()`

Adding warning filter to suppress GA warning from ES Python client

---

connectors/es/__init__.py

- [Adding warning filter to suppress GA warning from ES Python client (#3189)](https://github.com/elastic/connectors/pull/3189)

[8.18] Adding warning filter to suppress GA warning from ES Python client (#3189)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to ff16db3 (#3194)](https://github.com/elastic/connectors/pull/3194)

[8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to ff16db3 (#3194)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to ff16db3 (#3194)](https://github.com/elastic/connectors/pull/3194)

[8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to ff16db3 (#3194)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)](https://github.com/elastic/connectors/pull/3203)

[8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)](https://github.com/elastic/connectors/pull/3203)

[8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)](https://github.com/elastic/connectors/pull/3203)

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)

---

README.md

- Removes mention of managed connectors
- Updates links accordingly, including the API docs 
> [!NOTE]
> URLs for the elasticsearch docs will be redirected when the new docs system goes live.

Update README.md for 9.0

---

.buildkite/publish/publish-common.sh

beta1 is out, so time to bump the qualifier, per the #mission-control thread

switch version qualifier to `rc1`

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)](https://github.com/elastic/connectors/pull/3227)

[8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)](https://github.com/elastic/connectors/pull/3227)

[8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)](https://github.com/elastic/connectors/pull/3227)

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)](https://github.com/elastic/connectors/pull/3241)

[8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)](https://github.com/elastic/connectors/pull/3241)

[8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)](https://github.com/elastic/connectors/pull/3241)

[8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)](https://github.com/elastic/connectors/pull/3283)

[9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)](https://github.com/elastic/connectors/pull/3283)

[8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)](https://github.com/elastic/connectors/pull/3283)

[8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)](https://github.com/elastic/connectors/pull/3283)

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)

---

NOTICE.txt
connectors/sources/azure_blob_storage.py

The Azure Blob Storage configuration for max concurrent downloads wasn't applying the configured option.

Fix ABS concurrent download configuration

---

Makefile

Removing `make release` command - we don't release the service, no need to have the command.

Remove make release command

---

.buildkite/publish/publish-common.sh
NOTICE.txt

Removes the qualifier for rc1, as requested by mission control

prep for 9.0.0 release

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)](https://github.com/elastic/connectors/pull/3319)

[8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)](https://github.com/elastic/connectors/pull/3319)

[8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)](https://github.com/elastic/connectors/pull/3319)

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)

---

NOTICE.txt
config.yml.example
connectors/config.py
connectors/services/job_scheduling.py
tests/services/test_job_scheduling.py

This PR introduces concurrent task to job scheduling service. Before, `_schedule` function would be awaited - now they are added to concurrent task pool (default size = 4) and are all awaited in the end of scheduling loop.
Result of this is that it's possible to properly stop job scheduling service when it's in the middle of `_schedule` function. Before this change, slow validation of the connector could result in service hanging - while validation is happening, it was impossible to stop the connectors service.

Make job_scheduling service run schedule in a task pool

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

[9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

[8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

[8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

[8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0863e59 (#3350)](https://github.com/elastic/connectors/pull/3350)

[9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0863e59 (#3350)

---

connectors/services/job_scheduling.py

Running 5 connectors locally can lead to the error in stdout:
```
[FMWK][15:07:12][ERROR] [job_scheduling_service] 'JobSchedulingService' object has no attribute 'display_name'
File "/Users/artemshelkovnikov-m2/git_tree/connectors-py/connectors/services/job_scheduling.py", line 184, in _run
f"Job Scheduling service is already running {self.max_concurrency} concurrent scheduling jobs and can't run more at this point. Increase 'max_concurrent_scheduling_tasks' in config if you want the service to run more concurrent scheduling jobs."  # pyright: ignore
^^^^^^^^^^^^^^^^^
AttributeError: 'JobSchedulingService' object has no attribute 'display_name'
```
Fixing it (code was copied wrongly from scheduling services)

Fix log line for when too many jobs are attempted to be scheduled

---

scripts/stack/copy-config.sh
scripts/stack/wait-for-elasticsearch.sh

handling ELASTIC_PASSWORD when running run-stack.sh

---

NOTICE.txt
connectors/services/job_scheduling.py

Minor fix: now with every loop of SchedulingService this log line is emitted making it look like this:
```
[FMWK][15:22:30][INFO] Running connector service version 8.17.3
[FMWK][15:22:30][INFO] Loading config from /Users/artemshelkovnikov-m2/git_tree/connectors-py/connectors/../config.yml
[FMWK][15:22:30][INFO] Running preflight checks
[FMWK][15:22:30][INFO] Waiting for Elasticsearch at https://a75ef4b880e04d68a4632538f7c2b3df.us-west2.gcp.elastic-cloud.com:443 (so far: 0 secs)
[FMWK][15:22:30][INFO] Elasticsearch 8.17.3 and Connectors 8.17.3 are compatible
[FMWK][15:22:30][INFO] Extraction service is not configured, skipping its preflight check.
[FMWK][15:22:31][INFO] [job_scheduling_service] Job Scheduling Service started, listening to events from …
```

Make Job Scheduling service emit debug log instead of info

---

NOTICE.txt
connectors/sources/github.py
tests/sources/test_github.py

- [Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)](https://github.com/elastic/connectors/pull/3358)

[9.0] Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)

---

NOTICE.txt
connectors/sources/github.py
tests/sources/test_github.py

- [Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)](https://github.com/elastic/connectors/pull/3358)

[8.18] Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)

---

NOTICE.txt
connectors/sources/github.py
tests/sources/test_github.py

- [Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)](https://github.com/elastic/connectors/pull/3358)

[8.17] Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0863e59 (#3350)](https://github.com/elastic/connectors/pull/3350)

[8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0863e59 (#3350)

---

.backportrc.json
.buildkite/pipeline.yml
catalog-info.yaml

- [8.18 Release Activities for DRA / Backport (#3166)](https://github.com/elastic/connectors/pull/3166)

[8.x] 8.18 Release Activities for DRA / Backport (#3166)

---

.backportrc.json
.buildkite/pipeline.yml
NOTICE.txt
catalog-info.yaml

- [Rename 8.x to 8.19 (#3387)](https://github.com/elastic/connectors/pull/3387)

[8.19] Rename 8.x to 8.19 (#3387)

---

NOTICE.txt
connectors/sources/confluence.py
tests/sources/test_confluence.py

The goal of this PR is to update the following `paginated_api_call` function to re-raise and/or handle specific Exceptions instead of blanket-swallowing any Exceptions that arise.
Current exception-handling code:
https://github.com/elastic/connectors/blob/8c8d4a3f7775c6edbb598a81a2b67348a7244f3a/connectors/sources/confluence.py#L194-L198

Fix Confluence connector swallowing all errors

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)](https://github.com/elastic/connectors/pull/3414)

[8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)](https://github.com/elastic/connectors/pull/3414)

[8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)](https://github.com/elastic/connectors/pull/3414)

[8.19] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)](https://github.com/elastic/connectors/pull/3414)

[9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)

---

.buildkite/nightly_steps.yml
.buildkite/pipeline.yml
.buildkite/release-pipeline.yml
NOTICE.txt

Because the first few tries were spread across PRs, not straightforward to backport. 
OG PRs were:
- https://github.com/elastic/connectors/pull/3425
- https://github.com/elastic/connectors/pull/3426
- https://github.com/elastic/connectors/pull/3427

backport slack configs

---

config.yml.example
connectors/config.py
connectors/services/job_scheduling.py
tests/services/test_job_scheduling.py

- [Make job_scheduling service run schedule in a task pool (#3335)](https://github.com/elastic/connectors/pull/3335)

[8.18] Make job_scheduling service run schedule in a task pool (#3335)

---

connectors/sources/confluence.py
tests/sources/test_confluence.py

- [Fix Confluence connector swallowing all errors (#3384)](https://github.com/elastic/connectors/pull/3384)

[8.19] Fix Confluence connector swallowing all errors (#3384)

---

NOTICE.txt
connectors/sources/mongo.py
tests/sources/fixtures/mongodb/fixture.py
tests/sources/test_mongo.py

MongoDB is pretty special about UUID handling.
Before a certain version of MongoDB, there was UUID type 3 - driver-specific UUID. Here's example from docs:
```
An example GUID created and displayed in a C# application would be shown as follows:
00010203-0405-0607-0809-0A0B0C0D0E0F
The MongoDB C# driver (in the default configuration) will convert it to a Binary database representation and store it with the following byte order:
03 02 01 00 05 04 07 06 08 09 0A 0B 0C 0D 0E 0F
However, the Java driver used to access the same field will return and display the following:
06070405-0001-0203-0F0E-0D0C0B0A0908
The Python driver will display something different again:
03020100-0504-0706-0809-0A0B0C0D0E0F
```
At some point type 4 was introduced, which is serialized in the same way across all the …

Add support for default UUID type 4 serialization

---

connectors/sources/mongo.py
tests/sources/test_mongo.py

A bunch of MongoDB connector simplifications:
- Remove `remote_temp_file` method as it's pure + not really reusable
- Changed `get_client` to just yield client and stop populating `self.collection` - really problematic 
- Adjusted `get_docs` to init client in the beginning of the method
- Adjusted tests

Refactor MongoDB connector `get_client` method to not produce unexpected side-effects

---

NOTICE.txt
requirements/framework.txt
requirements/tests.txt

Bumping `requests` to fix https://github.com/advisories/GHSA-9hjg-9r4m-mvj7. It's a transitive dependency of our real code, plus is used in tests.

Bump requests to 2.32.4

---

NOTICE.txt
requirements/framework.txt
requirements/tests.txt

- [Bump requests to 2.32.4 (#3480)](https://github.com/elastic/connectors/pull/3480)

[8.17] Bump requests to 2.32.4 (#3480)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)](https://github.com/elastic/connectors/pull/3496)

[8.19] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)](https://github.com/elastic/connectors/pull/3496)

[8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)

---

Dockerfile.ftest.wolfi
Dockerfile.wolfi
NOTICE.txt

- [Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)](https://github.com/elastic/connectors/pull/3496)

[9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)

---

NOTICE.txt
connectors/sources/mysql.py

Small cleanup:
Before all SQL connectors were using absolutely same logic that was later split up.
The split did not clean up everything, so this PR just cleans up one thing - unnecessary `MySQLQueries` class.
This PR removes it and inlines queries into the places that use these queries - all queries are used exactly once (or even never).

Remove MySQLQueries class and inline its methods

---

connectors/sources/mysql.py

Instead of running a query to get column names returned, we run same query wrapping it into (`SELECT * from ({query}) LIMIT 0`) to save some time.

Speed up column name fetching

---

NOTICE.txt
requirements/framework.txt

This will backport the following commits from `main` to `9.1`:
- [Bump aiohttp to 3.12.14 (#3554)](https://github.com/elastic/connectors/pull/3554)

[9.1] Bump aiohttp to 3.12.14 (#3554)

---

connectors/es/sink.py

This PR adds a `try/except` block around a dictionary access in the `_populate_stats` method in `es/sink.py`.
While rare, this method can occasionally raise a `KeyError` when the sink hits a lot of indexing errors - this will gracefully catch and log the exception at the DEBUG log level.

Handle KeyError in the ES sink.py

---

tests/ftest.sh

- [ci: improve ftest ES DRA fetching (#3651)](https://github.com/elastic/connectors/pull/3651)

[8.19] ci: improve ftest ES DRA fetching (#3651)

---

connectors/sources/salesforce.py
tests/sources/test_salesforce.py

- [[Salesforce] optimize field validation to reduce API calls (#3668)](https://github.com/elastic/connectors/pull/3668)

[8.18] [Salesforce] optimize field validation to reduce API calls (#3668)

---

connectors/sources/salesforce.py
tests/sources/test_salesforce.py

- [[Salesforce] optimize field validation to reduce API calls (#3668)](https://github.com/elastic/connectors/pull/3668)

[8.17] [Salesforce] optimize field validation to reduce API calls (#3668)

---

NOTICE.txt
tests/sources/fixtures/oracle/docker-compose.yml

This PR pins the OracleDB Docker container version to 23.8.0.0, as `:latest` tag seemed to be causing issues. This change will hopefully unblock CI for now 🤞

Pin Oracle DB version for ftest to 23.8.0.0

---

.buildkite/nightly_steps.yml
.buildkite/pipeline.yml
connectors/sources/sandfly.py

When we added the Sandfly connector in https://github.com/elastic/connectors/issues/3510, we didn't add it to our CI. We should.

Add sandfly to nightly CI
