- requirements.txt
Suggestion when reading CONTRIBUTING.rst - pin requirements of currently used dependencies declared in requirements.txt.
> Pin dependencies in requirements.txt

- config.yml
- connectors/byoc.py
- connectors/byoei.py
- connectors/tests/memconfig.yml
- connectors/tests/test_runner.py
- connectors/tests/test_utils.py
- connectors/utils.py
- docs/CONFIG.md
These improvements were done for the Network drive connector and will make sure we cap memory usage when we ingest *files*
two mechanisms:
- the async queue that piles up documents to send out will block in the next insertion until its size in MB gets down
- the bulk request that is being prepared will be sent out to Elasticsearch when the request reaches a certain size, no matter how many documents we configured per bulk. 
The latter gives us a great way to scale up and down: we can put a huge value for the number of ops for bulk requests
and adapt the request size depending on the network we have.
> limit the bulk queue and request in memory

- connectors/byoei.py
- connectors/tests/test_byoei.py
- connectors/tests/test_runner.py
Remove the `upsert` ops that are done with the result of the file download.
This two-phase is overkill and adds conflict issues. Let's just sent out the document once with everything.
> Remove the two-phase for files

- connectors/byoei.py
- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
- connectors/tests/config.yml
- connectors/tests/test_byoei.py
- connectors/tests/test_runner.py
Not sure why that was lost at some point. We need to keep the timestamp of the document when it's provided by the connector.
> do not add a new ts if the backend provides it

- connectors/byoei.py
- connectors/tests/test_byoei.py
- connectors/tests/test_runner.py
- Remove the two-phase for files (#148)
> [8.5] Remove the two-phase for files (#148)

- config.yml
- connectors/byoc.py
- connectors/byoei.py
- connectors/tests/memconfig.yml
- connectors/tests/test_runner.py
- connectors/tests/test_utils.py
- connectors/utils.py
- docs/CONFIG.md
- limit the bulk queue and request in memory (#147)
> [8.5] limit the bulk queue and request in memory (#147)

- connectors/byoei.py
- connectors/tests/test_utils.py
- connectors/utils.py
I've realized during a bench that `asizeof` is pretty CPU-heavy and slows down the event loop.
This patch dramatically speeds up the memory lookup by:
- avoiding computing 3 times for each item
- avoiding computing the whole batch (that's very expensive)
> speed up the memory lookups by doing a single call per item

- config.yml
- connectors/byoc.py
- connectors/runner.py
- connectors/source.py
- connectors/tests/test_byoc.py
- connectors/tests/test_runner.py
- connectors/tests/test_source.py
For custom connectors, connector service should populate `service_type` and `configuration`.
> Populate service_type and configuration for custom connectors

- connectors/byoc.py
- connectors/runner.py
- connectors/source.py
- connectors/tests/test_byoc.py
- connectors/tests/test_runner.py
- connectors/tests/test_source.py
Regression introduced by https://github.com/elastic/connectors-python/pull/74
the check
```
connector.status in (Status.CREATED, Status.NEEDS_CONFIGURATION )
```
now comes **after** the data source class creation. We need to bypass the creation of the class if we have those states.
The `get_data_source` role became very confusing, I have refactored things.
Changes:
- `connectors.source.get_data_source(connector, config)` becomes `connectors.byoc.BYOConnector.prepare(config)`
- `BYOConnector.prepare()` is always called before `BYOConnector.sync()` and does the config writes in Elasticsearch if needed
- `BYOConnector.sync()` creates the data provider instance if needed.
- `connectors.runner.ConnectorService._one_sync()` becomes much cleaner as it deals with the `connector` instance only …
> avoid creating source class if not needed

- connectors/byoc.py
- connectors/runner.py
- connectors/tests/test_byoc.py
- connectors/tests/test_runner.py
This PR introduces 2 changes:
1. Add pagination to `get_connectors` function
2. Make `get_connectors` only return supported connectors.
> Add pagination and only return supported connectors

- connectors/byoc.py
- connectors/runner.py
- connectors/utils.py
Stop checking for the `pipeline` presence -- puts the Py service on par with the Ruby one
> Remove pipeline check

- Makefile
> [8.6] Fix makefile errors (#233)

- connectors/cli.py
- connectors/services/sync.py
- connectors/utils.py
- requirements/framework.txt
- setup.py
On Linux or macOS, `--uvloop` will use the uvloop (NodeJS) eventloop instead of the system's queue/kqueue. 
Deactivated by default.
> Added the `--uvloop` option

- connectors/services/sync.py
- connectors/sources/tests/fixtures/mysql/loadsample.py
- connectors/sources/tests/fixtures/mysql/remove.py
- connectors/tests/ftest.sh
- plugged the `--asyncstats` plugin
- exposed `DATA_SIZE` so we can run various sizes of perf tests
- exposed `--refresh-rate` so we can lower the size of the reports on very long runs
> Tweak perf8 options

- connectors/runner.py
- connectors/tests/entsearch.yml
- connectors/tests/test_runner.py
- connectors/utils.py
- Merge the headers from `elasticsearch:headers` (#243)
> [8.6] Merge the headers from `elasticsearch:headers` (#243)

- connectors/runner.py
- connectors/tests/entsearch.yml
- connectors/tests/test_runner.py
- connectors/utils.py
- Merge the headers from `elasticsearch:headers` (#243)
> [8.5] Merge the headers from `elasticsearch:headers` (#243)

- connectors/tests/test_sync.py
- connectors/tests/test_utils.py
- The cron test can fail if the time is at the last second of the minute, so we just check it runs under 2 min
- left over from a merge, we do want to catch stdout in that test
> fixed an intermittent+leftover from a merge

- connectors/services/sync.py
A couple small changes:
1. Rearranged arguments in `_run` function to group them more logically (same things happen together)
2. Moved all preflight check logic to a separate method
> Extract pre-flight check to a function + rearrange arguments in _run function

- connectors/filtering/__init__.py
- connectors/filtering/basic_rule.py
- connectors/tests/test_basic_rule.py
- requirements/framework.txt
This PR introduces the BasicRule class which can check if a document matches the constraints defined by a basic rule. The BasicRule tries to coerce the type of the rule value to the type of the document value. It also exposes a property to check whether the used policy was `include` or not (will be important for the rules engine and its execution later on during a sync).
The following comparisons are supported:
- Starts with
- Ends with
- Contains
- Regex
- Less than
- Greater than
- Equals
> Add BasicRule class matching documents against a basic rule

- connectors/filtering/basic_rule.py
- connectors/tests/test_basic_rule.py
This PR adds a parse method to the `BasicRule` class to parse an array of dicts representing raw basic rules in the following way:
- Map every raw basic rule in the json array to the corresponding BasicRule object
- Filter out every basic rule, which matches the default rule
- Sort the result in descending order according to their basic rule order (rules are executed in descending order)
Also add `from_string` factory methods for the `Policy`, `Rule` and a `from_json` factory method for `BasicRule`.
> [Filtering] Add BasicRule parse method

- connectors/filtering/basic_rule.py
- connectors/tests/test_basic_rule.py
- requirements/framework.txt
Related to https://github.com/elastic/enterprise-search-team/issues/3583
This PR introduces the [fastjsonschema](https://pypi.org/project/fastjsonschema/) library. The evaluation/discovery process is described in https://github.com/elastic/enterprise-search-team/issues/3646. Also add a class encapsulating a basic rule schema and validate rules against it. The validation returns a BasicRuleValidationResult which can be used later to log validation information and also to inform the UI about invalid rules.
> [Filtering] Validate basic rules against a JSON schema

- connectors/filtering/basic_rule.py
- connectors/tests/test_basic_rule.py
This PR introduces the BasicRuleEngine which executes a list of rules in the order they're passed to the BasicRuleEngine. It also records which rule included or excluded how many documents (will be used for logging at the end of a sync job).
> [Filtering] Add BasicRuleEngine to execute a list of rules against a document

- connectors/filtering/basic_rule.py
- connectors/tests/test_basic_rule.py
This PR adds the `BasicRuleNoMatchAllRegexValidator`. The default rule is excluded from this validation as it intentionally uses a match all regex.
> [Filtering] Add BasicRuleNoMatchAllRegexValidator

- connectors/filtering/basic_rule.py
- connectors/tests/test_basic_rule.py
This PR adds two new classes:
- `BasicRuleSetValidator`: this class serves as a base class to validate a whole set of rules, used to validate constraints between different rules as opposed to `BasicRuleValidator` which validates a single rule in isolation. Can also act as a facade later on hiding different basic rule validators keeping code clean (passing all rules to it and calling the appropriate validators).
- `BasicRuleSetSemanticValidator`: this class checks if semantic errors are present in the set of rules like the following:
- Duplicate rules with the same policy (duplicate in the sense of same `field`, `rule` and `value`)
- Duplicate rules with different policies (duplicate in the sense of same `field`, `rule` and `value`)
- (other constraints can be added in the future)
> [Filtering] Add BasicRuleSetSemanticValidator

- Makefile
- connectors/tests/test_utils.py
- connectors/utils.py
- requirements/framework.txt
- Adds a base64 helper that uses the system's `base64` encoder (fast and no memory overhead)
- Falls back to pure Python (win32)
- enforces a lower limit for tests coverage
> added convert_to_b64

- Makefile
I ran into the problem that the execution of the following commands:
```
make clean
make install
make run
```
lead to the following error: `make: bin/elastic-ingest: No such file or directory`.
I've added `bin/elastic-ingest` command to `install` to be sure that it's also installed. Also removed a redundant installation step (requirements are installed by `bin/python` and by `bin/elastic-ingest`).
> [Makefile] Add 'bin/elastic-ingest' command to 'install' command

- requirements/framework.txt
This PR will update `elasticsearch` client to the latest public version 8.6.0
*Note*: I didn't update `elastic-transport` because the latest version is 8.4.0.
> Update elasticsearch client to 8.6.0

- connectors/byoc.py
- connectors/services/sync.py
- connectors/source.py
- connectors/sources/directory.py
- connectors/sources/gcs.py
- connectors/sources/mysql.py
- connectors/sources/network_drive.py
- connectors/sources/s3.py
- connectors/sources/tests/test_gcs.py
- connectors/tests/test_byoc.py
- connectors/tests/test_source.py
The Python framework uses type definitions, which are not part of the connectors protocol.
We're sending back the default configuration to Kibana with this extra field, and it chokes.
This change ensures we respect the standard by sending back only `label` and `value`.
We're keeping the `type` value because it allows us to automatically convert the value we get back from Kibana into the right type. The patch also automates the conversion in the `Field` class.
The changes will be tested once ent-search main picks the main snapshot
> Fix configuration values sent to Kibana

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Updated document key as `database_table_column` to avoid the parsing error from elastic
> [MySQL] Update document key as database_table_column

- connectors/byoc.py
- connectors/source.py
- connectors/sources/abs.py
- connectors/sources/directory.py
- connectors/sources/gcs.py
- connectors/sources/mongo.py
- connectors/sources/mysql.py
- connectors/sources/network_drive.py
- connectors/sources/s3.py
- connectors/sources/tests/support.py
- connectors/sources/tests/test_gcs.py
- connectors/tests/fake_sources.py
- connectors/tests/test_source.py
Small refactoring for BaseDataSource:
Before:
```python
def __init__(self, connector):
self.connector = connector
```
After:
```python
def __init__(self, configuration):
self.configuration = configuration
```
Idea is - neither `BaseDataSource` nor its children need access to `Connector` class instance - moreover it can be used in a harmful way. This change makes it so that DataSource classes only receive configuration as an argument in the initializer.
> Simplify the __init__ for BaseDataSource

- connectors/tests/test_utils.py
- connectors/utils.py
I closed https://github.com/elastic/connectors-python/pull/281 because I figured out that we did not have a race condition.
See https://github.com/elastic/connectors-python/pull/281#issuecomment-1379794960
But then I realized the implementation can lead to unordered inserts in the queue. So this new patch reintroduces the change which does respect the ordering.
> reimplemented the MemQueue class to avoid unordered inserts

- connectors/source.py
- connectors/tests/test_source.py
- the conversion for bool=false is broken (#319)
> [8.6] the conversion for bool=false is broken (#319)

- connectors/tests/test_config.py
Seems like `test_config.py` is broken, see: https://buildkite.com/elastic/connectors-python/builds/1452#0185bb48-cb87-4632-81bb-0ec9f96a36a9
Running `bin/pytest connectors/tests/test_config.py` produces the following output:
```
E           ValueError: Strict mode enabled, variables $elasticsearch.password are not defined!
lib/python3.10/site-packages/envyaml/envyaml.py:270: ValueError
---------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
[FMWK][17:33:25][INFO] Loading config from /Users/artemshelkovnikov/git_tree/connectors-py/connectors/tests/config.yml
================================================================================ …
```
> Fix test_config.py

- connectors/sources/abs.py
- connectors/sources/gcs.py
- connectors/utils.py
`base64` on macOs returns `\n` instead of an empty string.  Here, we strip the data before we put it in the attachment key
A better long term fix would be to generate a real 15 bytes files in those tests, but it's still a good idea to strip
cc @praveen-elastic
> fix macOS specific issue

- connectors/sources/tests/test_abs.py
- connectors/sources/tests/test_gcs.py
- connectors/tests/fake_sources.py
- connectors/tests/memconfig.yml
- connectors/tests/test_sync.py
Improves test performance - some tests are taking too long to finish.
Changes in the PR:
- Remove `connectors/sources/tests/test_abs.py::test_ping_for_empty_connection_string` - judging from the implementation of `ping`, there is no actual different in our code regarding connection strings. ABS client seems to have some internal implementation difference based on connection strings, but our code does not make a difference - it just catches a wide `Exception` and handles it. Thus this test is deleted as previous test `test_ping_for_failed_connection` handles exactly same scenario.
- `connectors/sources/tests/test_abs.py::test_ping_for_failed_connection` - now mocks response from 3rd-party instead of making a real call to 3rd-party system
- `connectors/sources/tests/test_gcs.py:: …
> Mock some calls for abs and gcs tests

- connectors/sources/abs.py
- connectors/sources/tests/test_abs.py
1. Added `tweak_bulk_options` implementation as per https://github.com/elastic/connectors-python/issues/256#issuecomment-1373816488 for tweaking `concurrent_downloads` to support https://github.com/elastic/connectors-python/pull/279
2. Added archive tier check as it won't support permit `download_blob` operation
3. Update configuration initialization in `__init__` as per https://github.com/elastic/connectors-python/pull/287
> [ABS] Add concurrent_downloads option & archive check

- connectors/sources/tests/fixtures/mysql/fixture.py
We had a failure in the e2e test for MySQL
`mysql.connector.errors.OperationalError: 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes`
This change updates the table in batches of 1000 lines to avoid hitting that limit
reproduced locally with 
```
make ftest NAME=mysql
```
which passes with the fix
> dont send huge sql queries in load()

- connectors/byoc.py
- connectors/cli.py
- connectors/conftest.py
- connectors/preflight_check.py
- connectors/services/sync.py
- connectors/tests/test_cli.py
- connectors/tests/test_preflight_check.py
- connectors/tests/test_sync.py
This PR extracts preflight check to a separate module.
The preflight check should not be run in any service (in this case, `SyncService`), but should be done (blocking) before any service can be started.
> Extract preflight check from SyncService

- Makefile
- connectors/sources/tests/fixtures/mysql/fixture.py
- connectors/tests/ftest.sh
- requirements/framework.txt
- requirements/tests.txt
- Add perf8 integration (#191)
tried with 
```
make ftest NAME=mysql
```
in this branch
> [8.6] Add perf8 integration (#191)

- connectors/tests/test_preflight_check.py
Speeding up tests in `test_preflight_check.py` - they rely on default timeout times that are a bit too slow (e.g. initial backoff for retrying connector to Elasticsearch is 5 seconds). These tests mock responses, thus no need to keep long times.
```
> bin/pytest -sv --durations=0 connectors/tests/test_preflight_check.py
```
Before change takes ~19 seconds:
```
5.01s call     connectors/tests/test_preflight_check.py::test_es_unavailable
4.06s call     connectors/tests/test_preflight_check.py::test_job_index_missing
4.03s call     connectors/tests/test_preflight_check.py::test_connector_index_missing
4.03s call     connectors/tests/test_preflight_check.py::test_both_indices_missing
2.02s call     connectors/tests/test_preflight_check.py::test_index_exist_transient_error
0.01s call …
```
> Speed up test_preflight_check.py tests

- connectors/tests/test_utils.py
- requirements/tests.txt
See for example pipeline https://buildkite.com/elastic/connectors-python/builds/1611#0185c5c1-f3fb-47bd-a9c3-91f50b4270fa: 
```
=================================== FAILURES ===================================
________________________________ test_next_run _________________________________
def test_next_run():
assert next_run("1 * * * * *") < 120
>       assert next_run("* * * * * *") == 0
E       AssertionError: assert 1.999814 == 0
E        +  where 1.999814 = next_run('* * * * * *')
connectors/tests/test_utils.py:35: AssertionError
```
The problem happens because test that checks when next cron trigger happens uses current time for the fixture - in some cases it seems to produce unexpected results.
This fix adds `freezegun` package and uses it to rewind the time for this specific test: …
> Fix one flaky test relying on time

- connectors/cli.py
- connectors/services/base.py
- connectors/services/sync.py
- connectors/tests/test_sync.py
This PR made the following changes:
1. The CLI will be able to run multiple services.
2. Move `perf8` to the application level.
3. Move some common attributes to `BaseService`
4. Make one service only run once.
> Refactor services

- connectors/source.py
- connectors/sources/abs.py
- connectors/sources/gcs.py
- connectors/sources/mysql.py
- connectors/sources/network_drive.py
- connectors/sources/s3.py
When running `bin/elastic-ingest --action list`, it prints:
```
[FMWK][11:14:02][INFO] Registered connectors:
[FMWK][11:14:02][INFO] - MongoDB
[FMWK][11:14:02][INFO] - Amazon S3
[FMWK][11:14:02][INFO] - Directory
[FMWK][11:14:02][INFO] - Class to fetch and modify documents from MySQL server
[FMWK][11:14:02][INFO] - Class to fetch documents from Network Drive
[FMWK][11:14:02][INFO] - Class to fetch documents from Google Cloud Storage.
[FMWK][11:14:03][INFO] - Class to fetch documents from Azure Blob Storage
[FMWK][11:14:03][INFO] Bye
```
The `__doc__` of each data source is expected to be the name of each data source:
https://github.com/elastic/connectors-python/blob/002901eeadb5faa9e66fdaaa8fab06f477ff648f/connectors/cli.py#L118
This PR updates the `__doc__` of some data sources.
> Update data source __doc__

- connectors/tests/test_es_client.py
- connectors/tests/test_utils.py
Similar to https://github.com/elastic/connectors-python/pull/343 speeding up two slowest tests:
1. test_es_client.py
```
> bin/pytest -sv --durations=0 connectors/tests/test_es_client.py
```
Before:
```
================================================================================================ slowest durations ================================================================================================
4.17s call     connectors/tests/test_es_client.py::test_es_client_no_server
```
After:
```
================================================================================================ slowest durations ================================================================================================
0.02s call     connectors/tests/test_es_client.py::test_es_client_no_server
0.01s …
```
> Speed up test_es_client.py and test_utils.py slow tests

- connectors/tests/test_sync.py
Reduce the idling time from the sync service to 0 when it's created in the tests within `test_sync.py`.
Speed up: ~ 4.5 seconds to ~ 400 ms (This would've add up for every new test in `test_sync.py`; +0.5s with every test)
Before:
After:
~~- [ ] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)~~
~~- [ ] Considered corresponding documentation changes~~
~~- [ ] Contributed any configuration settings changes to the configuration reference~~
> [Performance] Speed up sync tests

- connectors/byoc.py
- connectors/tests/test_byoc.py
This PR will add a new SyncJobIndex class which represents sync job index.
> Add SyncJobIndex

- Makefile
- connectors/tests/test_utils.py
- requirements/tests.txt
A couple small changes bundled:
1. Add `pytest-fail-slow` pytest plugin that fails tests that are too slow. Too slow = 1 second for now (there are a couple tests that take ~500ms). This can be changed later to something smaller, ideally ~100ms. Package page: https://pypi.org/project/pytest-fail-slow/ Package license is MIT.
2. Speed up `connectors/tests/test_utils.py::test_mem_queue_race` by decreasing intervals + set test timeout to 1 second
> Add pytest plugin to fail tests that are too slow

- connectors/sources/tests/test_mysql.py
The test actually worked for the wrong reason: A query was passed instead of a query name, which lead to an exception thrown not for the reason of exceeding retries, but for formatting a string in a wrong way. As this [PR](https://github.com/elastic/connectors-python/pull/378) changed this behavior the test started to work in the intended way and got slow as the `DEFAULT_WAIT_MULTIPLIER` was not mocked and had a high value. This PR mocks now `DEFAULT_WAIT_MULTIPLIER` and speeds up the test.
> [Performance] Fix and speed up test in MySQL tests

- connectors/source.py
- connectors/sources/mysql.py
The `serialize` method in the MySQL connector is the same as in the base class it inherits the method from.
> [Refactoring] Remove duplicate serialize method

- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_mysql.py
- connectors/tests/test_source.py
This PR fixes the `test_serialize` tests as they were not testing the actual logic and were still green, when you've changed the logic in `serialize` to return wrong values/types. Also move it to the appropriate place.
> [Fix] Fix test_serialize tests to test the actual logic

- connectors/byoc.py
- connectors/kibana.py
- connectors/tests/commons.py
- connectors/tests/test_byoc.py
- connectors/tests/test_byoei.py
This PR adds empty filtering to the functional tests and also updates the default filters to be actual `Filter` objects and not plain dicts.
> [Fix] Add empty filtering to functional tests and update the default filtering

- requirements/framework.txt
Seems to be connected to the CI failure from [this post](https://elastic.slack.com/archives/CA65B8NUR/p1675084007614339?thread_ts=1675073394.259549&cid=CA65B8NUR):
```
[2023-01-30T10:09:51.161Z]   × python setup.py egg_info did not run successfully.
[2023-01-30T10:09:51.161Z]   │ exit code: 1
[2023-01-30T10:09:51.161Z]   ╰─> [3 lines of output]
[2023-01-30T10:09:51.161Z]       error in elasticsearch-connectors setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
[2023-01-30T10:09:51.161Z]           azure-storage-blob>
[2023-01-30T10:09:51.161Z]                             ^
[2023-01-30T10:09:51.161Z]       [end of output] …
```
> Pin azure-storage-blob version

- scripts/verify.py
Small fix for a warning when running functional tests:
> /Users/artemshelkovnikov/git_tree/connectors-py/connectors/tests/../../scripts/verify.py:80: DeprecationWarning: There is no current event loop
>  loop = asyncio.get_event_loop()
> Create an event loop instead of getting for verify.py

- config.yml
- connectors/byoc.py
- connectors/services/sync.py
- connectors/tests/config.yml
- connectors/tests/test_sync.py
- connectors/tests/test_utils.py
- connectors/utils.py
- docs/CONFIG.md
Allows concurrent syncs to happen.
The `SyncService` class runs syncs sequentially. This patch will allow it to run several syncs at the same time (with a max concurrency value)
We can keep that value to `1` on cloud for now, because this will make the service grow in memory.
> Allow concurrent syncs

- connectors/sources/s3.py
- connectors/sources/tests/test_s3.py
- docs/DEVELOPING.md
This PR includes following changes 
- Updated comma separated string to pass buckets
- Added * to index all buckets example : "buckets": {"value": "*", "label": "AWS Buckets", "type": "list"}
- Added exception when user passes an empty string ("")
> Add support for fetching data all buckets

- connectors/byoc.py
- connectors/source.py
- connectors/sources/mysql.py
- connectors/sources/tests/test_abs.py
- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_mongo.py
- connectors/sources/tests/test_network_drive.py
- connectors/sources/tests/test_oracle.py
- connectors/sources/tests/test_postgresql.py
- connectors/sources/tests/test_s3.py
- connectors/tests/test_validation.py
- setup.py
See thread: https://elastic.slack.com/archives/C01795T48LQ/p1675244947774679?thread_ts=1675177627.706859&cid=C01795T48LQ
Linter stage broke because of Black update. Rules that were triggered make sense, so I propose we fix them with `make autoformat`.
> Fix linters for new version of black

- connectors/sources/aws.py
- connectors/sources/mysql.py
- connectors/sources/tests/test_aws.py
- connectors/sources/tests/test_mongo.py
- connectors/tests/test_byoc.py
- connectors/tests/test_byoei.py
- connectors/tests/test_runner.py
- connectors/tests/test_source.py
- connectors/tests/test_utils.py
Mirror of https://github.com/elastic/connectors-python/pull/409 to 8.5 branch.
Black updated to a new version, so now need to reformat the code base here if we want to backport changes to this branch.
> Fix linters on 8.5 branch

- connectors/byoc.py
- connectors/source.py
- connectors/sources/mysql.py
- connectors/sources/tests/test_mongo.py
- connectors/sources/tests/test_network_drive.py
- connectors/sources/tests/test_s3.py
- connectors/tests/test_byoc.py
- connectors/tests/test_byoei.py
- connectors/tests/test_runner.py
- connectors/tests/test_source.py
- connectors/tests/test_utils.py
Mirror of https://github.com/elastic/connectors-python/pull/409 to 8.6 branch.
Black updated to a new version, so now need to reformat the code base here if we want to backport changes to this branch.
> Fix linters on 8.6 branch

- connectors/sources/tests/test_mysql.py
- connectors/tests/commons.py
This PR removes some duplicate setup code, the `AsyncIter` class and some unnecessary comments.
> [Refactoring] Remove duplicate setup code/AsyncIter in test_mysql

- connectors/kibana.py
- connectors/sources/tests/fixtures/mysql/filtering.json
- connectors/tests/ftest.sh
- connectors/tests/test_kibana.py
This PR adds a mechanism to read a `filtering.json` file located in the fixtures for each data source. If no `filtering.json` file is present we fall back to the default filtering. 
> [Testing] Read in filtering.json for functional tests

- connectors/services/job_cleanup.py
- connectors/tests/test_job_cleanup.py
Follow-up PR of https://github.com/elastic/connectors-python/pull/219
This PR ensures that the content indices of existing connectors are not deleted.
> Don't delete content indices of existing connectors

- connectors/byoc.py
- connectors/tests/test_byoc.py
- connectors/tests/test_sync.py
This change allows to continue with Suspended jobs.
When connector service checks connector and sees that "last_sync_status" was "Suspended", then service schedules an absolutely new job for this connector.
What it means in practice, also, is that if configuration/filtering of connector changed between the moment service was suspended and restarted, then new job will have new configuration/filtering as well.
If connector service was restarted/terminated when connector was working on a sync, the connector will try to sync again when the service is started again.
> Add logic to allow running a new job if connector was suspended before

- connectors/sources/tests/test_abs.py
- connectors/sources/tests/test_mysql.py
- connectors/sources/tests/test_oracle.py
- connectors/sources/tests/test_postgresql.py
- connectors/tests/commons.py
- connectors/tests/test_byoc.py
- connectors/tests/test_byoei.py
- connectors/tests/test_job_cleanup.py
This PR removes multiple duplicates of `AsyncIter` and uses the common implementation under `commons.py`.
> [Refactoring] Remove duplicate AsyncIter class

- connectors/byoc.py
- connectors/cli.py
- connectors/services/base.py
- connectors/services/sync.py
- connectors/tests/test_job_cleanup.py
- connectors/tests/test_sync.py
This PR makes sure that several things happen when service is being terminated/restarted:
1. Jobs are interrupted immediately instead of waiting of it to finish
2. When jobs are interrupted, they are marked as "Suspended" so that other logic that restarts the job can kick-in
When service is interrupted, it suspends the jobs immediately so that it can be restarted later when the service is back up.
> Mark jobs that were running during service termination as Suspended

- docs/DOCKER.md
The correct commands are `docker-build` and `docker-run`.
> [Docs] Fix commands in docker docs

- connectors/byoc.py
The method `_sync_done` is also called in `JobCleanUpService` to mark a job as `error`, and it will report error because at the end of method `_sync_done`, there is a log:
https://github.com/elastic/connectors-python/blob/66af09843512b88f28f89746a45d45ade351095b/connectors/byoc.py#L601-L604
When called from `JobCleanUpService`, `self._start_time` is not defined.
This is a [known issue](https://github.com/elastic/connectors-python/pull/219#discussion_r1090960415), and should be fixed by the refactor PR https://github.com/elastic/connectors-python/pull/375. But now we feel it's too risky to merge the refactor PR and I need time to break it down into multiple small PRs, we may not have it in 8.7. So I want to have this change to make the …
> move log from method _sync_done to finally block

- connectors/tests/test_sync.py
Minor problem with current `test_sync` tests is that it relies on time when interrupting the service. If the service is too slow, then the logic that the test expects to trigger might make too much time. If the timeout is too big, however, the test will take too much time to run.
This change updates `run_service_with_stop_after` to work differently:
If `stop_after` is not provided or is 0, then the test will attempt to update `service.running` with `call_soon`. In essence, it will mean that the service will attempt to terminate without cancelling jobs. (TODO: should we change a BaseService method? Like having `stop` with a `force_terminate` parameter?
If `stop_after` is provided, the logic stays how it was - service is terminated in `stop_after` seconds while cancelling running work.
> Change create_and_run_service to make it more reliable

- connectors/sources/abs.py
- connectors/sources/directory.py
- connectors/sources/gcs.py
- connectors/sources/generic_database.py
- connectors/sources/mysql.py
- connectors/sources/network_drive.py
- connectors/sources/s3.py
This cleans up the labels of configuration fields in various sources, making them more easily understandable and consistent.
> Clean up config field names for all sources

- connectors/kibana.py
This PR updates the ftest connector data, to use `None` instead of `""` for datetime fields
> Use None instead of empty string for datetime field

- connectors/byoc.py
- connectors/services/sync.py
- connectors/tests/test_byoc.py
- connectors/tests/test_sync.py
- connectors/tests/test_utils.py
- connectors/utils.py
`e2str` is a pretty generic method and should probably live in `utils.py`, so we don't run into possible cyclic imports, when we import it.
> [Refactoring] Move e2str to utils to avoid cyclic imports

- connectors/byoc.py
- connectors/byoei.py
- connectors/tests/test_byoei.py
Pass the active filtering (an instance of `Filter`) instead of filtering (a list of filtering including `active` and `draft` filtering, an instance of `Filtering`).
Moving forward, we will use `filtering` data in `syncJob`, where only active filtering data is available.
> Use active filter in async_bulk

- connectors/byoc.py
- connectors/tests/test_utils.py
- connectors/utils.py
This PR adds a `str2e` function in module `connectors.utils`, to convert a string to an Enum value
> Add str2e function

- connectors/byoc.py
- connectors/byoei.py
- connectors/tests/test_byoc.py
- connectors/tests/test_byoei.py
This PR implements the class `Pipeline` as a derived class of `UserDict`, which provides default values for:
1. name
2. extract_binary_content
3. reduce_whitespace
4. run_ml_inference
> Implement Pipeline as a derived class of UserDict

- connectors/tests/test_byoc.py
Mock the elasticsearch client directly and assert the passed kwargs.
Also remove explicit sleep for some speed up.
Use a local variable instead of a "constant", which can get mutated dependent on the test case order.
> [Fix] Fix flaky test "test_sync_job"

- Makefile
- config.yml
- connectors/cli.py
- connectors/tests/ftest.sh
- connectors/tests/test_cli.py
- docs/CONFIG.md
- docs/DEVELOPING.md
Minor improvement for the CLI:
Instead of `--debug` flag setting log level to DEBUG and having INFO as a default, we can now specify log level in 2 ways:
1. By providing it in config in `service.log_level: <LOG_LEVEL>` setting
2. By running the service with --log-level=<LOG_LEVEL>
Precedence of the operation is:
1. Option from CLI arguments
2. Option from configuration file
3. If none provided, fall back to INFO
Now it's possible to choose the log level of the service by either using a "--log-level=<LOG_LEVEL>" argument when running the service over CLI or setting a `service.log_level: <LOG_LEVEL>` option in configuration file.
> Add --log-level setting for ingest service instead of --debug flag

- connectors/cli.py
- connectors/services/base.py
- connectors/services/sync.py
- connectors/tests/test_job_cleanup.py
- connectors/tests/test_sync.py
As discussed with @tarekziade before, `loop.add_signal_handler(sig, lambda: asyncio.ensure_future(_shutdown(sig.name)))` is not the right way to handle the cancellation - ensure_future expects a synchronous function.
This patch does the following:
- Makes BaseService.stop a non-async function like it was before
- Modifies loop.add_signal_handler to properly call shutdown without a `lambda` statement.
> Fix service stop code

- connectors/cli.py
- connectors/tests/test_cli.py
Small change connected to discussion in https://github.com/elastic/connectors-python/pull/446#discussion_r1101566293.
`elastic-ingest --action list` outputs to the logger, while it naturally feels like it should instead output to STDOUT.
Before:
```
artemshelkovnikov@Artems-MBP connectors-py % bin/elastic-ingest --action list
[FMWK][14:12:54][INFO] Loading config from /Users/artemshelkovnikov/git_tree/connectors-py/connectors/../config.yml
[FMWK][14:12:54][INFO] Registered connectors:
[FMWK][14:12:54][INFO] - MongoDB
[FMWK][14:12:54][INFO] - Amazon S3
[FMWK][14:12:54][INFO] - System Directory
[FMWK][14:12:54][INFO] - MySQL
[FMWK][14:12:55][INFO] - Network Drive
[FMWK][14:12:55][INFO] - Google Cloud Storage
[FMWK][14:12:55][INFO] - Azure Blob Storage
[FMWK][14:12:55][INFO] - PostgreSQL …
```
> Make --action list command output to stdout

- Makefile
- config.yml
- connectors/cli.py
- connectors/tests/test_cli.py
- docs/CONFIG.md
- docs/DEVELOPING.md
- [Add --log-level setting for ingest service instead of --debug flag (#446)](https://github.com/elastic/connectors-python/pull/446)
> [8.7] Add --log-level setting for ingest service instead of --debug flag (#446)

- connectors/cli.py
- connectors/tests/test_cli.py
- [Make --action list command output to stdout (#454)](https://github.com/elastic/connectors-python/pull/454)
> [8.7] Make --action list command output to stdout (#454)

- connectors/es/client.py
`delete_indices` used a default mutable argument, which could've lead to weird bugs in the future.
> [Fix] delete_indices used a default mutable argument

- connectors/cli.py
- connectors/services/base.py
- connectors/tests/test_base_service.py
- [Terminate all services if one exits (#437)](https://github.com/elastic/connectors-python/pull/437)
> [8.7] Terminate all services if one exits (#437)

- connectors/byoc.py
Pointed out by @tarekziade here https://github.com/elastic/connectors-python/pull/460#discussion_r1106300817, we should not use mutable default. This PR made changes to some methods of `SyncJobIndex` class, to make some params compulsory.
> Make SyncJobIndex methods param compulsory

- connectors/byoc.py
- connectors/services/job_cleanup.py
- connectors/tests/test_byoc.py
- connectors/tests/test_job_cleanup.py
This PR renames `stuck` jobs to `idle` jobs, including comments, variable names and method names.
> Rename stuck jobs to idle jobs

- connectors/byoc.py
- connectors/es/__init__.py
- connectors/es/document.py
- connectors/es/index.py
- connectors/services/job_cleanup.py
- connectors/services/sync.py
- connectors/tests/test_byoc.py
- connectors/tests/test_es_document.py
- connectors/tests/test_job_cleanup.py
- connectors/tests/test_sync.py
This PR refactors `SyncJob` class. The changes are:
1. Add a new class `ESDocument`, to be a parent class of `SyncJob` and `Connector` class.
2. Make `SyncJob` data representation of a document in `.elastic-connectors-sync-jobs`, and include self-mutating methods.
3. Move `transform_filtering` method from `SyncJob` to `Filter`.
4. Add `validate_filtering` method to `SyncJob`.
5. Make the system work with the refactored `SyncJob`.
> Refactor SyncJob class

- README.md
- docs/CONNECTOR_PROTOCOL.md
- docs/DEVELOPING.md
I think it makes more sense to have the connector protocol in the python repository as we're moving onwards with python.
TODOs:
> [Docs] Move connector protocol to python

- connectors/es/client.py
I think this error message should be more explicit, what the conditions are detecting that basic auth and the api key are used at the same time.
> [Refactoring] Make error more explicit when basic auth and api key are used at the same time

- connectors/source.py
- connectors/tests/test_source.py
`assert` statements are supposed to be used only in tests. We have an `assert` statement in our production code in `BaseDataSource` class. This assert attempts to validate the type of `configuration` variable passed into the class.
This PR removes `assert` and replaces it with a regular `if` statement that checks type of the variable and raises a `TypeError` in case the type is unexpected. Choice of exception type was made based on https://docs.python.org/3/library/exceptions.html#TypeError
> Remove assert from source.py and replace it with manual validation

- connectors/es/client.py
- connectors/tests/test_es_client.py
This PR
1. makes the param `indices` of method `ESClient.delete_indices` mandatory, 
2. returns early without making ES request if `indices` is empty.
> Make param indices of delete_indices method mandatory

- connectors/byoc.py
- connectors/es/__init__.py
- connectors/es/document.py
- connectors/es/index.py
- connectors/services/job_cleanup.py
- connectors/services/sync.py
- connectors/tests/test_byoc.py
- connectors/tests/test_es_document.py
- connectors/tests/test_job_cleanup.py
- connectors/tests/test_sync.py
- [Refactor SyncJob class (#460)](https://github.com/elastic/connectors-python/pull/460)
> [8.7] Refactor SyncJob class (#460)

- connectors/filtering/validation.py
- connectors/services/sync.py
- connectors/tests/test_validation.py
This PR extracts some changes from #474 , which updates `validate_filtering` function. 
`source_klass` is passed in as a param as `source_klass` won't be availbe in `Connector` class anymore.
> Update validate_filtering function

- connectors/byoc.py
- connectors/byoei.py
- connectors/tests/test_byoei.py
This PR is to rename the param `filter` in `Fetcher` class and `async_bulk` method to `filter_`, as `filter` is a built-in name.
> Rename param filter to filter_

- connectors/cli.py
- connectors/tests/test_cli.py
Quoting:
> Certain logging like connectors yml parsing errors have no logger or log level specification so it is easy to be missed by admins/support.
We want Cloud (and other) deployments to properly report errors about parsing config files. To do so, I'm wrapping parsing of config file in try/except and in case error happens use provided `--filebeat` option + set log level to INFO (can actually do DEBUG, doesn't matter as long as it reports errors).
> Set logger before parsing config

- connectors/sources/generic_database.py
We only allow one database for Oracle and PostgreSQL to be configured. This should also be reflected in the label.
> [Generic Database Connector] Use singular for database label

- connectors/cli.py
- connectors/tests/test_cli.py
- [Set logger before parsing config (#524)](https://github.com/elastic/connectors-python/pull/524)
> [8.7] Set logger before parsing config (#524)

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Allow only one database to be configured for a MySQL connector. This will remove the database validation concern during filtering validation. I've considered moving the whole MySQL implementation to use `generic_database.py`, but this would need some more investigation and also prioritisation. Can be discussed later, when all SQL-like connectors follow the same topology.
A big chunk of the diff is due to removal of methods like `validate_databases`, `configured_databases` and the corresponding tests.
> [MySQL] Only allow one database to be configured

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Small fix for a sleep line in MySQL connector:
```
RETRY_INTERVAL = 2
await asyncio.sleep(RETRY_INTERVAL**retry)
```
Retry count is user's input. What it means is that if something goes wrong and connector has to retry, let's say, 5 times, last sleep will be 2^5 = 32 seconds. If service is interrupted during this time, it'll have to wait until these 32 seconds pass.
This change makes use of CancellableSleep so that if service is stopped, user won't have to wait for remaining sleep time until service is interrupted.
> Make MySQL connector terminate faster when connector is retrying

- connectors/filtering/validation.py
- connectors/sources/tests/test_mysql.py
- [[Fix] Store filtering in its original form in .elastic-connectors-sync-job (#477)](https://github.com/elastic/connectors-python/pull/477)
> [8.7] [Fix] Store filtering in its original form in .elastic-connectors-sync-job (#477)

- .backportrc.json
Currently we only matched versions like "8.7.0", but not "8.7.0.0", which lead to some missing backports.
> Allow multiple ".digit" postfixes after major.minor in .backportrc

- connectors/byoc.py
- connectors/services/sync.py
This PR extracts this part of `Connector.sync` method to `SyncService`:
https://github.com/elastic/connectors-python/blob/a5976d20cd8277ae46511f7176662afc889e56ec/connectors/byoc.py#L686-L719
The logic checks whether the connector is ready to sync (on-demand, scheduled or restart a suspended job), and whether there's any change in the remote source. The logic should not be part of `sync` method.
> Extract ready_to_sync method from Connector to SyncService

- connectors/byoc.py
- connectors/tests/test_sync.py
Found a problem while doing refactoring. BaseService actually swallows terminal errors - ones that make service stops. Due to change in https://github.com/elastic/connectors-python/pull/514 removing this code, some tests break - I decided to fix them in separate PR (this one).
This PR does the following:
1. Makes `test_sync.py` create service that does not swallow errors with config["service_config"]["max_errors"] = 0
2. Pull instantiation of `configured_service_type` higher - it's used in a method later and it's possible that this variable won't be defined by the time it's used
3. Fix setup of tests for validation of config - nesting was incorrect for changing the features
> Fix issues raising from base service swallowing errors

- connectors/filtering/basic_rule.py
- connectors/filtering/validation.py
- connectors/tests/test_byoc.py
Add documentation for the most important classes and methods in the filtering module. Skipped on the documentation, where it doesn't add any information, which can not be derived from the class name.
> [Docs] Document the filtering module

- connectors/sources/tests/fixtures/network_drive/docker-compose.yml
Removing Volumes since the data used for e2e test does not need to be stored permanently in the device, it thus allows e2e test to execute irrespective of the device configuration, since devices like macbook with m1 chip provide enhanced security features such as sticky bit preventing deletion of files.
> [Network Drive] Add support for e2e in Macbook with m1 chip

- connectors/services/sync.py
This PR did a minor refactor of `SyncService`:
1. rename `self.hb` to `self.heartbeat_interval`
2. rename `self.connectors` to `self.connector_index`
3. rename method `_one_sync` to `_sync`
4. remove `self.raise_if_spurious` for `DataSourceError` and raise directly
5. put `connector.sync` into `self.syncs` instead of `self._one_sync`
> Minor refactor of SyncService

- connectors/byoc.py
- connectors/source.py
- connectors/sources/mysql.py
- connectors/tests/fake_sources.py
- connectors/tests/test_sync.py
We want to be able to validate connector configuration meaningfully on the level of the framework - not as a part of other methods like `ping` or `get_docs`.
This PR introduces new method `validate_configuration` to BaseSource that does nothing when called. Individual sources can override it to validate configuration and raise errors if configuration was invalid. If configuration was invalid and exception was raised, framework will just handle this error as any other errors - it will update connector status to `ERROR` and display error message coming from `validate_configuration` in UI.
It would have been a large change to implement for all connectors, so this PR only implements the change for MySQL connector. Later I'm planning to follow-up with this change for all other connectors and …
> Introduce "validate_configuration" method to BaseSource and use it

- connectors/kibana.py
- connectors/sources/s3.py
When I run `make lint` I see the below `pyright` errors, and this PR tries to fix them:
```shell
pyright 1.1.295
/Users/chenhui.wang/src/github.com/elastic/connectors-python/connectors/kibana.py
/Users/chenhui.wang/src/github.com/elastic/connectors-python/connectors/kibana.py:107:48 - error: No parameter named "body" (reportGeneralTypeIssues)
/Users/chenhui.wang/src/github.com/elastic/connectors-python/connectors/kibana.py:129:48 - error: No parameter named "body" (reportGeneralTypeIssues)
/Users/chenhui.wang/src/github.com/elastic/connectors-python/connectors/sources/s3.py
/Users/chenhui.wang/src/github.com/elastic/connectors-python/connectors/sources/s3.py:138:31 - error: Cannot access member "response" for type "ServerTimeoutError"
  Member "response" is unknown …
```
> Fix pyright errors

- .backportrc.json
- connectors/sources/generic_database.py
- connectors/sources/mysql.py
- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_mysql.py
This PR adds a new configurable field for the MySQL connector to be able to configure the tables, where we ingest from. Remote validation (do the configured tables exist, does the database user has access?) of configured tables will happen separate from this PR and is tracked by this issue: https://github.com/elastic/enterprise-search-team/issues/4052.
I've reused some functionality from `generic_database.py` to avoid duplication and make it easier to migrate the mysql connector to use `GenericDatabaseSource` class (if we decide to).
The corresponding frontend change for the native MySQL connector is tracked by https://github.com/elastic/enterprise-search-team/issues/4032.
~- [ ] Contributed any configuration settings changes to the …
> [MySQL] Make tables configurable

- connectors/sources/oracle.py
~`DEFAUTL_WALLET_CONFIGURATION_PATH`~ -> `DEFAULT_WALLET_CONFIGURATION_PATH`
Not sure about **backports**, _iff_ this typo needs correcting.
> Fix typo in `oracle.py`

- connectors/tests/test_es_index.py
Tarek pointed out ([slack link](https://elastic.slack.com/archives/C01795T48LQ/p1678209151786269)) that the test coverage for the ESIndex class is only 62%. This PR improves the coverage to 100%
> Add more tests for ESIndex class

- connectors/kibana.py
- docs/CONNECTOR_PROTOCOL.md
This PR adds a new field `last_sync_scheduled_at` to index `.elastic-connectors`.
> Add last_sync_scheduled_at to connector index

- connectors/sources/tests/test_mysql.py
- connectors/tests/test_es_index.py
I've noticed, that the tests regarding `close` for the MySQL connector didn't have any assertions, that a connection pool was actually closed. They've relied on the absence of an exception implying that the connection pool was closed correctly. 
Also removed the fake class `ConnectionPool` as this object/class is mocked now.
> [MySQL] Add assertions to "close" tests

- connectors/sources/tests/test_mysql.py
Use `pass` for a noop statement in a test.
> [MySQL] Use pass for noop statement in test

- connectors/sources/mongo.py
- connectors/sources/tests/test_mongo.py
Add the advanced rules validator for the MongoDB connector.
The advanced rules validator checks, that the provided advanced rules adhere to the motor asyncio API (see: https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_motor_collection.html).
Note that some lower-level options, which require f.e. a python object are not exposed.
> [MongoDB] Advanced rules validator

- connectors/source.py
- connectors/sources/google_cloud_storage.py
- connectors/sources/tests/test_google_cloud_storage.py
- connectors/tests/test_utils.py
- connectors/utils.py
This PR addresses the following changes:
- Parse the private-key present in the configurations passed from UI.
- Moves the configuration validation to a separate method.
> [GCS]-Parse configurations from Kibana UI

- connectors/sources/mongo.py
- connectors/sources/tests/test_mongo.py
Empty advanced rules should be valid for MongoDB.
> [MongoDB] Allow empty advanced rules

- connectors/cli.py
- connectors/services/__init__.py
- connectors/services/base.py
- connectors/services/job_cleanup.py
- connectors/services/job_scheduling.py
- connectors/tests/test_base_service.py
- connectors/tests/test_cli.py
This patch prepares https://github.com/elastic/connectors-python/pull/220/files where I'll add a new service.
It introduces a simple metaclass to simplify the registry of services in the CLI (one service == one action)
It allows running the CLI like this:
```
elastic-ingest --action sync cleanup upload
```
And automatically create a `MultiService` instance with the two services -- removing the need to define services in CLI.
To add a new service, you just create the class and name the action
> service factory metaclass

- connectors/filtering/validation.py
- connectors/tests/test_validation.py
Empty advanced rules shouldn't be validated, because that would imply that every connector implementation needs to handle the special case of advanced rules being empty correctly.
> [Filtering] Empty advanced rules shouldn't be validated

- connectors/sources/mongo.py
- connectors/sources/tests/test_mongo.py
This PR adds validation logic to MongoDB connector in the same way it works in Ruby. Particularly, these two cases:
-  Entering invalid database name displays a helpful error message in Kibana UI
-  Entering invalid collection name displays a helpful error message in Kibana UI
> Add validation and errors for invalid mongodb database/collection

- connectors/es/document.py
- connectors/tests/test_es_document.py
This PR adds new instance variable `_seq_no` and `_primary_term` to `ESDocument` class
> Add _seq_no and _primary_term to ESDocument

- .buildkite/nightly.yml
- connectors/sources/generic_database.py
- connectors/sources/oracle.py
- connectors/sources/postgresql.py
- connectors/sources/tests/fixtures/oracle/docker-compose.yml
- connectors/sources/tests/fixtures/oracle/fixture.py
- connectors/sources/tests/fixtures/oracle/requirements.txt
- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_oracle.py
- requirements/framework.txt
- [Upgrade SQLAlchemy v2.0 to use python-oracledb and improve performance (#447)](https://github.com/elastic/connectors-python/pull/447)
> [8.7] Upgrade SQLAlchemy v2.0 to use python-oracledb and improve performance (#447)

- docs/DEVELOPING.md
- [[Generic Database Connector] Added documentation for PostgreSQL in developing.md (#549)](https://github.com/elastic/connectors-python/pull/549)
> [8.7] [Generic Database Connector] Added documentation for PostgreSQL in developing.md (#549)

- docs/DEVELOPING.md
- [[Generic Database Connector] Added documentation for Oracle Database in developing.md (#556)](https://github.com/elastic/connectors-python/pull/556)
> [8.7] [Generic Database Connector] Added documentation for Oracle Database in developing.md (#556)

- connectors/sources/azure_blob_storage.py
- connectors/sources/tests/test_azure_blob_storage.py
As a part of standardisation effort, we're moving all validation of connector configurations into `validate_config` method of the connector.
This PR does it for ABS connector - validation was happening in multiple methods in the connector, i moved it to a single `validate_config` method.
> Introduce validate_config to ABS connector

- connectors/services/job_scheduling.py
This change separates the messaging for situations when connector cannot sync due to it being in invalid status. Now there's a different message for connector status `CREATED` and `NEEDS_CONFIGURATION`, and this message is trying hard to be user-friendly and actionable!
> Add more explicit messages for connector errors when status is unexpected

- connectors/cli.py
When running connector service with default arguments OR not with "list" action, we want to output service version into console.
Example output with this change:
```
artemshelkovnikov@Artems-MacBook-Pro connectors-py % make run
bin/elastic-ingest
[FMWK][14:36:39][INFO] Loading config from /Users/artemshelkovnikov/git_tree/connectors-py/connectors/../config.yml
[FMWK][14:36:39][INFO] Running connector service version 8.8.0.0
[FMWK][14:36:39][INFO] Preflight checks...
[FMWK][14:36:39][INFO] Waiting for NodeConfig(scheme='http', host='localhost', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, …
```
> Log service version once real service starts

- connectors/sources/directory.py
Minor change - it's the only place in code where `print` is used instead of `logger.info`, thus this PR contains only 1 line of change :)
> Replace print with logger.info for directory connector

- connectors/source.py
- connectors/sources/azure_blob_storage.py
- connectors/sources/generic_database.py
- connectors/sources/google_cloud_storage.py
- connectors/sources/jira.py
- connectors/sources/mongo.py
- connectors/sources/mysql.py
- connectors/sources/s3.py
- connectors/sources/sharepoint.py
- connectors/sources/tests/test_azure_blob_storage.py
- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_google_cloud_storage.py
- connectors/sources/tests/test_jira.py
- connectors/sources/tests/test_mongo.py
- connectors/sources/tests/test_mysql.py
- connectors/sources/tests/test_s3.py
- connectors/sources/tests/test_sharepoint.py
- connectors/utils.py
This PR adds a new error type - `connectors.utils.ConfigurableFieldValueError` that is supposed to be used in `valdiate_config` of individual connector source files.
For now I haven't changed the way the errors are treated in the framework - framework still catches `Exception` and fails the sync, but in future I'm planning to add separate handling to also properly distinguish validation errors vs other errors (type errors, value errors, problems accessing 3rd-party system, etc).
What I also don't address - incompatible types for values are still handled in a messy way. E.g. if connector expects an integer in "port", but you give it a string, you'll get an unreadable exception message.
> Introduce and use ConfigurableFieldValueError

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Use the newly introduced `ConfigurableFieldError`, if the config is invalid.
> [MySQL] Use ConfigurableFieldError in validate_config

- connectors/tests/test_utils.py
- connectors/utils.py
Attempting to improve error messages for QueueFull error. There are 2 possible cases:
1. MemQueue has not been dequeued for a while and is still full after a timeout. Example message:
```
MemQueue has been full for 1.005s. while timeout is 1s.
```
2. MemQueue is almost full and a consumer is attempting to forcefully add a large enough object to it. Example message:
```
Queue is full: attempting to add item of size 4056 bytes while 10 free bytes left."
```
> Add human-readable error messages to QueueFull

- connectors/byoc.py
- connectors/tests/test_sync.py
- [Fix issues raising from base service swallowing errors (#551)](https://github.com/elastic/connectors-python/pull/551)
> [8.7] Fix issues raising from base service swallowing errors (#551)

- .github/PULL_REQUEST_TEMPLATE.md
I've noticed a few PRs today with empty descriptions or missing links to issues. This should help make sure they aren't accidentally left out.
> Adds PR hygiene checks to checklist

- connectors/byoei.py
The `get_mb_size` is CPU intensive operation, and it's used in debug logging:
https://github.com/elastic/connectors-python/blob/d3736dfcc824af7bcbc7ff99d7cb39ae2163217b/connectors/byoei.py#L118-L120
A function used in f-string will be evaluated even if the message is not logged at all (e.g. the log level is set to INFO).
This PR is to make sure the `get_mb_size` is not called if the message is not to be logged, by the best practice from the official python doc: https://docs.python.org/3.10/howto/logging.html#optimization
> Use lazy evaluation for expensive function in DEBUG log

- connectors/sources/s3.py
- connectors/sources/tests/test_s3.py
Our Nightly QA pipeline caught a problem with S3 connector - it wasn't able to sync.
Investigation shown that I forgot adding `async` before `validate_config` method in S3 connector - framework expects `validate_config` to by an async function and awaits for it, and it was causing an error.
> Add missing async/await for validate_config in s3

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Wildcards are supported by MySQL connector but they fail the validation step `_validate_tables_accessible`.
This was also causing [nightly e2e tests to fail](https://buildkite.com/elastic/connectors-python-nightly/builds/452#01872c9e-794f-47b1-9d2e-cd475208640b).
This PR updates `_validate_tables_accessible` so that wildcards fetch all of the database tables, which can then be tested individually for accessibility.
Reviewers can confirm that this fixes the nightly build by running `NAME=mysql make ftest` locally.
* https://github.com/elastic/connectors-python/pull/662#issuecomment-1488837434
> Allow wildcards in MySQL table accessibility validation

- connectors/sources/mysql.py
The framework already logs this information and other data sources are not logging it explicitly, so we should remove it.
> [MySQL] Remove unnecessary log

- config.yml
- requirements/framework.txt
Our CI is currently blocked because `pyodbc` is not installed in Cloud docker image.
We're getting rid of this library and migrating to `pytds` here: https://github.com/elastic/connectors-python/pull/624#discussion_r1150295132
The migration is not finished yet, but soon will be. Meanwhile we need to unblock our CI by removing the dependency. On-prem SQL connectors using generic sql connector code will be broken with this change and repaired with the mentioned PR.
> Remove `pyodbc` library from requirements.txt

- connectors/tests/ftest.sh
Perf8 has no time to wrap up its work sometimes (when memray has a lot of work) and the current ftest moves on once the sync is over and does not wait.
We end up getting incomplete reports in BK for this reason.
This is a fast fix, a better fix would be to make sure the process running with perf8 has a chance to finish before we move to the next step in the script
> added a 2mn pause to give a chanche to perf8 to wrap up

- connectors/byoei.py
- connectors/services/job_scheduling.py
- connectors/sync_job_runner.py
- connectors/tests/test_byoei.py
- connectors/tests/test_sync_job_runner.py
- [Make async_bulk a task (#513)](https://github.com/elastic/connectors-python/pull/513)
> [8.7] Make async_bulk a task (#513)

- connectors/byoc.py
- connectors/sync_job_runner.py
- connectors/tests/test_byoc.py
- connectors/tests/test_sync_job_runner.py
- [Report ingestion stats during job execution (#515)](https://github.com/elastic/connectors-python/pull/515)
> [8.7] Report ingestion stats during job execution (#515)

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
The current implementation is a bit unclear how ids are generated at a first look. To safely be able to change these ids in the future, which is needed for https://github.com/elastic/enterprise-search-team/issues/4263 and https://github.com/elastic/enterprise-search-team/issues/4240 I want to separate out the generation of ids to make the code more readable and to be able to test the id generation in isolation. 
This will also make it easier to reuse this code as it's conceptually the same in other SQL-like connectors.
> [MySQL] Separate get_primary_key_columns

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Create a separate `generate_id` method and test it explicitly. This enables changing the `_id` generation in a much safer way.
> [MySQL] Separate "generate_id" method

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
This PR changes the `_id` to not contain the `database` a row came from as the MySQL connector only allows one database to be configured, which makes this information obsolete. Therefore the `Database` field is also removed from the docs to ingest as it does not provide any useful information and only takes up space.
Note: After a discussion with Product it's fine that this change leads to a reindex as all `_id`s will change, when a previous MySQL connector version was used to ingest documents.
> [MySQL] Remove unnecessary database information from ids and docs

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Why do we need this change?
Currently too many concerns are implemented in `_connect` inside `MySQLDataSource`:
- Fetching metadata of a table (column names)
- Fetching all rows from a table
- Fetching all rows from a table using pagination
This makes it very hard to adapt the code to the new advanced rules structure as it's not too easy to understand the interaction with the database server in the first place.
We also started to introduce dedicated client classes in other data sources ([Jira Client](https://github.com/elastic/connectors-python/blob/main/connectors/sources/jira.py#L64), [Confluence Client](https://github.com/elastic/connectors-python/blob/main/connectors/sources/confluence.py#L57), etc.) for similar reasons. To further align different connectors and increase the …
> [MySQL] Introduce basic MySQLClient class

- connectors/sources/tests/test_confluence.py
- connectors/sources/tests/test_directory.py
- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_google_cloud_storage.py
- connectors/sources/tests/test_jira.py
- connectors/sources/tests/test_mongo.py
- connectors/sources/tests/test_mssql.py
- connectors/sources/tests/test_mysql.py
- connectors/sources/tests/test_network_drive.py
- connectors/sources/tests/test_oracle.py
- connectors/sources/tests/test_postgresql.py
- connectors/sources/tests/test_s3.py
- connectors/sources/tests/test_sharepoint.py
- connectors/tests/test_byoc.py
- connectors/tests/test_byoei.py
- connectors/tests/test_cli.py
- connectors/tests/test_es_client.py
- connectors/tests/test_es_document.py
- connectors/tests/test_es_index.py
- connectors/tests/test_job_cleanup.py
- connectors/tests/test_job_scheduling.py
- connectors/tests/test_sync_job_runner.py
- connectors/tests/test_utils.py
`patch_logger` is supposed to assert some messages were logged, but it's mainly used to silent logs.
This PR removes incorrect use of `patch_logger`.
> Remove incorrect use of patch_logger

- connectors/cli.py
- connectors/services/__init__.py
- connectors/services/job_execution.py
- connectors/services/job_scheduling.py
- connectors/tests/test_job_execution.py
- connectors/tests/test_job_scheduling.py
This PR decouples the job execution to a separate service.
1. The `JobSchedulingService` will only be responsible for scheduling jobs. It will create a job for a connector when the connector is scheduled to sync, but won't execute the job.
2. The `JobExecutionService` will only be responsible for executing jobs. It will periodically query jobs with `pending`/`suspended` status, and try to execute them.
> Decouple job execution service

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
This PR moved the `ping` method to the `MySQLClient`. This changed revealed some wrong mocking in three unit tests, which are also fixed with this PR as the CI would break otherwise.
> [MySQL] Move "ping" method to MySQLClient

- connectors/byoc.py
- connectors/es/index.py
- connectors/services/job_scheduling.py
- connectors/tests/test_byoc.py
- connectors/tests/test_es_index.py
- connectors/tests/test_job_scheduling.py
This PR passes `trigger_method` to the `create` method of `SyncJobIndex` explicitly, instead of relying on `connector.sync_now`. Because in the following PRs, `connector.sync_now` will be reset first.
> Pass trigger_method explicitly to SyncJobIndex create method

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Note: changes with regards to the `connection_pool` will be made, if all new high-level methods are implemented, so this change can be achieved in a separate PR in a consistent way.
This method will replace the implicit `yield_once` flag in `_connect`, which returns the column names of a table in follow-up PRs. It'll also serve as the base method for fetching the primary key columns of a table as you can simply provide another `query` for `get_column_names` to narrow the result set.
> [MySQL] Add "get_column_names" method to MySQLClient

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Note: changes with regards to the connection_pool will be made, if all new high-level methods are implemented, so this change can be achieved in a separate PR in a consistent way.
This method will replace the `fetch_all_tables` method in a follow-up PR.
> [MySQL] Add "get_all_table_names" to "MySQLClient"

- connectors/tests/ftest.sh
There was a change recently so that Nightly builds were able to produce PERF8 artifacts: https://github.com/elastic/connectors-python/pull/682
This change also increased the run time of our regular CI. This change makes it so that our CI run time would not be affected by the change mentioned simply by putting the added `sleep 120` statement to be executed only if performance is actually measured with PERF8.
> Speed up CI by not sleeping if PERF8 is not enabled

- connectors/tests/test_utils.py
There's a problem that `test_mem_queue` fails often with a message:
```
E                   asyncio.queues.QueueFull: MemQueue has been full for 0.1005s. while timeout is 0.1s.
connectors/utils.py:266: QueueFull
```
I'm increasing timeout for now to make CI fail less often, but we really need to look into it.
> Increase timeout for test_mem_queue

- connectors/tests/ftest.sh
- [Sleep for 2 minutes only if PERF8 is yes (#723)](https://github.com/elastic/connectors-python/pull/723)
> [8.7] Sleep for 2 minutes only if PERF8 is yes (#723)

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Create a new `get_last_update_time` method, calling this method alongside the other new methods will all be done in a separate PR. Also using `fetchone` and not `fetchall` now.
> [MySQL] Add "get_last_update_time" to MySQLClient

- connectors/byoc.py
- connectors/tests/test_byoc.py
When a sync job is created by the connector service, there's no ingestion stats set, which will be defaulted to `null`. Before the first ingestion stats are reported back by connector service, they are displayed empty in Kibana:
This PR sets the default ingestion stats to 0.
> Set default stats when creating a sync job

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Use the newly introduced method `get_all_table_names` in the `MySQLDataSource`
> [MySQL] Use get_all_table_names in MySQLDataSource

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
This PR adds `yield_for_rows` wrapping `_fetchmany_in_batches`. There will be additional high-level methods wrapping `_fetchmany_in_batches` therefore it's already introduced in this PR.
> [MySQL] Add method fetching rows from a table in batches

- requirements/framework.txt
Bumps Elasticsearch to 8.7.0 . Part of [Enterprise Search 8.7.0 release](https://github.com/elastic/enterprise-search-team/issues/3687).
> Bump Elasticsearch to 8.7.0

- connectors/source.py
- connectors/sources/azure_blob_storage.py
- connectors/sources/confluence.py
- connectors/sources/generic_database.py
- connectors/sources/google_cloud_storage.py
- connectors/sources/jira.py
- connectors/sources/mongo.py
- connectors/sources/mysql.py
- connectors/sources/postgresql.py
- connectors/sources/s3.py
- connectors/sources/sharepoint.py
- connectors/sources/tests/test_confluence.py
- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_google_cloud_storage.py
- connectors/sources/tests/test_jira.py
- connectors/sources/tests/test_mongo.py
- connectors/sources/tests/test_mysql.py
- connectors/sources/tests/test_s3.py
- connectors/sources/tests/test_sharepoint.py
Swap all connector validations to framework level.
If a unique validation exists for a connector (e.g. checking JSON structure) that isn't covered by the new validations, I have left it in the connector.
Majority of validations should now be handled by simply having the appropriate `validations` added to the configuration.
> Move validations from connector to framework

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
This PR adapts the `fetch_documents` method to use the new `MySQLClient`. Therefore every interaction with the remote database server happens through the new client. To not clutter this PR's diff a separate PR will be used to remove all old methods and tests.
Two new methods are introduced acting as wrappers for already existing methods:
- `get_primary_key_column_names`
- `yield_rows_for_query `
> [MySQL] Use MySQLClient for interacting with the configured db server

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
This PR removes all old methods, which now live inside in the `MySQLClient`class.
> [MySQL] Remove old data source methods replaced by new MySQLClient methods

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
This PR adapts the `MySQLClient` to use the `CancellableSleeps` class to be able to directly cancel sleeps, if needed.
> [MySQL] Use CancellableSleeps in MySQLClient

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
Align the behavior between the MySQL connector and the connectors inheriting from the GenericDatabaseConnector by falling back to `iso_utc()`, if the `last_update_time` is not present in a row returned from a MySQL table.
> [MySQL] Fallback on iso_utc, if last_update_time is not present

- connectors/byoc.py
- connectors/tests/test_byoc.py
This PR makes the method `sync_starts` of the `Connector` class use optimistic concurrency control, so that it will work in multi-instances environment, and will make sure only one instance can start the sync for a connector successfully.
This will be used in the subsequent PRs.
> Make sync_starts use optimistic concurrency control

- connectors/byoc.py
- connectors/tests/test_byoc.py
This PR adds the method `update_last_sync_scheduled_at` to the `Connector` class and this method will work in multi-instances environment, and will make sure only one instance can update `last_sync_scheduled_at` successfully.
The new method will be used in the subsequent PRs.
> Add update_last_sync_scheduled_at method

- connectors/source.py
- connectors/tests/test_source.py
This change allows `Field` to return a `default_value` when its `value` is requested.
This will only happen if `required: False` and `value` is empty.
If this is approved, I will make a followup PR to set the `value` for all non-required configuration fields to `None` and add an appropriate `default_value`.
> Use default_value for value when applicable

- connectors/sources/generic_database.py
- connectors/sources/mssql.py
- connectors/sources/tests/test_generic_database.py
- connectors/sources/tests/test_mssql.py
Use NamedTemporaryFile for creating temporary SSL Certificate file for MS-SQL.
> [Microsoft SQL]Use NamedTemporaryFile for temporary SSL certificate file

- connectors/sources/tests/fixtures/confluence/fixture.py
This PR aims to add the following changes in e2e:
- With the endpoint change for `content` API, the maximum allowed limit for results is now changed from 100 to 50 in [PR for space as a configurable field](https://github.com/elastic/connectors-python/pull/752/files#diff-c334a0be5ca7d084a2bfca1f24b2d07c40b96f20e359b31b24b3e71056853327R40). The present PR adds relevant change in e2e for the same.
- The API query for `content` was updated from `type=page` to `cql=type=page` or `cql=type=blogpost` in the [PR for space as a configurable field](https://github.com/elastic/connectors-python/pull/752/files#diff-c334a0be5ca7d084a2bfca1f24b2d07c40b96f20e359b31b24b3e71056853327R40) due to which relevant changes needs to be added in e2e for fetching `type` from `args`.
> [Confluence] Update E2E test for space as configurable field 

- requirements/aarch64.txt
Fixes this test on M1: 
```
self = s3.ServiceResource()
def close(self):
>       return self.meta.client.close()
ERROR       AttributeError: 'S3' object has no attribute 'close'
lib/python3.10/site-packages/aioboto3/resources/base.py:17: AttributeError
ERROR    asyncio:base_events.py:1758 Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x12af3a170>
```
> Align aioboto3 version with x86

- docs/CONNECTOR_PROTOCOL.md
The field `indexed_document_volume` (in bytes) in `.elastic-connectors-sync-jobs` is of type `integer`, which can hold a maximum value of `2^31-1`, which is equivalent to 2-ish GB. This PR changes it to `unsigned_long`, which can hold a maximum value of `2^64-1`, which is equivalent to 18-ish Exa Bytes (1 Exa Byte = 1000 PB).
> Use unsigned_long for field indexed_document_volume

- connectors/services/job_scheduling.py
- connectors/tests/test_job_scheduling.py
This PR adds concurrency control to job scheduling:
1. an `on_demand` sync is created only when `sync_now` flag is reset successfully
2. a `scheduled` sync is created only when `last_sync_scheduled_at` is updated successfully
> Add concurrency control to job scheduling

- connectors/byoc.py
- connectors/services/job_scheduling.py
- connectors/tests/test_byoc.py
- connectors/tests/test_job_scheduling.py
This PR adds concurrency control to the `prepare` method of `Connector` class
> Add concurrency control to connector prepare

- connectors/sources/mysql.py
Found a small issue with MySQL connector that was found during functional tests:
When data is received from MySQL, rows are taken and zipped with column names. These column names are taken from the `columns` method in the PR, but the problem is:
```
SELECT * from customers;
| name  | description | age |
| artem | lalala      | 123 | 
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'customerinfo' AND TABLE_NAME = 'customers';
| COLUMN_NAME |
| age         |
| description |
| name        |
```
Sorting is different! As a result, the record for the data above will look like this:
```json
{
"age": "artem",
"description": "lalala",
"name": "123"
}
```
This PR fixes it by also sorting column names by ORDINAL_POSITION - without it they seem to be sorted alphabetically.
> Sort column names by ORDINAL_POSITION

- docs/CONNECTOR_PROTOCOL.md
Reverts elastic/connectors-python#781
See: https://github.com/elastic/connectors-python/issues/735#issuecomment-1513725750
> Revert "Use unsigned_long for field indexed_document_volume"

- connectors/byoc.py
- connectors/es/index.py
- connectors/tests/test_byoc.py
- connectors/tests/test_es_index.py
This PR adds `sort` to `pending_jobs` of `SyncJobIndex` class, so that the oldest sync job is executed first.
> Execute the oldest sync job first

- connectors/services/job_execution.py
- connectors/sync_job_runner.py
- connectors/tests/test_job_execution.py
- connectors/tests/test_sync_job_runner.py
1. Add the `connector.last_sync_status` check to Job Execution Service, so if the connector is still syncing, don't create a `SyncJobRunner` instance for the sync job.
2. Raise `SyncJobStartError` if a `SyncJobRunner` instance fails to start a sync
Context is here: https://github.com/elastic/connectors-python/pull/768#discussion_r1165566262
> Move last_sync_status to Job Execution Service

- connectors/sources/mysql.py
- connectors/sources/tests/test_mysql.py
This PR changes the id generation to always use a sorted versions of the tables/primary key columns for the ids to make ids more stable (tables could have an unsorted order in the advanced rules and impact the order of primary key columns).
We've decided with product to take the query not into account, which leads to the following expected behavior: If you've two queries using the same tables and the result sets overlap, the query executed later "wins" and overrides the documents ingested previously, if the ids match. 
> [MySQL] Make doc id generation more stable using sorted table names/pk columns

- .buildkite/nightly.yml
Minor thing - we have a functional test for MongoDB, but it's not included into nightlies. This PR makes sure we run a functional test for MongoDB during Nightly QA.
> Add MongoDB to nightly runs

- connectors/byoei.py
Round the indexed document volume instead of floor. E.g. 1.8 MB should be rounded to 2 MB instead of 1 MB.
> Round indexed_document_volume

- .buildkite/README.md
- .buildkite/nightly.yml
- .buildkite/pipeline.yml
- .buildkite/run_dockerized_test.sh
- .buildkite/run_nigthly.sh
We'll have our own docker image to run our pipelines against. This PR makes use of this image and cleans up scripts that run tests.
Example before:
https://buildkite.com/elastic/connectors-python/builds/4574#01879df5-c172-4e72-8b53-dd43513f35ff
Example after:
https://buildkite.com/elastic/connectors-python/builds/4583#01879e0c-2445-4e4b-a921-0eb8dc12e4e3
> Use custom docker images for our CI

- docs/DEVELOPING.md
Default value of data source is `Confluence Server`. Reference: https://github.com/elastic/connectors-python/blob/3c318299f6bb0d86e165f819d1d19e5424b6c7f3/connectors/sources/confluence.py#L219
- ~~[x] Contributed any configuration settings changes to the configuration reference~~
> [Documentation] Rectify default value of data source in Confluence

- connectors/sources/tests/fixtures/mongodb/connector.json
- connectors/sources/tests/fixtures/mongodb/docker-compose.yml
- connectors/sources/tests/fixtures/mongodb/fixture.py
Small problem to fix Nightly QA + `NAME=mongodb make ftest`.
Our MongoDB instance is not password-proteched, but connector recently started requiring username/password. This change updates our functional tests to setup a MongoDB instance with a password + change functional test setup to respect this password.
> Make mongodb instance password-protected and use this password

- connectors/sources/tests/fixtures/azure_blob_storage/docker-compose.yml
- connectors/sources/tests/fixtures/confluence/docker-compose.yml
- connectors/sources/tests/fixtures/dir/docker-compose.yml
- connectors/sources/tests/fixtures/google_cloud_storage/docker-compose.yml
- connectors/sources/tests/fixtures/jira/docker-compose.yml
- connectors/sources/tests/fixtures/mongodb/docker-compose.yml
- connectors/sources/tests/fixtures/mssql/docker-compose.yml
- connectors/sources/tests/fixtures/mysql/docker-compose.yml
- connectors/sources/tests/fixtures/network_drive/docker-compose.yml
- connectors/sources/tests/fixtures/oracle/docker-compose.yml
- connectors/sources/tests/fixtures/postgresql/docker-compose.yml
- connectors/sources/tests/fixtures/s3/docker-compose.yml
- connectors/sources/tests/fixtures/sharepoint/docker-compose.yml
Our functional tests seem to fail from time to time with an error:
```
Failed to monitor the sync job. Something bad happened: ApiError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [520278848/496.1mb], which is larger than the limit of [510027366/486.3mb], real usage: [520278848/496.1mb], new bytes reserved: [0/0b], usages [eql_sequence=0/0b, fielddata=0/0b, request=0/0b, inflight_requests=0/0b, model_inference=0/0b]')
```
Looking at the documentation of Elasticsearch this error happens because our Elasticsearch instance is overloaded with data that's being ingested - it's stored in-memory. 
This PR increases the amount of RAM used by Elasticsearch to 2GB, hopefully that should be sufficient.
> Increase nightly ES limits to 2GB to avoid memory errors

- connectors/config.py
- connectors/tests/config.yml
- connectors/tests/entsearch.yml
- connectors/tests/test_config.py
- [Make connectors respect cloud log level (#809)](https://github.com/elastic/connectors-python/pull/809)
> [8.7] Make connectors respect cloud log level (#809)

- connectors/sources/tests/fixtures/fixture.py
Minor change to ftest flow - instead of terminating service with SIGTERM, we give it a chance to gracefully stop with SIGINT.
Why?
Perf8 needs time to compile reports and SIGTERM sometimes prevents it from doing so - if amount of data is reasonably large Perf8 will take several minutes to compile the report. This change potentially makes it so that we'll wait until Perf8 report will be completed.
> Use SIGINT to terminate the process from monitor

- connectors/sources/mongo.py
- connectors/sources/mysql.py
- connectors/sources/tests/fixtures/mongodb/connector.json
- connectors/sources/tests/fixtures/mysql/connector.json
MongoDB and MySQL native connectors and custom connectors are misaligned in their configurable fields.
This PR changes the default fields so that they will be the same as their native counterparts.
See Kibana PR: https://github.com/elastic/kibana/pull/155606
> Align mysql and mongodb with native connectors

- connectors/sources/tests/fixtures/mongodb/connector.json
Small mistake in MongoDB connector.json - somehow there's a dangling comma!
> Fix misformatted mongodb connector.json

- connectors/sources/tests/fixtures/fixture.py
- connectors/tests/ftest.sh
added a max duration for BK
By default we allow a maximum time of 10 minutes per e2e test. If it goes beyond that limit we fail.
Each connector test can tweak that value in the `.env` variable
> added a max duration

- .buildkite/nightly.yml
- .buildkite/pipeline.yml
There was a bug that added 15 seconds to each CI job that is ran in Buildkite. Our pipelines for Buildkite semi-randomly had this option set to true due to it providing no visible side-effects while improving our run-times.
It was fixed with https://github.com/elastic/vault-buildkite-plugin/pull/26 and it's safe to do `useVault: false` for now - we don't have secrets that we use.
> useVault: false for pipelines - we don't use Vault

- .backportrc.json
Maybe it'll fix our autobackports?
It constantly fails saying that it's unable to backport to the branch that's currently main.
Most likely it's broken cause our `main` is automatically labelled with additional `.0` in the end, for example see label for this PR.
We should account for both `v8.9.0` and `v.8.9.0.0` as main, thus I've updated regex to allow optional `.0` in the end.
> Fix regex for main labelling for backportrc

- connectors/tests/ftest.sh
Our FTESTs are still using 8.8.0-SNAPSHOT version of stack, when 8.9.0-SNAPSHOT builds are available this PR needs to be merged to make use of new stack version.
> Bump ftest to use 8.9.0-SNAPSHOT

- .buildkite/nightly.yml
I've set `useVault: false` for Nightly pipeline but it's actually needed to build Docker images, see https://buildkite.com/elastic/connectors-python-nightly/builds/587#0187dbb5-92de-4791-9115-4d0db6c1b1e1
This PR returns `useVault: true` for Nightlies
> Use vault in nightly tests

- connectors/sources/generic_database.py
Linting stage fails due to newer version of static analyser reporting an error:
```
artemshelkovnikov@Artems-MacBook-Pro-2 connectors-py % make lint
bin/isort --check . --sp .isort.cfg
Skipped 6 files
bin/black --check connectors
All done! ✨ 🍰 ✨
91 files would be left unchanged.
bin/black --check setup.py
All done! ✨ 🍰 ✨
1 file would be left unchanged.
bin/flake8 connectors
bin/flake8 setup.py
bin/black --check scripts
All done! ✨ 🍰 ✨
1 file would be left unchanged.
bin/flake8 scripts
bin/pyright connectors
/Users/artemshelkovnikov/git_tree/connectors-py/connectors/sources/generic_database.py
/Users/artemshelkovnikov/git_tree/connectors-py/connectors/sources/generic_database.py:473:31 - error: "__getitem__" method not defined on type "object*" (reportGeneralTypeIssues)
1 error, 0 …
```
> Fix linters for now

- connectors/sources/generic_database.py
- [Fix linters for now (#848)](https://github.com/elastic/connectors-python/pull/848)
> [8.8] Fix linters for now (#848)

- connectors/sources/generic_database.py
- [Fix linters for now (#848)](https://github.com/elastic/connectors-python/pull/848)
> [8.7] Fix linters for now (#848)

- connectors/byoei.py
- [Report indexed_document_volume in MiB (#796)](https://github.com/elastic/connectors-python/pull/796)
> [8.7] Report indexed_document_volume in MiB (#796)

- docs/DOCKER.md
When I QA the above issue, I found that the network creation step is missing in the docker documentation.
> Update docker documentation

- connectors/tests/test_utils.py
- connectors/utils.py
- [Add items that are too big to ingest into the queue anyway (#808)](https://github.com/elastic/connectors-python/pull/808)
> [8.7] Add items that are too big to ingest into the queue anyway (#808)

- connectors/sources/mssql.py
Updating label for SSL certificate for MSSQL connector - it's called "SSL certificate" in PostgreSQL and in Frontend.
> Update SSL cert label for MSSQL

- catalog-info.yaml
When investigating a problem with CI I renamed "connectors-python" to "Connectors Python" and it makes it look weird in CI:
Thus, returning back the name of "connectors-python".
> Return connectors-python back

- connectors/sources/mssql.py
- [Update SSL cert label for MSSQL (#857)](https://github.com/elastic/connectors-python/pull/857)
> [8.8] Update SSL cert label for MSSQL (#857)

- .backportrc.json
Small thing - there are no more 8.6.* releases left, so no point to have it in backportrc.
> Remove 8.6 from backportrc

- README.md
- connectors/sources/mysql.py
- docs/sync-rules/MYSQL.md
This PR adds a new directory under `docs` to provide simple examples for connectors, which have implemented sync rules. These examples target developers trying out and/or modifying the advanced rules implementation.
~- [ ] Tested the changes locally~
~- [ ] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)~
> [Docs] MySQL sync rules examples

- connectors/sources/tests/fixtures/google_cloud_storage/.env
- connectors/sources/tests/fixtures/mssql/.env
- connectors/sources/tests/fixtures/mysql/.env
- connectors/sources/tests/fixtures/oracle/.env
- connectors/sources/tests/fixtures/postgresql/.env
- connectors/tests/ftest.sh
Increasing RSS thresholds by ~35MB for each connector affected.
Seems like we've improved our memory footprints between 8.7 and 8.8 and RSS limits that work for 8.8 don't work for 8.7.
This. PR just increase thresholds so that our nightlies work well.
> Increase FTEST RSS thresholds for 8.7

- Makefile
- connectors/cli.py
Introducing an additional option to cli - `config`.
With this option CLI will output the default connector configuration for connector passed in `--service-type` argument.
It's also possible to use this command with `make default-config SERVICE_TYPE=<service_type>` for convenience.
Example output:
```sh
artemshelkovnikov@Artems-MacBook-Pro-2 connectors-py % make default-config SERVICE_TYPE=mongodb
bin/elastic-ingest --action config --service-type mongodb
[FMWK][12:13:39][INFO] Running connector service version 8.9.0.0
[FMWK][12:13:39][INFO] Loading config from /Users/artemshelkovnikov/git_tree/connectors-py/connectors/../config.yml
Getting default configuration for service type mongodb
{
"host": {
"default_value": null,
"depends_on": [],
"display": "text",
"label": "Server hostname", …
```
> Add a sample option to CLI to get connector default config

- connectors/config.py
- connectors/tests/entsearch_invalid_log_level.yml
- connectors/tests/test_config.py
Funny problem in Cloud - when user changes `log_level` setting, it has to be lowercase.
However, Connector Service expects upper case log_level and is unable to start. Thus, adding this little hack for now to unblock 8.8 deployment - if we're updating log_level for deployment from Enterprise Search, then upper case it.
We need to follow up on this with a more complex value remapping from Enterprise Search config.
> Correctly copy over log_level from Enterprise Search config file

- docs/CONNECTOR_PROTOCOL.md
Backports the following commits to 8.8:
- Add rich configurable fields to connector protocol (https://github.com/elastic/connectors-python/pull/893)
> [8.8] Add rich configurable fields to connector protocol (893)

- connectors/utils.py
Add XLSM and XLSB filetypes to the list `TIKA_SUPPORTED_FILETYPES` in utils.py
> Add xlsb, xlsm in tika supported filetypes

- connectors/sources/tests/fixtures/sharepoint/fixture.py
To be able to measure data volume more precisely we need to store documents' IDs as 36 bytes strings (Sharepoint format)
* https://github.com/elastic/enterprise-search-team/issues/4332
> [Sharepoint] Make all documents IDs size 36 bytes

- connectors/utils.py
- [add xlsb, xlsm in tika supported filetypes (#894)](https://github.com/elastic/connectors-python/pull/894)
> [8.8] add xlsb, xlsm in tika supported filetypes (#894)

- connectors/sources/tests/fixtures/sharepoint/fixture.py
This PR adds support for multiple file sizes for better Sharepoint Online/Server simulation.
if `DATA_SIZE` environment variable is passed then only one size will be used.
* https://github.com/elastic/enterprise-search-team/issues/4332
> [Sharepoint] Support multiple file sizes

- connectors/byoei.py
- connectors/tests/test_byoei.py
When framework attempts to create a search index mappings, it does not actually provide "dynamic" and "dynamic_templates" settings to the `put_mappings` call. This PR changes it and actually starts providing these options.
> Fix problem with incorrect mappings created for content indices

- connectors/tests/test_utils.py
- connectors/utils.py
See the detailed analysis here: https://github.com/elastic/enterprise-search-team/issues/4517#issuecomment-1546108471
This PR makes the changes, so that when an exception is raised from a task in `ConcurrentTasks`, the [join](https://github.com/elastic/connectors-python/blob/ccaa51a7de7b104c381f7ba71581b56bdad89475/connectors/utils.py#L353-L355) will still wait for other tasks to complete.
> Don't stop the ConcurrentTasks when one task raises exception

- connectors/protocol/connectors.py
- connectors/source.py
- connectors/sync_job_runner.py
- connectors/tests/test_protocol.py
- connectors/tests/test_source.py
- connectors/tests/test_sync_job_runner.py
When configuration is missing fields, we raise an error. That information doesn't make it to Kibana, because it is never added to the `error` document field.
This PR adds the missing error information to the document.
> Add malformed configuration error to document

- connectors/byoc.py
- connectors/source.py
- connectors/sync_job_runner.py
- connectors/tests/test_byoc.py
- connectors/tests/test_source.py
- connectors/tests/test_sync_job_runner.py
- [Add malformed configuration error to document (#909)](https://github.com/elastic/connectors-python/pull/909)
> [8.8] Add malformed configuration error to document (#909)

- connectors/byoei.py
- connectors/tests/test_byoei.py
- [Fix problem with incorrect mappings created for content indices (#908)](https://github.com/elastic/connectors-python/pull/908)
> [8.8] Fix problem with incorrect mappings created for content indices (#908)

- .buildkite/nightly.yml
- .buildkite/run_nigthly.sh
- connectors/sources/tests/fixtures/sharepoint/fixture.py
This will fix the broken nightly build of Sharepoint connector. 
Also, DATA_SIZE becomes configurable via command argument
* [Broken build](https://buildkite.com/elastic/connectors-python-nightly/builds/638#018823cf-eac2-4c4f-9cb0-2dcdef6d2e09)
```
+ NUM_DOCS='Generating '\''small'\'' size data
750'
+ /opt/buildkite-agent/builds/bk-agent-elastic-gcp-1684228024617818935/elastic/connectors-python-nightly/connectors/tests/../../bin/python /opt/buildkite-agent/builds/bk-agent-elastic-gcp-1684228024617818935/elastic/connectors-python-nightly/connectors/tests/../../scripts/verify.py --index-name search-sharepoint --service-type sharepoint --size Generating ''\''small'\''' size data 750
[FMWK][09:31:09][INFO] Fetcher <create: 131 |update: 0 |delete: 0>
usage: verify
[-h]
[--config-file …
```
> Fix Sharepoint e2e test

- connectors/sources/tests/fixtures/sharepoint/docker-compose.yml
`DATA_SIZE` wasn't passed correctly to `docker compose` from `ftest.sh`
Links:
* [Fix Sharepoint e2e test](https://github.com/elastic/connectors-python/pull/922)
> [Sharepoint] Fix DATA_SIZE variable

- connectors/protocol/connectors.py
- tests/protocol/test_connectors.py
When a new sync job starts, it should also reset the connector error.
> Reset connector error when a new sync job starts

- connectors/protocol/connectors.py
- connectors/sources/mysql.py
- tests/protocol/test_connectors.py
This PR adds the `last_permissions_sync_scheduled_at` property to the connectors class. The property will be added to protocol with another PR.
> [DLS] Add "last_permissions_sync_scheduled_at" property to connector class

- connectors/sources/atlassian.py
- connectors/sources/jira.py
- tests/sources/test_atlassian.py
- tests/sources/test_jira.py
This PR introduces advanced filtering rules for JIRA by custom JQL queries to filter out issues based on that. Also included `atlassian.py` which can be helpful to implement filtering rules for Atlassian connectors [`Jira` & `Confluence` for now]
> Jira advanced sync rules

- connectors/source.py
- connectors/sources/mysql.py
- tests/test_source.py
This PR adds the `get_permissions` method to the `BaseDataSource`, which should be implemented by connectors supporting DLS.
> [DLS] Add "get_permissions" to BaseDataSource

- connectors/protocol/connectors.py
- connectors/sources/mysql.py
- tests/protocol/test_connectors.py
This PR adds a new enum `JobType` used by DLS and incremental syncs. There's no default value provided as we should raise/log an error, if we encounter a job without a job type IMO.
The corresponding protocol change will be handled by a different PR in Enterprise Search.
> [DLS] Add "permissions" job_type to SyncJob class

- connectors/protocol/connectors.py
- connectors/sources/mysql.py
- tests/protocol/test_connectors.py
This PR adds the `document_level_security` feature flag. We'll use that feature flag to guard calls to `get_permissions` and `permissions_query` on a framework level. 
The protocol update will happen in a separate PR inside Enterprise Search.
> [DLS] Add "document_level_security" feature flag

- connectors/kibana.py
- connectors/sources/mysql.py
Add new `last_permissions_sync_scheduled_at` field to the kibana fake.
> [DLS] Add "last_permissions_sync_scheduled_at" to Kibana fake

- connectors/sources/mysql.py
- docs/CONNECTOR_PROTOCOL.md
Adds `last_permissions_sync_scheduled_at` to the connector protocol docs.
~- [ ] Tested the changes locally~
> [DLS] Add "last_permissions_sync_scheduled_at" to protocol docs

- connectors/protocol/connectors.py
- connectors/sources/mysql.py
- tests/protocol/test_connectors.py
This PR adds an update method for the new `last_permissions_sync_scheduled_at` field of a connector document. This is needed, when a job scheduler scheduled a permissions sync job, so other connector service instances don't schedule the same permissions sync job multiple times.
> [DLS] Add "last_permissions_sync_scheduled_at" mutator

- docs/CONNECTOR_PROTOCOL.md
Update the connector protocol to include `sync_cursor` in `.elastic-connectors` index
> Add sync_cursor to connector protocol doc

- connectors/kibana.py
- tests/fixtures/connector.json
- tests/sources/fixtures/mongodb/connector.json
- tests/sources/fixtures/mysql/connector.json
Add `sync_cursor` to `connector.json` of ftest.
> Add sync_cursor to ftest connector.json

- connectors/sources/mysql.py
- docs/CONNECTOR_PROTOCOL.md
This PR adds the new `last_permissions_sync_status` to the connector protocol docs.
> [DLS] Add "last_permissions_sync_status" to connector protocol docs

- connectors/kibana.py
- connectors/sources/mysql.py
- tests/fixtures/connector.json
- tests/sources/fixtures/mongodb/connector.json
- tests/sources/fixtures/mysql/connector.json
This PR adds `last_permissions_sync_status` to the Kibana fake and the fixtures.
> [DLS] Add "last_permissions_sync_status" to kibana and fixtures

- connectors/protocol/connectors.py
- docs/CONNECTOR_PROTOCOL.md
- tests/protocol/test_connectors.py
This PR:
1. adds property `last_incremental_sync_scheduled_at` to  class `Connector`
2. adds the mutating method of `last_incremental_sync_scheduled_at` to class `Connector`
3. adds `last_incremental_sync_scheduled_at` to connector protocol
> Add last_incremental_sync_scheduled_at to Connector

- connectors/protocol/connectors.py
- connectors/sources/mysql.py
- tests/protocol/test_connectors.py
This PR adds the `last_permissions_sync_status` property to the `Connector` class we'll need for at most one permissions sync per connector semantics.
> [DLS] Add last_access_control_sync_status property to Connector

- connectors/protocol/connectors.py
- connectors/sources/mysql.py
- tests/protocol/test_connectors.py
This PR changes the "scheduling.permissions" field to "scheduling.access_control"
> [DLS] Rename "scheduling.permissions" to "scheduling.access_control"

- connectors/protocol/connectors.py
- tests/protocol/test_connectors.py
Adds mutating of `sync_cursor` to the `sync_done` method of the `Connector` class, so that the `sync_cursor` will only be updated after a completed sync job.
> Update sync_cursor for a completed sync job

- requirements/framework.txt
Bumping version of elasticsearch to 8.8.0
> Bump elasticsearch package to 8.8.0

- connectors/sources/sharepoint.py
- tests/sources/test_sharepoint.py
This PR includes:
1. Add  `server_relative_url` for list and its items as a document field in elastic search.
> [Sharepoint] Add server relative url for list and its items

- connectors/protocol/connectors.py
- connectors/services/job_scheduling.py
- tests/protocol/test_connectors.py
- tests/services/test_job_scheduling.py
Allows to create a sync job with job type, defaulted to `full`
> Allow to create job with job type

- connectors/source.py
- tests/test_source.py
This PR
1. adds a class method `support_incremental_sync` to indicate whether the data source supports incremental syn
2. adds a method `get_docs_incrementally` to run incremental sync
3. adds a method `sync_cursor`
> Add incremental sync support to BaseDataSource

- connectors/services/job_execution.py
- connectors/sources/mysql.py
- tests/services/test_job_execution.py
This PR adds a guard to check whether a connector has an access control sync already running, so we don't schedule two access control syncs at the same time for one connector.
The assertion will be adapted to use the separate access control syncs task pool in a separate PR addressing the task pool separation.
> [DLS] At most one access control sync per connector guard

- connectors/services/job_scheduling.py
- tests/fake_sources.py
- tests/fixtures/config.yml
- tests/services/test_job_scheduling.py
`JobSchedulingService` should only schedule incremental sync job is the feature flag is enabled for the connector and the data source for the connector supports incremental sync.
> Add incremental sync support to JobSchedulingService

- tests/sources/fixtures/sharepoint/fixture.py
Flask limiter use slightly different names for the HTTP throttling headers. This PR will align them with Sharepoint server
> [Sharepoint] Use correct throttling headers 

- connectors/es/sink.py
- connectors/services/job_execution.py
- connectors/sync_job_runner.py
- tests/protocol/test_connectors.py
- tests/services/test_job_execution.py
- tests/test_sink.py
- tests/test_sync_job_runner.py
`JobType` should be imported from `connectors.protocol`, instead of `connectors.protocol.connectors`
> Import from connectors.protocol

- connectors/services/job_execution.py
- connectors/source.py
- tests/fake_sources.py
- tests/services/test_job_execution.py
Part of https://github.com/elastic/enterprise-search-team/issues/4733
Introduces the concept of "premium" connectors, and won't run syncs for premium connectors if your license level isn't sufficient.
- https://github.com/elastic/connectors-python/pull/1013
> add premium connectors

- Makefile
- tests/conftest.py
- tests/es/test_client.py
- tests/es/test_index.py
- tests/fake_sources.py
- tests/protocol/test_connectors.py
- tests/services/test_job_execution.py
- tests/services/test_job_scheduling.py
- tests/sources/fixtures/sharepoint_online/fixture.py
- tests/sources/test_generic_database.py
- tests/sources/test_google_cloud_storage.py
- tests/sources/test_mongo.py
- tests/sources/test_s3.py
- tests/sources/test_sharepoint.py
- tests/sources/test_sharepoint_online.py
- tests/test_logger.py
- tests/test_sink.py
- tests/test_source.py
- tests/test_sync_job_runner.py
Mistakes were made and when I moved `tests` directory from `connectors` directory, linters and autoformat stopped working on it.
This PR enables both `make lint` and `make autoformat` to work on tests directory and fixes all broken rules.
> Fix make lint|autoformat to also work on tests

- connectors/sources/mssql.py
This fixes MSSQL validate_host config field displaying as a text field instead of a toggle.
> Display MSSQL validate_host bool as toggle

- connectors/sources/sharepoint_online.py
Updating casing for Sharepoint Online connector labels following comment from @sphilipse:
> ...
> 
> Also, we've generally used Sentence case instead of Title Case for these values. So: Tenant Name instead of Tenant Name, and so on for all the others.
> 
> Tenant ID or Tenant id are both preferable toTenant Id.
> Update configurable field cases

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
Renaming 2 functions:
- get_attachment -> get_attachment_content
- get_content -> get_drive_item_content
Adding a comment to get_attachment_content that explains something about timestamps and why we always need to subextract attachments.
> Small renames for download functions in SPO connector + important comment for attachment download

- connectors/protocol/connectors.py
- connectors/sync_job_runner.py
- tests/protocol/test_connectors.py
- tests/test_sync_job_runner.py
This PR makes sure the sync cursor is stored to `SyncJob` when claiming the job, and the connector is updated with the latest `sync_cursor` when the sync job completes.
> Add incremental sync support to SyncJobRunner

- config.yml
- connectors/es/sink.py
- connectors/sources/sharepoint_online.py
- connectors/utils.py
- tests/sources/test_sharepoint_online.py
- tests/test_utils.py
Adds extraction service as a standalone service outside of connectors.
The extraction service is only initialised and used if the user has set `use_text_extraction_service: true`.
If enabled, it will send files to the [data-extraction-service](https://github.com/elastic/data-extraction-service), which will return the extracted text or any errors.
This content is added directly to the `body` of the document before indexing. No `_attachment` is added in this case.
* https://github.com/elastic/data-extraction-service/pull/11
> Add extraction service

- config.yml
- connectors/kibana.py
- connectors/services/job_execution.py
- requirements/tests.txt
- tests/ftest.sh
- tests/sources/fixtures/README.md
- tests/sources/fixtures/azure_blob_storage/config.yml
- tests/sources/fixtures/confluence/config.yml
- tests/sources/fixtures/dir/config.yml
- tests/sources/fixtures/fixture.py
- tests/sources/fixtures/google_cloud_storage/config.yml
- tests/sources/fixtures/jira/config.yml
- tests/sources/fixtures/mongodb/config.yml
- tests/sources/fixtures/mongodb/connector.json
- tests/sources/fixtures/mongodb_serverless/config.yml
- tests/sources/fixtures/mongodb_serverless/connector.json
- tests/sources/fixtures/mssql/config.yml
- tests/sources/fixtures/mssql/fixture.py
- tests/sources/fixtures/mysql/config.yml
- tests/sources/fixtures/mysql/connector.json
- tests/sources/fixtures/mysql/fixture.py
- tests/sources/fixtures/network_drive/config.yml
- tests/sources/fixtures/oracle/config.yml
- tests/sources/fixtures/oracle/fixture.py
- tests/sources/fixtures/postgresql/config.yml
- tests/sources/fixtures/postgresql/fixture.py
- tests/sources/fixtures/s3/config.yml
- tests/sources/fixtures/sharepoint/config.yml
- Removes "native" as the default way to start connectors
- enables ftests to run on their on config files, and with pre-determined connector ids (non-native)
- removes `sync_now` usage from ftests
- cleans up some testing logging
Cloned/forked connectors from connectors-python no longer run in "native" mode. Native mode is available exclusively on Elastic Cloud deployments.
> Attempt to use non-native default and ftest configs

- connectors/preflight_check.py
- tests/test_preflight_check.py
- Adds deprecation warnings when running in Native mode
- Adds a new config, `_force_allow_native`, which bypasses ignores these deprecation warnings.
* Corresponding ent-search pr: https://github.com/elastic/ent-search/pull/7558
Running self-managed connectors in "native" mode is deprecated starting in 8.9.0.
> deprecate native mode configurably

- connectors/sources/sharepoint_online.py
This PR removes the try/finally wrapper in get_docs for SPO. This was used to manage the extraction service session during a sync, but it could result in the session closing before syncing was complete.
Instead, the session should be closed when the connector does its post-sync cleanup.
The session opening is already handled dynamically within the extraction service.
> Refactor extraction service session handling

- connectors/protocol/connectors.py
- connectors/sources/mysql.py
- connectors/utils.py
- tests/protocol/test_connectors.py
This PR prefixes the target index for sync jobs of type `access_control` with `search-acl-filter-`, which is the prefix for access control indices.
> [DLS] Prefix target index for access control syncs

- connectors/es/sink.py
Found duplicate code block, reuse the existing method.
> Reuse enqueue_docs_to_delete method

- connectors/sources/sharepoint_online.py
- connectors/utils.py
- tests/test_utils.py
- Alphabetise `use_text_extraction_service` configurable field property ordering
- Add `ui_restrictions` to `use_text_extraction_service`
- Replace deprecated `.warn` with `.warning`
- Add missing `await`
> Fix minor issues with data extraction service

- connectors/kibana.py
- connectors/protocol/connectors.py
- connectors/services/job_scheduling.py
- docs/CONNECTOR_PROTOCOL.md
- tests/fixtures/connector.json
- tests/protocol/test_connectors.py
- tests/services/test_job_scheduling.py
- tests/sources/fixtures/mongodb/connector.json
- tests/sources/fixtures/mongodb_serverless/connector.json
- tests/sources/fixtures/mysql/connector.json
- tests/sources/fixtures/sharepoint_online/connector.json
This PR removes the `sync_now` flag support:
1. connector service won't schedule a sync job if this flag is set to `true`
2. remove `sync_now` from documentation
> Remove sync_now flag support

- connectors/sources/sharepoint_online.py
Found a string that is formatted without interpolation - fixing it.
> Use string interpolation for warning when Retry-After is not provided

- connectors/preflight_check.py
- tests/fake_sources.py
- tests/test_cli.py
- tests/test_preflight_check.py
See this slack thread: https://elastic.slack.com/archives/C01795T48LQ/p1686824151748759
A recent change switched our `config.yml` to use client mode and deprecate native mode. For folks who were used to using the default `config.yml` without changes, this caused their connectors to stop syncing without any clear error messaging. This PR aims to make the issue clear, and to fail-fast.
```
[FMWK][11:23:55][INFO] Preflight checks...
[FMWK][11:23:55][INFO] Waiting for NodeConfig(scheme='http', host='localhost', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, …
```
> Add preflight check for unmodified config

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
Found out that some of IDs that were used by the connector before are actually not unique.
For list items I'm mixing in ID of List object that contains items, for Web Pages I switch to `odata.id` - these seem unique.
> Properly populate ids for site pages and list items

- .buildkite/nightly_docker.yml
See fails on https://buildkite.com/elastic/connectors-python-nightly-dockers/builds/33#0188d13a-0658-4204-85e2-d59c71b7484e
Problem is with missing `.buildkite/nightly_docker.yml`.
> [8.7] Add nightly_docker.yml for docker builds

- config.yml
- connectors/es/sink.py
- connectors/sources/sharepoint_online.py
- connectors/sync_job_runner.py
- connectors/utils.py
- tests/sources/test_sharepoint_online.py
- tests/test_utils.py
Add the following misc changes to SharePoint Online local content extraction:
- Download files in either of the following cases:
- the pipeline `binary_content_extraction` is `True` 
- the configurable field `use_text_extraction_service` is `True`
- Use real file names in failed extraction logs
- Remove file size download limit when `use_text_extraction_service` is `True`
- Catch `ClientConnectionError` as well as `ServerTimeoutError`
> Log filename for failed extractions

- config.yml
- connectors/preflight_check.py
- tests/fixtures/config.yml
- tests/sources/fixtures/azure_blob_storage/config.yml
- tests/sources/fixtures/confluence/config.yml
- tests/sources/fixtures/dir/config.yml
- tests/sources/fixtures/google_cloud_storage/config.yml
- tests/sources/fixtures/jira/config.yml
- tests/sources/fixtures/mongodb/config.yml
- tests/sources/fixtures/mongodb_serverless/config.yml
- tests/sources/fixtures/mssql/config.yml
- tests/sources/fixtures/mysql/config.yml
- tests/sources/fixtures/network_drive/config.yml
- tests/sources/fixtures/oracle/config.yml
- tests/sources/fixtures/postgresql/config.yml
- tests/sources/fixtures/s3/config.yml
- tests/sources/fixtures/servicenow/config.yml
- tests/sources/fixtures/sharepoint/config.yml
- tests/test_preflight_check.py
Add a preflight check for the extraction service. This will only run when extraction service is enabled from configuration. The connector client should continue to run even if this check fails.
> Add extraction service preflight check

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
This PR adds incremental sync support for the Sharepoint Online connector.
The connector uses [Microsoft Graph API Delta queries](https://learn.microsoft.com/en-us/graph/delta-query-overview) to retrieve changes. 
The flow looks like this: 
1. When a customer creates a connector they need to run a full sync. A full sync will store `deltaLink` for each `site drive` in the connectors document (`sync_cursor)`. 
2. When customers run incremental sync it validates the `sync_cursor` property and if it is not correct or one of the tokens is expired, customers will get a message and will be asked to run a full sync to fix the `sync_cursor` object.
> [Sharepoint Online] Support incremental sync

- connectors/sources/mysql.py
- tests/sources/test_sharepoint_online.py
`test_get_docs_incrementally_with_empty_cursor` missed the decorator `pytest.mark.asyncio` and was therefore ignored.
> [Incremental Sync] Enable ignored test

- config.yml
- connectors/preflight_check.py
- connectors/sources/sharepoint_online.py
- connectors/utils.py
- tests/fixtures/config.yml
- tests/sources/fixtures/azure_blob_storage/config.yml
- tests/sources/fixtures/confluence/config.yml
- tests/sources/fixtures/dir/config.yml
- tests/sources/fixtures/google_cloud_storage/config.yml
- tests/sources/fixtures/jira/config.yml
- tests/sources/fixtures/mongodb/config.yml
- tests/sources/fixtures/mongodb_serverless/config.yml
- tests/sources/fixtures/mssql/config.yml
- tests/sources/fixtures/mysql/config.yml
- tests/sources/fixtures/network_drive/config.yml
- tests/sources/fixtures/oracle/config.yml
- tests/sources/fixtures/postgresql/config.yml
- tests/sources/fixtures/s3/config.yml
- tests/sources/fixtures/servicenow/config.yml
- tests/sources/fixtures/sharepoint_server/config.yml
- tests/sources/test_sharepoint_online.py
- tests/test_preflight_check.py
- tests/test_utils.py
Make the `extraction_service` config setting optional.
This is to prevent users from needing to manage this configuration even if they aren't using this feature.
- Revert all config changes made in https://github.com/elastic/connectors-python/pull/1089
- Convert configuration check-up to be based on `extraction_service` configuration presence rather than an enabled flag.
- Don't attempt to extract content if `extraction_service` has not been configured.
- Remove the file-pointer extraction method
- This feature did not make it in time for 8.9 FF on the data-extraction-service side, but we will re-add it in 8.10.
This is a follow-up PR based on feedback here: https://github.com/elastic/connectors-python/pull/1089#discussion_r1235272058
> Make extraction service config optional

- requirements/framework.txt
This will fix the dependency tree caused by this error: 
```
....
File "/Users/jedr/connectors-qa/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3170, in __init__
super(Requirement, self).__init__(requirement_string)
File "/Users/jedr/connectors-qa/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
stone (>=2.*)
~~~~^
make: *** [bin/elastic-ingest] Error 1
```
Related PRs: 
* https://github.com/dropbox/dropbox-sdk-python/pull/456/files
> Update Dropbox SDK to 11.36.2

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
- [[SPO] Check if DLS RFC is enabled (#1123)](https://github.com/elastic/connectors-python/pull/1123)
> [8.9] [SPO] Check if DLS RFC is enabled (#1123)

- connectors/sources/mysql.py
- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
Some domain group ids have a suffix starting with `_`. We need to remove this suffix to have a valid domain group id.
> [SPO] Remove domain group id suffixes starting with "_"

- connectors/sources/sharepoint_online.py
Found when running tests:
```
tests/sources/test_sharepoint_online.py::TestSharepointOnlineDataSource::test_get_docs_incrementaly
/Users/artemshelkovnikov/git_tree/connectors-py/tests/sources/test_sharepoint_online.py:1773: RuntimeWarning: coroutine 'SharepointOnlineDataSource._site_access_control' was never awaited
async for doc, download_func, operation in source.get_docs_incrementally(
Enable tracemalloc to get traceback where the object was allocated.
See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
```
Looks like `get_docs_incrementally` incorrectly collected permissions or just failed because of it.
> Fix missing await for _site_access_control in get_docs_incrementally for Sharepoint Online connector

- connectors/services/job_scheduling.py
- tests/services/test_job_scheduling.py
We need to run validation for connectors when filtering is enabled. The validation requires creating the instance of the connector, but somehow the code was never closing the connector to deallocate resources needed for validation.
This PR fixes it by closing the connector after the validation happens.
> Close data source after running a validation

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
Minor adjustment of debug messages for Sharepoint Online connector - when some drive items are ignored, no message is provided for them. This PR fixes it.
Additionally, this PR makes sure we just folders purely by checking drive_item for `folder` key.
> Add more verbose messages why drive item is not downloaded for SPO connector

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
Problem is that our `retryable` does not support defining which exception types are not retryable, so Sharepoint Online connector retries all calls.
Errors that are retried:
- ThrottledError - these are in general retryable errors that indicate that API is throttling
- PermissionsMissing - errors when server returns "Unauthorized". We can retry them after invalidating the token.
- InternalServerError - 500 errors sometimes also indicate throttling or just an error on the side of the API that's worth to retry
TODO: after this PR is merged we can follow up on our `@retryable` function to make it handle this case instead of us writing our own retryable abstractions.
> Make Sharepoint Online connector retry only specific errors

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
The incremental sync is used to ignore deleted files filtering them by `@microsoft.graph.downloadUrl`. It worked well when we checked that property first. However, the check was moved down so it made the service fail when the `folder` is deleted because deleted items don't have the `name` property.
This PR will add an explicit validation and ignore all deleted items.
> Ignore deleted files when choosing a download function

- .buildkite/nightly_steps.yml
- tests/ftest.sh
As discussed on a sprint sync, we want to disable some parts of Nightly tests for now that cause flaky behaviour.
Currently identified flaky behaviours:
1. MongoDB Serverless connector test is broken with no visible indication - probably need to revisit the test and see what's going on. This PR disables it.
2. MaxRSS setting choice seems to be a bit random and since we collect metrics every 5 seconds, that means that we could miss some spikes in RSS when running the connector functional test. This PR disables it.
The plan for now is to merge this change and have a [tech-debt issue](https://github.com/elastic/connectors-python/issues/1208) to address ASAP.
> Disable MongoDB serverless nightly + max-rss setting

- connectors/sources/sharepoint_online.py
Ensure that the field `_original_filename` is included in the doc for all attachments.
Also rename some variables for greater clarity.
> Get filename for all attachments

- connectors/sources/sharepoint_online.py
- connectors/utils.py
- tests/test_utils.py
Re-enable filepointers as an option for local data extraction.
_(The following instructions will also be added to our official documentation)_
To set this up:
- connectors-python must be run in docker
- you must also run data-extraction-service (use the branch in [this PR](https://github.com/elastic/data-extraction-service/pull/18) if it isn't merged yet)
- the two docker images must share a network and a volume (see below for instructions)
Sample config (note the `host` is no longer `localhost`):
```
extraction_service:
host: http://host.docker.internal:8090
use_file_pointers: true
shared_volume_dir: '/app/files'
```
First make a volume that will be used by both docker containers:
```bash
$ docker volume create --name connectors-volume
```
Follow the [instructions to run …
> Allow file pointers for local data extraction

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
There is no need to download files that can't be processed successfully in the extraction service or ingest pipeline.
> Do not download unsupported files

- connectors/sources/network_drive.py
- tests/sources/test_network_drive.py
Add an if-block in close method of Network Drive that checks if session was previously registered:
> Fix Ftest in Network Drive connector

- docs/reference/dropbox.md
Since the docs are nested under `reference` folder we need to tweak relative links. Right now clicking on them yields 404s.
> [Dropbox] Fix reference docs relative links 404s

- connectors/sources/sharepoint_online.py
- tests/sources/fixtures/sharepoint_online/connector.json
- tests/sources/test_sharepoint_online.py
Speeding up the ACL sync.
- fixes an id-vs-username bug
- Utilizes `$expand=transitiveMemberOf` in a bulk request, to reduce request volume
- Utilizes `$top` to cap out page size
- Utilizes `$filter` to fetch only active users, and not disabled users.
- Utilizes `$select` to fetch only the fields we need, which speeds up response time
- Removes fetching users from UserInformationList because that was broken, and we could not extract User Ids (to then fetch transitive group membership)
- https://github.com/elastic/kibana/pull/161798
- https://github.com/elastic/enterprise-search-pubs/pull/3627
> Performance improvements to the ACL sync

- connectors/sources/sharepoint_online.py
Two small changes bundled together:
- Inverted the retry policy for MicrosoftAPISession - it specifically does not retry `NotFound` and `ClientResponseError`, retried everything else (before it retried 4 specific error types, see changeset)
- Remove the semaphore code and make use of `aiohttp.TCPConnector(limit=X)` to limit aiohttp client maximum consequent call to X
> Use blocklist for retry policy + make user of aiohttp limiter

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
By using explicit `$select` clauses, we both increase performance and limit what types of fields we index. 
This change adds a few explicit select clauses, and reduces our total fields in a full sync of the koffelab dataset from ~224 to ~70 fields (not counting nested subfields).
There's a good chance that we'll eventually want to make the selected fields configurable.
> [SPO] Limit synced fields

- connectors/sources/sharepoint_online.py
This PR removes some dead code and changes the severity of the log to `info` when we hit HTTP throttling limits. This might be helpful if customers complain about their connectors' speed.
> [SPO] Logs improvements

- connectors/preflight_check.py
- connectors/protocol/connectors.py
- connectors/services/base.py
- connectors/services/job_cleanup.py
- connectors/services/job_execution.py
- connectors/services/job_scheduling.py
- tests/protocol/test_connectors.py
- tests/services/test_base.py
- tests/test_preflight_check.py
This PR makes the following services support both the new connectors config and the deprecated connector config in `config.yml`:
1. Job Scheduling service
2. Job Execution service
3. Job Cleanup service
4. Preflight check
Customers can now run multiple connector clients/customized connectors in one connector service.
> Support multiple connectors in services

- connectors/sources/dropbox_aiohttp.py
- tests/sources/test_dropbox_aiohttp.py
This PR contains the Dropbox connector implementation using `aiohttp` module. This PR aims to provide a better performance than Dropbox connector with SDK implementation (https://github.com/elastic/connectors-python/pull/1005).
> Dropbox connector code with AioHTTP

- connectors/sources/sharepoint_online.py
When the chunk_size is 1KB the maximum download speed is 14MB/s. 
When increased to 64KB the speed goes up ~ 95MB/s - which is the network thoughput limit in the testing hardware environment. 
Why 64KB? - it's default page size in the most SSD buffers. In the future, this options should be configurable.
> [SPO] Tune download/write chunk size

- .backportrc.json
This makes it so that anything labeled with `vpre-8.10-stable` can automatically be backported.
> Add backport automations for the pre-8.10 branch

- connectors/sources/sharepoint_online.py
- connectors/utils.py
- tests/sources/fixtures/sharepoint_online/connector.json
- tests/sources/test_sharepoint_online.py
- tests/test_utils.py
- [[SPO] Add configurable drive item permissions support (#1259)](https://github.com/elastic/connectors-python/pull/1259)
> [pre-8.10-stable] [SPO] Add configurable drive item permissions support (#1259)

- connectors/sources/sharepoint_online.py
- tests/sources/fixtures/sharepoint_online/connector.json
- tests/sources/test_sharepoint_online.py
- [[SPO] Add configurable unique page permissions support (#1264)](https://github.com/elastic/connectors-python/pull/1264)
> [pre-8.10-stable] [SPO] Add configurable unique page permissions support (#1264)

- connectors/sources/google_drive.py
- tests/sources/fixtures/google_drive/connector.json
Hide the service account JSON in the UI, mark it as sensitive field.
> [Google Drive] Obfuscate Service account JSON in the UI

- tests/ftest.sh
See https://elastic.slack.com/archives/C04KMMNAHGB/p1689772818319019
the ftest script ends by terminating the ingest processes. However, because of how we `set -e` and then try a combination of `kill` commands, if the process terminates before the final `kill` is issued, bash returns an error, and we fail the ftest. This PR:
1. only tries a `kill -KILL $PID` if the pid is still present 5 seconds after we tried the first `kill`. This reduces the chance of a race condition, but doesn't eliminate it.
2. sets `set +e` before we start killing things, because at that point, the test has passed, and we don't want to flag it as a failure because we cleaned up faster than expected.
> Remove race condition when killing ingest processes

- connectors/sources/mysql.py
- connectors/sources/sharepoint_online.py
- tests/commons.py
- tests/sources/fixtures/sharepoint_online/connector.json
- tests/sources/test_sharepoint_online.py
- tests/test_commons.py
This PR adds support for unique site list permissions, which broke the inheritance to their parent site. This is guarded through a new RFC `fetch_unique_list_permissions`.
Also added some missing tests around `site_lists` and extended the `AsyncIterator` with some new assertions (which are needed for the `site_lists` tests) and added missing tests for this class, too.
Note: a separate PR will be opened for the Kibana RFC
> [SPO] Add unique list permissions support

- connectors/sources/mysql.py
- tests/sources/test_sharepoint_online.py
Remove a duplicate `@pytest.mark.asyncio` decorator.
> [SPO] Remove duplicate test decorator

- connectors/sources/mysql.py
- tests/sources/test_sharepoint_online.py
We had two tests using the same name causing a linter warning. This PR deduplicates the test names.
> [SPO] Deduplicate test name

- connectors/sources/google_drive.py
Use async os stat operation to check file size
While checking implementation of `aiohttp_session` I realized that we can use `aiofiles` to get file size in non-blocking way. Here is the link to open-source repo: https://github.com/omarryhan/aiogoogle/blob/master/aiogoogle/sessions/aiohttp_session.py#L17
Use the same async approach in google drive connector.
> [Google Drive] Use async os stat operation to check file size

- connectors/sources/google_drive.py
Remove the print() statement that I used to verify and debug advanced RCF default value from the config
> [Google Drive] Remove debug print() statement

- tests/sources/fixtures/google_cloud_storage/fixture.py
Fixes GCS functional tests. Issue is that 2GB Elasticsearch is not able to chew through the data that comes in:
```
[FMWK][09:13:04][ERROR] Exception found for task Task-5611: ApiError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [2072318054/1.9gb], which is larger than the limit of [2040109465/1.8gb], real usage: [2061130016/1.9gb], new bytes reserved: [11188038/10.6mb], usages [fielddata=0/0b, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=11188038/10.6mb, request=0/0b]')
```
Option 1 would be to increase Elasticsearch size.
Option 2 was what I did - make the test suite respect DATA_SIZE env variable and reduce the default size of the test fixture for ftest.
> Fix GCS ingesting too much in ftest

- tests/sources/fixtures/sharepoint_online/config.yml
looks like a merge conflict with https://github.com/elastic/connectors-python/pull/1271
> New config syntax for SPO ftest

- docs/CONNECTOR_PROTOCOL.md
- docs/DEVELOPING.md
- Adds section that explains existing RCFs and their possible values
- Small fix in connector-protocol, the `validations.constraint` can also be a list, when `validations.type` is of  `included_in` type (see[ this code for refrerence](https://github.com/elastic/connectors-python/blob/main/connectors/source.py#L193)) 
- my vscode did some linting of .MD whitespace
The table might be tough to verify in github PR diff, I suggest viewing changes on my branch directly. [Preview link](https://github.com/elastic/connectors-python/blob/jedrazb-add-rich-configurable-fields-reference/docs/DEVELOPING.md#rich-configurable-fields)
> [Rich Configurable Fields] Add dev-friendly reference docs

- connectors/services/job_execution.py
- tests/services/test_job_execution.py
This PR makes use of the per-connector API key to run the sync job if it's configured.
> Use per-connector api key to sync data if configured

- connectors/services/base.py
- tests/services/test_base.py
When a connector is configured without a connector id, this config will be ignored and a warning message will be logged.:
```yaml
connectors:
-
service_type: mysql
```
> Ignore connector configurations with missing connector id

- tests/sources/fixtures/sharepoint_online/fixture.py
In #1269 the filzesize in ftests was increased significantly and it causes following errors: `elasticsearch.ApiError: ApiError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [2076451632/1.9gb], which is larger than the limit of [2040109465/1.8gb], real usage: [2076451632/1.9gb]`
> [SPO] Decrease the filesize for SPO ftests to fix nightlies

- tests/sources/fixtures/dropbox/config.yml
Fixes https://buildkite.com/elastic/connectors-python-nightly/builds/945#01899699-6871-4b2c-a428-6fd4b2bd9106
The new dropbox connector hadn't rebased on main recently, and missed the new yaml config structure
> Fix dropbox ftest config for new structure

- connectors/sources/github.py
- tests/sources/fixtures/github/fixture.py
- tests/sources/test_github.py
As discussed on slack, In GitHub we are indexing markdown files only.
> [GitHub] Index markdown files only

- connectors/utils.py
- tests/test_utils.py
During some testing it came up that we should have debug logs for successful text extraction.
This PR adds that log.
> Add debug log on successful text extraction

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
When `fetch_drive_item_permissions` is enabled don't propagate the `site_access_control` permissions to drive items
> [SPO] Change permission inheritance logic for driveItems

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
SPO Site admins should be included to ACL for a single site page by default
> [SPO] Propagate site admin access controls by default to site pages

- config.yml
- connectors/sources/salesforce.py
- tests/sources/test_salesforce.py
Adds the skeleton for Salesforce connector.
Includes the following basic functionality:
- configuration with validation
- ping
- get_token
> [Salesforce] Add salesforce connector skeleton

- .buildkite/pull-requests.json
doesn't work with our required CI step
See: https://github.com/elastic/connectors-python/pull/1119 and https://elastic.slack.com/archives/C02AV5C8ZDE/p1690793101153619?thread_ts=1690554027.660749&cid=C02AV5C8ZDE
> Remove ci skipping

- tests/sources/test_network_drive.py
The asyncio plugin is missing for one test.
> Add missing asyncio plugin

- tests/sources/fixtures/sharepoint_online/fixture.py
SPO fixture is fast, and connector is reasonably efficient. Connector is able to oversaturate a 2GB Elasticsearch cluster easily, thus I'm adding a small latency of 50ms to the requests so that connector would work closer to real-life SPO instance - that fixes the ingestion problem as a side-effect.
> Slow down SPO fake server to have 50ms latency

- connectors/sources/postgresql.py
- tests/sources/test_postgresql.py
This PR decouples `PostgreSQLDataSource` from `GenericBaseDataSource`. To make it easier to review, refactoring is not included in this PR, which will be added in a follow-up PR.
> Decouple PostgreSQLDataSource from GenericBaseDataSource

- connectors/logger.py
- tests/test_logger.py
This PR adds colored logging, so that log messages of different log levels will have different colors. This will only work in terminals, and logs for Cloud will remain unchanged.
Example output:
> Add colored logging

- config.yml
- connectors/sources/salesforce.py
- tests/sources/test_salesforce.py
This PR adds two things to the salesforce connector:
- `SalesforceSoqlBuilder` is a class that will be used to build soql queries for salesforce requests. This will be identical to how it is implemented in Workplace Search ([relevant code](https://github.com/elastic/ent-search/blob/main/connectors/lib/connectors/content_sources/salesforce/soql_query_builder.rb))
- `get_accounts` fetches all accounts for the current configured user and ingests that data as documents
There are many `TODO`s in this PR, so I can keep track of missing work. They will be addressed before the `salesforce-connector` branch is merged into main.
> [Salesforce] Add soql builder and ingest accounts

- connectors/sources/sharepoint_online.py
- [Stabilize SPO site page ids (#1384)](https://github.com/elastic/connectors-python/pull/1384)
> [8.9] Stabilize SPO site page ids (#1384)

- tests/sources/fixtures/servicenow/connector.json
Fixed Nightly CI - after recent commit to change default configs for ServiceNow connector, CI broke as default configs don't pass validation.
This PR adds `connector.json` file that contains stub username/password, so that connector passes validation.
> Add connector.json for ServiceNow

- connectors/sources/generic_database.py
- connectors/sources/postgresql.py
- tests/sources/test_generic_database.py
- tests/sources/test_postgresql.py
This PR refactor the `execute_query` function to `fetch` function, which
1. yields column names first if `fetch_columns` is true
2. fetches rows by `fetch_size` and yields rows one by one
3. uses `@retryable` to handle retry logic
> Refactor execute_query function

- .buildkite/pipeline.yml
Failures like from : https://buildkite.com/elastic/connectors-python/builds/7862#0189dbd4-eacf-4727-91f8-6b4f7f3b04f2
I noticed:
```
- label: "\U0001F528 Azure Blob Storage"
--
  | command:
  | - .buildkite/run_nigthly.sh azure_blob_storage small
  | - label: "\U0001F528 Postgresql"
  | command:
  | - .buildkite/run_nigthly.sh postgresql small
  | - {}
  | - label: "\U0001F528 Oracle Database"
  | command:
  | - .buildkite/run_nigthly.sh oracle small
  | - label: "\U0001F528 Sharepoint Server"
  | command:
```
And guessed that the `- {}` was the reason for the failure.
> Typo in new change checking step

- connectors/sources/mysql.py
- tests/test_utils.py
(No issue, this was a non-functional 2 minute change)
This PR splits up the `test_get_pem_format` tests to make it more obvious what exactly failed (I've struggled to detect a problem at a first glance, when I changed something in `get_pem_format`). Also corrected some variable name typos.
> [Refactoring] Split up test_get_pem_format tests

- connectors/sources/mysql.py
- connectors/sources/sharepoint_online.py
(No issue, since this is super trivial/just three renamings)
It seems to be a bad practice in python to shadow built-in names like `id` and `filter`. Variables with these names should end with `_` for being able to distinguish them from built-in functions and to not confuse many IDEs.
> [Refactoring] Remove shadow variables

- pytest.ini
- setup.cfg
- tests/sources/test_slack.py
This PR makes 2 things:
1. Makes our regular tests fail if a warning happens
2. Ignores several warnings that are not relevant to us (see comments in the ini file)
> Make tests fail on warnings; add some warnings to ignore list

- .ruff.toml
- connectors/logger.py
- connectors/source.py
- connectors/sources/github.py
- connectors/sources/google_drive.py
- connectors/sources/servicenow.py
- connectors/sources/sharepoint_online.py
- connectors/utils.py
- tests/conftest.py
- tests/es/test_settings.py
- tests/services/test_job_cleanup.py
- tests/sources/fixtures/confluence/fixture.py
- tests/sources/fixtures/google_drive/fixture.py
- tests/sources/fixtures/jira/fixture.py
- tests/sources/fixtures/sharepoint_server/fixture.py
- tests/sources/test_github.py
- tests/sources/test_mysql.py
- tests/test_source.py
Minor improvement:
Enabling `A` rules for `ruff`:
https://beta.ruff.rs/docs/rules/builtin-variable-shadowing/ - Checks for variable (and function) assignments that use the same name as a builtin.
https://beta.ruff.rs/docs/rules/builtin-argument-shadowing/ - Checks for any function arguments that use the same name as a builtin.
https://beta.ruff.rs/docs/rules/builtin-attribute-shadowing/ - Checks for any class attributes or methods that use the same name as a builtin.
> Enable linter rule to report shadowing issues

- connectors/sources/mysql.py
- tests/commons.py
- tests/sources/test_sharepoint_online.py
- tests/test_commons.py
This PR adds `assert_called_once_with` to the `AsyncIterator` fake class. This enables assertions checking that the `AsyncIterator` was called once with specific `*args` and `**kwargs` (need that for the GMail connector tests).
> [Commons] Add assert_called_once_with to AsyncIterator

- connectors/sources/onedrive.py
This PR aims to use updated method names of CacheWithTimeout, `get_value` and `set_value` instead of `get` and `set` used previously.
> Update OneDrive with utils change

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
Adding `_dls_enabled()` condition check for logic that fetches unique DLS permissions. Without this check, permissions are fetched even if DLS is disabled, making connector really slow (permission calls are expensive for DLS, plus some of them call for permissions in N+1 style: per item, which slows thing down more)
> Add _dls_enabled() before fetching unique permissions

- .isort.cfg
- .ruff.toml
- Makefile
- connectors/es/client.py
- requirements/tests.txt
Minor linter change - dropping standalone usage of `isort` because `ruff` already has it.
They have slight difference in import sorting, thus the changes in `connectors/es/client.py`
> Drop standalone isort and use one from ruff distribution

- connectors/sources/sharepoint_online.py
- tests/sources/fixtures/sharepoint_online/fixture.py
- tests/sources/test_sharepoint_online.py
This PR updates the logic that yields site pages and list item attachments. These fields are missing from objects as they are loaded with Rest API.
For site pages webUrl is populated from `EncodedAbsUrl` that is requested additionally.
For attachments it's populated from existing fields.
SPO connector now populates webUrl for Site Pages and List Item Attachments
> Populate webUrl for site pages and list item attachments

- connectors/sources/salesforce.py
- tests/sources/test_salesforce.py
Download `ContentDocument` SObjects that have a connection to existing SObjects.
A single `ContentDocument` can be connected to many SObjects through `ContentDocumentLinks`. This means duplicates are common. To prevent downloading or ingesting duplicates, we hold on to all `ContentDocument` ids until ingestion of all other SObjects is complete. We then ensure there are no duplicates among the files to download. 
When mapping the new doc for a `ContentDocument`, we retain a list of related SObject ids in the field `linked_ids`. These SObject ids are also the ids used in Elastic docs. (Happy to change the `linked_ids` field name).
`ContentDocuments` also have multiple `ContentVersions`. We ingest only the latest version through the relation `LatestPublishedVersion`.
All `ContentDocuments` …
> Download ContentDocuments and extract binary content

- config.yml
follow-up from https://github.com/elastic/connectors-python/pull/1404#issuecomment-1679150103, just reformats commented yaml
Note that now the comments should not be separated from the configs they describe, but configs have two lines of whitespace between them.
Also, configs are prefixed with a single `#` but comments are prefixed with `## `, which means that you can highlight the whole file and have your IDE "uncomment" it, and you still get valid yaml and meaningful comments.
> reformat config yaml

- connectors/sources/google_drive.py
In certain scenarios the `permissions.list` endpoint will result in `403 insufficientFilePermissions` error. 
For example: someone else (e.g. from outside org) shares a file with you, you then go to drive UI to the "shared with me" tab and share this with the SA with view-only access. This chain of permissions is insufficient according to google to fetch ACL for that file. (Surprisingly the editor access allows to fetch that). See full scenario described in: https://github.com/elastic/connectors-python/issues/1474
Before, the whole sync would fail if we failed to fetch permissions even for a single file. In this PR I'm adding a logic to handle this gracefully and log problematic filenames and corresponding exceptions. 
Also, for the sake of completeness I added …
> [Google Drive] Handle failures when fetching file ACLs

- tests/sources/test_mongo.py
MongoDB connector tests broke with new release of MongoDB client - `motor`C  lib depends on it with `>=4.4,<5` expression.
This PR updates the failing tests to not override `_get_socket` private method that is not defined in the new library version any more.
> Fix mongodb tests by removing mocking of _get_socket + patching admin ping call

- requirements/aarch64.txt
- requirements/x86_64.txt
See https://elastic.slack.com/archives/C01795T48LQ/p1692781505612279
The pymongo lib is pulled in not through our framework requirements.txt, but through the OS Arch requirements. It was pinned already in `arm64.txt`, but was pulled in transitively through `motor` from `arch64.txt` and `x86_64.txt`. Motor does not pin the version of pymongo, which means when installing from scratch, this dep can auto increment. 
At some point, we should look into why we're using different versions of pymongo depending on the architecture, but that's out of scope at the moment, as this PR is about creating stability, not opening a can of worms.
CI was breaking and was resolved with https://github.com/elastic/connectors-python/pull/1514. This PR just prevents us from getting in a similar spot in the future.
> lock pymongo version

- connectors/es/sink.py
Minor fix for broken log messages for access sync.
Previous refactoring changed the format of progress log messages, but access control syncs were affected.
Before the fix the message does not contain access control sync stats:
With this fix, access control syncs will use same format for logging as other syncs, for example:
```
[FMWK][11:19:59][INFO] [Connector id: 0GvSJooBdGhCfc5tqbUT, index name: search-spo, Sync job id: 02vVJooBdGhCfc5tYbWR] Sync progress -- created: 700 | updated: 0 | deleted: 0
[FMWK][11:20:06][INFO] [Connector id: 0GvSJooBdGhCfc5tqbUT, index name: search-spo, Sync job id: 02vVJooBdGhCfc5tYbWR] Sync progress -- created: 800 | updated: 0 | deleted: 0
[FMWK][11:20:12][INFO] [Connector id: 0GvSJooBdGhCfc5tqbUT, index name: search-spo, Sync job id: 02vVJooBdGhCfc5tYbWR] …
```
> Fix log message for access control sync after refactoring

- connectors/sources/gmail.py
- connectors/sources/google.py
- connectors/sources/google_drive.py
- connectors/sources/mysql.py
- tests/sources/test_gmail.py
- tests/sources/test_google.py
This PR moves the method `validate_service_account_json` from `google_drive.py` to the `google.py` module and also makes usage of it in `gmail.py` to avoid code duplication.
> [GMail/GDrive] Make validate_service_account_json a common method

- connectors/sources/azure_blob_storage.py
- connectors/sources/confluence.py
- connectors/sources/dropbox.py
- connectors/sources/github.py
- connectors/sources/network_drive.py
- connectors/sources/servicenow.py
- tests/sources/fixtures/azure_blob_storage/connector.json
- tests/sources/fixtures/confluence/connector.json
- tests/sources/fixtures/github/connector.json
- tests/sources/fixtures/network_drive/connector.json
- tests/sources/test_azure_blob_storage.py
- tests/sources/test_confluence.py
- tests/sources/test_dropbox.py
- tests/sources/test_github.py
- tests/sources/test_network_drive.py
- tests/sources/test_servicenow.py
Remove `value` field from connector default RCFs, allowing them to be initialised as a type-safe empty value.
- azure_blob_storage
- confluence
- dropbox
- github
- network_drive
- servicenow
- https://github.com/elastic/connectors-python/pull/1323
- https://github.com/elastic/connectors-python/pull/761
- https://github.com/elastic/connectors-python/pull/1540
> Remove value field from connector default RCFs (batch 2)

- connectors/sources/gmail.py
- connectors/sources/google_cloud_storage.py
- connectors/sources/google_drive.py
- connectors/sources/jira.py
- connectors/sources/onedrive.py
- tests/sources/fixtures/google_cloud_storage/connector.json
- tests/sources/fixtures/jira/connector.json
- tests/sources/test_gmail.py
- tests/sources/test_google_cloud_storage.py
- tests/sources/test_google_drive.py
- tests/sources/test_jira.py
Remove `value` field from connector default RCFs, allowing them to be initialised as a type-safe empty value.
- gmail
- google_cloud_storage
- google_drive
- jira
- onedrive
I refactored the `google_cloud_storage` and `google_drive` tests so they would also use `create_source` to generate their test source, bringing them in line with our other connector tests. I didn't update any actual tests, just the way they generate a source.
- https://github.com/elastic/connectors-python/pull/1323
- https://github.com/elastic/connectors-python/pull/761
- https://github.com/elastic/connectors-python/pull/1539
> Remove value field from connector default RCFs (batch 3)

- README.md
- [[DOCS] Update README.md (#1537)](https://github.com/elastic/connectors-python/pull/1537)
> [8.10] [DOCS] Update README.md (#1537)

- connectors/sources/slack.py
- tests/sources/test_slack.py
The slack connector will sync messages of past n days (n is configurable), and the time range was incorrect built which cased the latest messages are not synced. This PR fix the bug.
> Fix slack time range error

- connectors/sources/confluence.py
- connectors/sources/github.py
- connectors/sources/google_drive.py
- connectors/sources/jira.py
- connectors/sources/mongo.py
- connectors/sources/mssql.py
- connectors/sources/mysql.py
- connectors/sources/postgresql.py
When removing not-useful `value` fields from connector configurable fields, I mistakenly removed some bool-type values.
Fields with boolean type should always have an initial value.
- https://github.com/elastic/connectors-python/pull/761
- https://github.com/elastic/connectors-python/pull/1539
- https://github.com/elastic/connectors-python/pull/1540
- https://github.com/elastic/connectors-python/pull/1541
> Revert removed boolean `value` fields

- connectors/sources/gmail.py
- connectors/sources/google_drive.py
- connectors/sources/mysql.py
- connectors/utils.py
- tests/sources/test_gmail.py
- tests/test_utils.py
This PR adds an email address validation for the `subject` field in the GMail connector. It also moves common logic for validating an email address into the `utils.py` module to ensure consistent behavior accross connectors (we could swap out that logic later on with a more mature email address validation library, if we need to).
> [GMail] Validate subject RCF value

- tests/sources/test_mongo.py
- [Fix mongodb tests by removing mocking of _get_socket + patching admin ping call (#1514)](https://github.com/elastic/connectors-python/pull/1514)
> [8.9] Fix mongodb tests by removing mocking of _get_socket + patching admin ping call (#1514)

- tests/sources/test_mongo.py
- [Fix mongodb tests by removing mocking of _get_socket + patching admin ping call (#1514)](https://github.com/elastic/connectors-python/pull/1514)
> [pre-8.10-stable] Fix mongodb tests by removing mocking of _get_socket + patching admin ping call (#1514)

- connectors/sources/mysql.py
- tests/sources/fixtures/fixture.py
This PR adds a separate ftest logger to make it easier to distinguish between log messages from the ftest shell script and the python `fixture.py` module. This also allows different log levels for ftest + colored messages. 
Also added an info message, which action is executed, which makes it easier to understand the ftest lifecycle.
I didn't want to change every `print` statement in this PR to keep it small for now. Can be addressed in a follow-up.
> [FTest] Add separate ftest logger

- connectors/sources/gmail.py
- connectors/sources/google.py
- connectors/sources/google_cloud_storage.py
- connectors/sources/google_drive.py
- tests/sources/fixtures/description.txt
- tests/sources/test_google.py
- tests/sources/test_google_cloud_storage.py
`json.loads()` doesn't work with escaped JSON strings out of the box. This change adds additional logic that handles valid escaped json strings by essentially calling `json.loads` twice.
> [Google Drive/Storage/Gmail] Handle escaped json strings from user input

- connectors/es/client.py
- connectors/kibana.py
- connectors/preflight_check.py
- connectors/protocol/connectors.py
- requirements/tests.txt
- tests/test_kibana.py
- tests/test_preflight_check.py
This ensures the system indices are created by the connector on startup if not already present. 
**Release Note**
Connectors now create the connectors indices by indexing an empty document to trigger the Elasticsearch-installed index template.
> Ensure indices are created on startup

- requirements/framework.txt
- tests/test_utils.py
Small change - our `html_to_text` uses the following code:
```python
return BeautifulSoup(html, "lxml").get_text(separator="\n")
```
It does not properly work because `lxml` is not installed locally.
Once it's installed, the format of parsed html changes slightly (only line breaks are affected as it seems), so test is changed too.
> Include missing lxml library - beautifulsoup attempted to use it, but did not since library is not there

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
- [[SPO] Remove site_group_id and site_user_id (#1467)](https://github.com/elastic/connectors-python/pull/1467)
> [pre-8.10-stable] [SPO] Remove site_group_id and site_user_id (#1467)

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
When * is configured as site collections, skip site name validation, therefore, skip querying site collections.
> Skip site collection query if * is configured for site collections

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
- [Skip site collection query if * is configured for site collections (#1595)](https://github.com/elastic/connectors-python/pull/1595)
> [pre-8.10-stable] Skip site collection query if * is configured for site collections (#1595)

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
- [[SPO] Remove site_group_id and site_user_id (#1467)](https://github.com/elastic/connectors-python/pull/1467)
> [8.10] [SPO] Remove site_group_id and site_user_id (#1467)

- connectors/sources/mysql.py
- tests/sources/fixtures/fixture.py
This PR makes use of the newly introduced ftest logger. The print statements related to `DATA_SIZE` are not changed as they're used to set an environment variable through the caller script `ftest.sh`. 
Also improved some variables and log messages containing more accurate information about timeouts.
> [FTest] Use logger instead of print

- connectors/kibana.py
- connectors/sources/mysql.py
- tests/test_kibana.py
Currently the kibana fake used implicitly the framework logger, which lead to the following log messages:
`[FMWK][17:03:04][INFO] Prepare .elastic-connectors-v1 document`.
Considering that we want to refactor and improve ftests a lot in the future I think it's useful to separate the kibana fake logger for better debugability/traceability as it's conceptually not part of the framework, but a separate entity updating some elasticsearch indices. It's also only used during ftests.
The new log messages would look like:
`[KBN-FAKE][17:03:04][INFO] Prepare .elastic-connectors-v1 document`.
Now it's more clear, which different entities do what during an ftest.
I've also removed the logger assertion, which is a bad practice. I think it's more useful to assert on the actual client calls and not …
> [FTest] Separate Kibana fake logger from framework logger

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
We've had reports of 400 errors when issuing requests like:
```
GET /sites/<site_id>/_api/lists/GetByTitle('<list_title>')/items(41)/HasUniqueRoleAssignments
```
which is odd, since this should be a valid request, as far as we can tell from the docs. 
To prevent this from blocking syncs, we want to simply log a warning when this surfaces, and move on.
* a fuller implementation of generic and lenient error handling will be part of https://github.com/elastic/connectors-python/pull/1584
Log (but otherwise ignore) 400 errors that occasionally arise when requesting unique permissions from some Sharepoint Online List Items.
> catch 400 on list item unique role assignments

- connectors/sources/onedrive.py
- tests/sources/fixtures/onedrive/connector.json
- tests/sources/fixtures/onedrive/fixture.py
- tests/sources/test_onedrive.py
With the following change, the execution time is reduced by half 🎉 so it now takes 55 minutes in place of 2 hours to index 51k documents.
> Improve OneDrive Connector Performance

- connectors/sources/sharepoint_online.py
- connectors/utils.py
- tests/sources/test_sharepoint_online.py
This PR adds a linear backoff multiplier to the Sharepoint connector. Customers might experience throttling issues when connectors respect the `Retry-After` header.  
Also, this PR will change `DEFAULT_RETRY_COUNT` to 5 and `DEFAULT_BACKOFF_MULTIPLIER` to 5. These numbers are tested for the lowest Sharepoint tier.
Follow-up: 
* To make the retryable solution more consistent (handling retries based on the response error codes) a refactoring is required.
> Pass retry_count to the retry handler

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
- [Pass retry_count to the retry handler (#1601)](https://github.com/elastic/connectors-python/pull/1601)
> [8.10] Pass retry_count to the retry handler (#1601)

- connectors/config.py
- connectors/es/sink.py
- connectors/utils.py
- tests/test_sink.py
This PR adds a configurable max number of tries to bulk API calls.
> Add retryable to bulk api call

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
There are 2 exceptions reported (see the stacktrace): 
1. https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientPayloadError
2. RuntimeError: generator didn't stop after athrow()
The first can occur when the HTTP connection is lost. In its turn, the second issue arises because we don't let the async context manager finish its job. This leads to GeneratorExit which can't be caught by except Exception.
This PR will add a handler to catch `ClientPayloadError` and retry the requestion. `DEFAULT_RETRY_SECONDS` will be used in retries because the response payload can't be parsed. 
<details><summary>Original stack trace</summary>
```
[FMWK][17:57:53][DEBUG] [Sync Job id: ExTKlYoBw3jntSQT8Xn7, connector id: 2BSTj4oBw3jntSQTwXiF, index name: search-spo] Fetching url: …
```
> Handle aiohttp.ClientPayloadError

- connectors/sources/sharepoint_online.py
- tests/sources/test_sharepoint_online.py
- [[SPO] Add logic to handle sitegroups in ACL for drive_items and sites (#1659)](https://github.com/elastic/connectors-python/pull/1659)
> [pre-8.10-stable] [SPO] Add logic to handle sitegroups in ACL for drive_items and sites (#1659)
